// supabase/functions/main/verify_jwt_map.ts
//
// Per-function JWT enforcement, derived from supabase/config.toml's explicit
// `verify_jwt = false` entries. Any function NOT in this map defaults to
// `true` (Supabase's own platform default) - see index.ts's lookup.
//
// Regenerate by re-deriving from config.toml if it changes; this file is a
// snapshot, not a live read of config.toml (avoids adding a TOML parser
// dependency to the edge runtime for a value that changes rarely).
export const VERIFY_JWT_MAP: Record<string, boolean> = {
  "admin-reset-password": false,
  "anomaly-detection": false,
  "anomaly-detector": false,
  "autonomous-email": false,
  "calculate-lead-score": false,
  "carrier-scoring": false,
  "check-expiring-documents": false,
  "cleanup-logs": false,
  "create-franchise": false,
  "create-user": false,
  "delete-user": false,
  "email-scan": false,
  "email-stats": false,
  "escalate-message": false,
  "execute-sql-external": false,
  "export-data": false,
  "fleet-utilization": false,
  "get-account-label": false,
  "get-contact-label": false,
  "get-opportunity-full": false,
  "get-opportunity-label": false,
  "get-service-label": false,
  "ingest-linkedin": false,
  "ingest-web": false,
  "lead-event-webhook": false,
  "lead-scoring": false,
  "list-edge-functions": false,
  "margin-optimizer": false,
  "metrics-quotation": false,
  "mgl-quotation-api": false,
  "moderate-message": false,
  "plan-event-webhook": false,
  "predict-eta": false,
  "process-email-retention": false,
  "process-lead-assignments": false,
  "process-scheduled-emails": false,
  "process-sequences": false,
  "rate-engine": false,
  "remote-import": false,
  "restore-quotation-version": false,
  "revenue-forecasting": false,
  "route-email": false,
  "save-quotation-version": false,
  "search-emails": false,
  "send-web": false,
  "send-whatsapp": false,
  "subscription-plans": false,
  "sync-all-mailboxes": false,
  "sync-cn-hs-data": false,
  "sync-emails": false,
  "sync-emails-v2": false,
  "sync-hts-data": false,
  "win-probability": false,
  // Remaining functions with verify_jwt=false in config.toml, not in this
  // batch (needs-secrets or excluded) but included so this map stays
  // complete for future batches without regeneration:
  "ai-advisor": false,
  "ai-agent": false,
  "ai-message-assistant": false,
  "alert-notifier": false,
  "analyze-cargo-damage": false,
  "analyze-email-threat": false,
  "categorize-document": false,
  "classify-email": false,
  "container-demand": false,
  "domains-register": false,
  "domains-verify": false,
  "ensemble-demand": false,
  "exchange-oauth-token": false,
  "extract-bol-fields": false,
  "extract-invoice-items": false,
  "forecast-demand": false,
  "generate-quote-pdf": false,
  "ingest-email": false,
  "ingest-telegram": false,
  "nexus-copilot": false,
  "portal-chatbot": false,
  "process-franchise-import": false,
  "push-migrations-to-target": false,
  "risk-scoring": false,
  "route-optimization": false,
  "salesforce-sync-opportunity": false,
  "self-service-onboarding": false,
  "send-email": false,
  "smart-reply": false,
  "suggest-transport-mode": false,
};
