import type { UimNodeConfig } from './types';
import { uimValidationSchemas } from '@/modules/uim/validation/schemas';

const statusOptions = [
  { value: 'active', labelKey: 'uim.forms.options.active', labelDefault: 'Active' },
  { value: 'fulfilled', labelKey: 'uim.forms.options.fulfilled', labelDefault: 'Fulfilled' },
  { value: 'cancelled', labelKey: 'uim.forms.options.cancelled', labelDefault: 'Cancelled' },
];

export const uimNodeConfigs: Record<UimNodeConfig['key'], UimNodeConfig> = {
  overview: {
    key: 'overview',
    titleKey: 'uim.forms.overview.title',
    titleDefault: 'UIM Overview',
    subtitleKey: 'uim.forms.overview.subtitle',
    subtitleDefault: 'Configure module ownership and rollout checkpoints.',
    schema: uimValidationSchemas.overview,
    defaultValues: {
      module_name: '',
      owner_email: '',
      rollout_phase: 'phase_1',
      target_go_live_date: '',
      notes: '',
    },
    fields: [
      { name: 'module_name', type: 'text', labelKey: 'uim.forms.overview.moduleName', labelDefault: 'Module name', autoComplete: 'organization' },
      { name: 'owner_email', type: 'email', labelKey: 'uim.forms.overview.ownerEmail', labelDefault: 'Owner email', autoComplete: 'email' },
      {
        name: 'rollout_phase',
        type: 'select',
        labelKey: 'uim.forms.overview.rolloutPhase',
        labelDefault: 'Rollout phase',
        options: [
          { value: 'phase_1', labelKey: 'uim.forms.phase.1', labelDefault: 'Phase 1' },
          { value: 'phase_2', labelKey: 'uim.forms.phase.2', labelDefault: 'Phase 2' },
          { value: 'phase_3', labelKey: 'uim.forms.phase.3', labelDefault: 'Phase 3' },
          { value: 'phase_4', labelKey: 'uim.forms.phase.4', labelDefault: 'Phase 4' },
        ],
      },
      { name: 'target_go_live_date', type: 'date', labelKey: 'uim.forms.overview.goLiveDate', labelDefault: 'Target go-live date' },
      { name: 'notes', type: 'textarea', labelKey: 'uim.forms.overview.notes', labelDefault: 'Notes', max: 500 },
    ],
  },
  'item-master': {
    key: 'item-master',
    titleKey: 'uim.forms.itemMaster.title',
    titleDefault: 'Item Master',
    subtitleKey: 'uim.forms.itemMaster.subtitle',
    subtitleDefault: 'Manage SKU metadata and control thresholds.',
    schema: uimValidationSchemas['item-master'],
    defaultValues: {
      item_name: '',
      sku: '',
      sku_is_unique: false,
      category: '',
      uom: 'EA',
      reorder_point: 0,
      safety_stock: 0,
      length_cm: 0,
      width_cm: 0,
      height_cm: 0,
      weight_kg: 0,
    },
    includesDimensionBlock: true,
    fields: [
      { name: 'item_name', type: 'text', labelKey: 'uim.forms.itemMaster.itemName', labelDefault: 'Item name', autoComplete: 'off' },
      { name: 'sku', type: 'text', labelKey: 'uim.forms.itemMaster.sku', labelDefault: 'SKU', autoComplete: 'off' },
      { name: 'category', type: 'text', labelKey: 'uim.forms.itemMaster.category', labelDefault: 'Category', autoComplete: 'off' },
      {
        name: 'uom',
        type: 'select',
        labelKey: 'uim.forms.itemMaster.uom',
        labelDefault: 'Unit of measure',
        options: ['EA', 'KG', 'LB', 'L', 'BOX'].map((value) => ({
          value,
          labelKey: `uim.forms.itemMaster.uom.${value}`,
          labelDefault: value,
        })),
      },
      { name: 'reorder_point', type: 'number', labelKey: 'uim.forms.itemMaster.reorderPoint', labelDefault: 'Reorder point', min: 0, step: 1 },
      { name: 'safety_stock', type: 'number', labelKey: 'uim.forms.itemMaster.safetyStock', labelDefault: 'Safety stock', min: 0, step: 1 },
      { name: 'sku_is_unique', type: 'checkbox', labelKey: 'uim.forms.itemMaster.skuUnique', labelDefault: 'SKU uniqueness verified' },
    ],
  },
  'stock-ledger': {
    key: 'stock-ledger',
    titleKey: 'uim.forms.stockLedger.title',
    titleDefault: 'Stock Ledger',
    subtitleKey: 'uim.forms.stockLedger.subtitle',
    subtitleDefault: 'Capture immutable quantity movements with references.',
    schema: uimValidationSchemas['stock-ledger'],
    defaultValues: {
      item_id: '',
      transaction_type: 'RECEIVE',
      quantity_delta: 0,
      resulting_quantity: 0,
      transaction_at: '',
      reference: '',
    },
    fields: [
      { name: 'item_id', type: 'text', labelKey: 'uim.forms.stockLedger.itemId', labelDefault: 'Item ID', autoComplete: 'off' },
      {
        name: 'transaction_type',
        type: 'select',
        labelKey: 'uim.forms.stockLedger.transactionType',
        labelDefault: 'Transaction type',
        options: ['RECEIVE', 'RESERVE', 'RELEASE', 'CONSUME', 'ADJUST'].map((value) => ({
          value,
          labelKey: `uim.forms.stockLedger.transactionType.${value}`,
          labelDefault: value,
        })),
      },
      { name: 'quantity_delta', type: 'number', labelKey: 'uim.forms.stockLedger.quantityDelta', labelDefault: 'Quantity delta', min: 0, step: 1 },
      { name: 'resulting_quantity', type: 'number', labelKey: 'uim.forms.stockLedger.resultingQuantity', labelDefault: 'Resulting quantity', min: 0, step: 1 },
      { name: 'transaction_at', type: 'datetime-local', labelKey: 'uim.forms.stockLedger.transactionAt', labelDefault: 'Transaction at' },
      { name: 'reference', type: 'text', labelKey: 'uim.forms.stockLedger.reference', labelDefault: 'Reference', max: 120, autoComplete: 'off' },
    ],
  },
  reservations: {
    key: 'reservations',
    titleKey: 'uim.forms.reservations.title',
    titleDefault: 'Reservation Engine',
    subtitleKey: 'uim.forms.reservations.subtitle',
    subtitleDefault: 'Reserve inventory with availability-aware controls.',
    schema: uimValidationSchemas.reservations,
    defaultValues: {
      item_id: '',
      requested_quantity: 1,
      available_quantity: 0,
      reservation_status: 'active',
      expected_use_date: '',
      consumer_reference: '',
    },
    fields: [
      { name: 'item_id', type: 'text', labelKey: 'uim.forms.reservations.itemId', labelDefault: 'Item ID', autoComplete: 'off' },
      { name: 'requested_quantity', type: 'number', labelKey: 'uim.forms.reservations.requestedQuantity', labelDefault: 'Requested quantity', min: 1, step: 1 },
      { name: 'available_quantity', type: 'number', labelKey: 'uim.forms.reservations.availableQuantity', labelDefault: 'Available quantity', min: 0, step: 1 },
      { name: 'reservation_status', type: 'select', labelKey: 'uim.forms.reservations.status', labelDefault: 'Reservation status', options: statusOptions },
      { name: 'expected_use_date', type: 'date', labelKey: 'uim.forms.reservations.expectedUseDate', labelDefault: 'Expected use date' },
      { name: 'consumer_reference', type: 'text', labelKey: 'uim.forms.reservations.consumerReference', labelDefault: 'Consumer reference', autoComplete: 'off' },
    ],
  },
  'issue-consume': {
    key: 'issue-consume',
    titleKey: 'uim.forms.issueConsume.title',
    titleDefault: 'Issue & Consume',
    subtitleKey: 'uim.forms.issueConsume.subtitle',
    subtitleDefault: 'Execute issuance while validating available inventory.',
    schema: uimValidationSchemas['issue-consume'],
    defaultValues: {
      item_id: '',
      issue_quantity: 1,
      available_before_issue: 0,
      consume_immediately: true,
      technician_id: '',
      issued_at: '',
    },
    fields: [
      { name: 'item_id', type: 'text', labelKey: 'uim.forms.issueConsume.itemId', labelDefault: 'Item ID', autoComplete: 'off' },
      { name: 'issue_quantity', type: 'number', labelKey: 'uim.forms.issueConsume.issueQuantity', labelDefault: 'Issue quantity', min: 1, step: 1 },
      { name: 'available_before_issue', type: 'number', labelKey: 'uim.forms.issueConsume.availableBeforeIssue', labelDefault: 'Available before issue', min: 0, step: 1 },
      { name: 'consume_immediately', type: 'checkbox', labelKey: 'uim.forms.issueConsume.consumeImmediately', labelDefault: 'Consume immediately' },
      { name: 'technician_id', type: 'text', labelKey: 'uim.forms.issueConsume.technicianId', labelDefault: 'Technician ID', autoComplete: 'off' },
      { name: 'issued_at', type: 'datetime-local', labelKey: 'uim.forms.issueConsume.issuedAt', labelDefault: 'Issued at' },
    ],
  },
  restock: {
    key: 'restock',
    titleKey: 'uim.forms.restock.title',
    titleDefault: 'Dynamic Restock',
    subtitleKey: 'uim.forms.restock.subtitle',
    subtitleDefault: 'Plan replenishment based on threshold rules.',
    schema: uimValidationSchemas.restock,
    defaultValues: {
      item_id: '',
      current_quantity: 0,
      reorder_point: 0,
      recommended_restock_qty: 0,
      supplier_id: '',
      due_date: '',
    },
    fields: [
      { name: 'item_id', type: 'text', labelKey: 'uim.forms.restock.itemId', labelDefault: 'Item ID', autoComplete: 'off' },
      { name: 'current_quantity', type: 'number', labelKey: 'uim.forms.restock.currentQuantity', labelDefault: 'Current quantity', min: 0, step: 1 },
      { name: 'reorder_point', type: 'number', labelKey: 'uim.forms.restock.reorderPoint', labelDefault: 'Reorder point', min: 0, step: 1 },
      { name: 'recommended_restock_qty', type: 'number', labelKey: 'uim.forms.restock.recommendedQty', labelDefault: 'Recommended restock quantity', min: 0, step: 1 },
      { name: 'supplier_id', type: 'text', labelKey: 'uim.forms.restock.supplierId', labelDefault: 'Supplier ID', autoComplete: 'off' },
      { name: 'due_date', type: 'date', labelKey: 'uim.forms.restock.dueDate', labelDefault: 'Due date' },
    ],
  },
  locations: {
    key: 'locations',
    titleKey: 'uim.forms.locations.title',
    titleDefault: 'Location Registry',
    subtitleKey: 'uim.forms.locations.subtitle',
    subtitleDefault: 'Manage location metadata and geographic coverage.',
    schema: uimValidationSchemas.locations,
    defaultValues: {
      location_code: '',
      location_name: '',
      address_line_1: '',
      address_line_2: '',
      city: '',
      state_region: '',
      postal_code: '',
      country_code: '',
      latitude: 0,
      longitude: 0,
    },
    includesAddressBlock: true,
    fields: [
      { name: 'location_code', type: 'text', labelKey: 'uim.forms.locations.code', labelDefault: 'Location code', autoComplete: 'off' },
      { name: 'location_name', type: 'text', labelKey: 'uim.forms.locations.name', labelDefault: 'Location name', autoComplete: 'organization' },
      { name: 'latitude', type: 'number', labelKey: 'uim.forms.locations.latitude', labelDefault: 'Latitude', min: -90, max: 90, step: 0.000001 },
      { name: 'longitude', type: 'number', labelKey: 'uim.forms.locations.longitude', labelDefault: 'Longitude', min: -180, max: 180, step: 0.000001 },
    ],
  },
  analytics: {
    key: 'analytics',
    titleKey: 'uim.forms.analytics.title',
    titleDefault: 'Inventory Analytics',
    subtitleKey: 'uim.forms.analytics.subtitle',
    subtitleDefault: 'Run filtered analysis on inventory performance.',
    schema: uimValidationSchemas.analytics,
    defaultValues: {
      report_name: '',
      date_from: '',
      date_to: '',
      metric_group: 'inventory_health',
      include_archived: false,
    },
    fields: [
      { name: 'report_name', type: 'text', labelKey: 'uim.forms.analytics.reportName', labelDefault: 'Report name', autoComplete: 'off' },
      { name: 'date_from', type: 'date', labelKey: 'uim.forms.analytics.dateFrom', labelDefault: 'Date from' },
      { name: 'date_to', type: 'date', labelKey: 'uim.forms.analytics.dateTo', labelDefault: 'Date to' },
      {
        name: 'metric_group',
        type: 'select',
        labelKey: 'uim.forms.analytics.metricGroup',
        labelDefault: 'Metric group',
        options: [
          { value: 'inventory_health', labelKey: 'uim.forms.analytics.metric.inventoryHealth', labelDefault: 'Inventory health' },
          { value: 'reservation_efficiency', labelKey: 'uim.forms.analytics.metric.reservationEfficiency', labelDefault: 'Reservation efficiency' },
          { value: 'consumption_velocity', labelKey: 'uim.forms.analytics.metric.consumptionVelocity', labelDefault: 'Consumption velocity' },
        ],
      },
      { name: 'include_archived', type: 'checkbox', labelKey: 'uim.forms.analytics.includeArchived', labelDefault: 'Include archived records' },
    ],
  },
};
