import { Lead, LeadStatus } from '@/pages/dashboard/leads-data';
import { addDays, subDays, subHours } from 'date-fns';

export const mockUsers = [
  { id: 'u1', name: 'Sarah Wilson', email: 'sarah@example.com', role: 'Sales Manager', avatar: 'https://i.pravatar.cc/150?u=u1' },
  { id: 'u2', name: 'Mike Chen', email: 'mike@example.com', role: 'Account Executive', avatar: 'https://i.pravatar.cc/150?u=u2' },
  { id: 'u3', name: 'Jessica Jones', email: 'jessica@example.com', role: 'SDR', avatar: 'https://i.pravatar.cc/150?u=u3' },
];

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    created_at: subDays(new Date(), 2).toISOString(),
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@acme.corp',
    phone: '+1 555-0123',
    company: 'Acme Logistics',
    status: 'new',
    source: 'website',
    owner_id: 'u1',
    notes: 'Interested in international shipping rates.',
    lead_score: 85,
    last_activity_date: subHours(new Date(), 5).toISOString(),
    estimated_value: 50000,
    custom_fields: {},
    updated_at: new Date().toISOString(),
    tenant_id: 't1',
    franchise_id: 'f1',
    title: 'Logistics Manager',
    qualification_status: 'qualified',
    expected_close_date: addDays(new Date(), 30).toISOString(),
    description: 'Looking for a new freight forwarder.',
    converted_at: null
  },
  {
    id: 'l2',
    created_at: subDays(new Date(), 5).toISOString(),
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane@global.trade',
    phone: '+1 555-0124',
    company: 'Global Trade Inc',
    status: 'negotiation',
    source: 'referral',
    owner_id: 'u2',
    notes: 'Negotiating contract terms for Q3.',
    lead_score: 65,
    last_activity_date: subDays(new Date(), 1).toISOString(),
    estimated_value: 120000,
    custom_fields: {},
    updated_at: new Date().toISOString(),
    tenant_id: 't1',
    franchise_id: 'f1',
    title: 'Director of Ops',
    qualification_status: 'qualified',
    expected_close_date: addDays(new Date(), 15).toISOString(),
    description: null,
    converted_at: null
  },
  {
    id: 'l3',
    created_at: subDays(new Date(), 10).toISOString(),
    first_name: 'Robert',
    last_name: 'Johnson',
    email: 'rob@fastship.com',
    phone: '+1 555-0125',
    company: 'FastShip Delivery',
    status: 'won',
    source: 'linkedin',
    owner_id: 'u1',
    notes: 'Closed deal for fleet management.',
    lead_score: 95,
    last_activity_date: subDays(new Date(), 2).toISOString(),
    estimated_value: 250000,
    custom_fields: {},
    updated_at: new Date().toISOString(),
    tenant_id: 't1',
    franchise_id: 'f1',
    title: 'CEO',
    qualification_status: 'qualified',
    expected_close_date: subDays(new Date(), 2).toISOString(),
    description: 'Fleet expansion project.',
    converted_at: new Date().toISOString()
  },
  {
    id: 'l4',
    created_at: subDays(new Date(), 1).toISOString(),
    first_name: 'Emily',
    last_name: 'Davis',
    email: 'emily@tech.solutions',
    phone: '+1 555-0126',
    company: 'Tech Solutions',
    status: 'contacted',
    source: 'conference',
    owner_id: null,
    notes: 'Met at Logistics Expo.',
    lead_score: 45,
    last_activity_date: null,
    estimated_value: 15000,
    custom_fields: {},
    updated_at: new Date().toISOString(),
    tenant_id: 't1',
    franchise_id: 'f1',
    title: 'Supply Chain Analyst',
    qualification_status: 'unqualified',
    expected_close_date: null,
    description: null,
    converted_at: null
  },
  {
    id: 'l5',
    created_at: subDays(new Date(), 15).toISOString(),
    first_name: 'Michael',
    last_name: 'Brown',
    email: 'm.brown@import.export',
    phone: '+1 555-0127',
    company: 'Import Export Co',
    status: 'lost',
    source: 'cold_call',
    owner_id: 'u3',
    notes: 'Went with competitor.',
    lead_score: 20,
    last_activity_date: subDays(new Date(), 10).toISOString(),
    estimated_value: 0,
    custom_fields: {},
    updated_at: new Date().toISOString(),
    tenant_id: 't1',
    franchise_id: 'f1',
    title: 'Owner',
    qualification_status: 'disqualified',
    expected_close_date: null,
    description: null,
    converted_at: null
  }
];

export const mockActivities = [
  {
    id: 'a1',
    type: 'call',
    title: 'Introductory Call',
    description: 'Discussed initial requirements and timeline.',
    date: subDays(new Date(), 2).toISOString(),
    user: mockUsers[0],
    outcome: 'positive'
  },
  {
    id: 'a2',
    type: 'email',
    title: 'Proposal Sent',
    description: 'Sent initial proposal with pricing breakdown.',
    date: subDays(new Date(), 1).toISOString(),
    user: mockUsers[0],
    outcome: 'pending'
  },
  {
    id: 'a3',
    type: 'meeting',
    title: 'Contract Review',
    description: 'Reviewing terms with legal team.',
    date: new Date().toISOString(),
    user: mockUsers[1],
    outcome: 'scheduled'
  }
];

export const mockDocuments = [
  { id: 'd1', name: 'Contract_Draft_v1.pdf', size: '2.4 MB', type: 'pdf', uploaded_at: subDays(new Date(), 1).toISOString() },
  { id: 'd2', name: 'Pricing_Sheet.xlsx', size: '156 KB', type: 'spreadsheet', uploaded_at: subDays(new Date(), 2).toISOString() },
  { id: 'd3', name: 'Company_Profile.pptx', size: '5.1 MB', type: 'presentation', uploaded_at: subDays(new Date(), 5).toISOString() },
];
