import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Activity } from "lucide-react";
import { EmptyState } from "@/design-system";

export default function SignalsPage() {
  return (
    <DashboardLayout>
      <div className="mx-auto max-w-7xl space-y-6 p-6">
        <header className="flex items-start justify-between gap-4">
          <div>
            <h1 className="flex items-center gap-2 text-2xl font-semibold tracking-tight">
              <Activity className="h-5 w-5 text-muted-foreground" aria-hidden="true" />
              Signals
            </h1>
            <p className="text-sm text-muted-foreground">
              View AI-generated buy, sell, and hold signals across your instruments.
            </p>
          </div>
        </header>

        <EmptyState
          title="No signals yet"
          description="Signals are generated by the AI research engine based on price history, news sentiment, and strategy rules. They appear here with confidence scores and expiry times."
        />
      </div>
    </DashboardLayout>
  );
}
