#!/usr/bin/env bash
# mobile-build-markets — wrap `vite build && cap sync android` for the
# Sthira (Markets-only) mobile bundle.
#
# Detects the laptop's LAN IP at build time and bakes it into
# VITE_MARKETS_WORKER_URL so the Capacitor APK can reach the
# markets-worker over WiFi (no adb-reverse tunnel needed). The phone
# must be on the same WiFi as the laptop, AP isolation must be off,
# and the worker must be bound to 0.0.0.0:8001.
#
# Override at the CLI:
#   MARKETS_WORKER_URL=http://10.0.0.42:8001 ./scripts/mobile-build-markets.sh
# (e.g. for adb-reverse / USB-tethering / corporate dev setups)
#
# Usage:
#   npm run mobile:build:markets

set -euo pipefail

# Detect laptop LAN IP from en0 (Wi-Fi). Fall back to en1 (Ethernet), then
# scan ifconfig for the first non-loopback 192/10/172.16 address.
detect_lan_ip() {
  local ip
  for iface in en0 en1; do
    ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
    if [ -n "$ip" ]; then echo "$ip"; return 0; fi
  done
  ip=$(ifconfig 2>/dev/null \
    | awk '/^[a-z]/{iface=$1} /inet /{print iface, $2}' \
    | awk '$2 ~ /^(192\.168|10\.|172\.(1[6-9]|2[0-9]|3[01]))\./ {print $2; exit}')
  if [ -n "$ip" ]; then echo "$ip"; return 0; fi
  return 1
}

if [ -n "${MARKETS_WORKER_URL:-}" ]; then
  WORKER_URL="$MARKETS_WORKER_URL"
  echo "Using MARKETS_WORKER_URL override: $WORKER_URL"
else
  LAN_IP=$(detect_lan_ip || true)
  if [ -z "$LAN_IP" ]; then
    echo "✗ Could not detect a LAN IP. Set MARKETS_WORKER_URL=http://<ip>:8001 and retry." >&2
    exit 1
  fi
  WORKER_URL="http://${LAN_IP}:8001"
  echo "Detected laptop LAN IP: $LAN_IP"
fi

echo "Building Sthira markets-only bundle with VITE_MARKETS_WORKER_URL=$WORKER_URL"

# Regenerate the Android network security config so that cleartext to
# the *current* worker host is permitted. Android domain-config has no
# CIDR/wildcard support for IP addresses, so the LAN-IP path requires
# the exact host string in the XML — and that string changes whenever
# the laptop reconnects to a different network. Rewriting on every
# build avoids stale-IP "Mixed Content" failures in the WebView.
WORKER_HOST=$(echo "$WORKER_URL" | sed -E 's#^https?://##; s#:.*##')
NSC_PATH="android/app/src/main/res/xml/network_security_config.xml"
cat > "$NSC_PATH" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by scripts/mobile-build-markets.sh on $(date -Iseconds).
  Do not edit by hand — re-run \`npm run mobile:build:markets\` to
  refresh with the current laptop LAN IP. Base config keeps cleartext
  off for everything else (Supabase / LLM providers / hosted services
  remain HTTPS-only).
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">${WORKER_HOST}</domain>
    </domain-config>
</network-security-config>
EOF
echo "Wrote $NSC_PATH with cleartext-allow for: 127.0.0.1, localhost, ${WORKER_HOST}"

VITE_USE_DOMAIN_MANIFESTS=true \
VITE_DOMAIN_ONLY=markets \
VITE_MARKETS_WORKER_URL="$WORKER_URL" \
  vite build

npx cap sync android
