const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();
const fs = require('fs');
const path = require('path');

// 1. Setup Supabase Client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function runTest() {
  console.log('🚀 Starting New Branding System E2E Test...');

  // 2. Identify or Create a Test Tenant
  // We'll use a specific UUID for testing to avoid messing with real data if possible,
  // but for RLS to work, we might need a real user/tenant. 
  // We'll try to find an existing tenant first.
  const { data: tenants, error: tenantError } = await supabase
    .from('tenants')
    .select('id, name')
    .limit(1);

  if (tenantError || !tenants?.length) {
    throw new Error('❌ No tenants found. Cannot proceed.');
  }

  const tenantId = tenants[0].id;
  console.log(`✅ Using Tenant: ${tenants[0].name} (${tenantId})`);

  // 3. Configure Branding via quotation_configuration (The NEW System)
  const brandingConfig = {
    company_name: "Acme Logistics V2",
    primary_color: "#E63946", // Bright Red
    secondary_color: "#F1FAEE",
    header_text: "Excellence in Motion",
    footer_text: "Generated by Automated Test Suite",
    disclaimer_text: "This is a test disclaimer.\nIt should wrap correctly across multiple lines.\nLine 3."
  };

  console.log('📝 Updating quotation_configuration...');
  const { error: configError } = await supabase
    .from('quotation_configuration')
    .upsert({
      tenant_id: tenantId,
      branding_settings: brandingConfig
    }, { onConflict: 'tenant_id' });

  if (configError) {
    throw new Error(`❌ Failed to update config: ${configError.message}`);
  }
  console.log('✅ Branding configuration saved.');

  // 4. Create a Test Quote
  console.log('📝 Creating Test Quote...');
  const quoteNumber = `TEST-${Date.now()}`;
  
  // Need ports for the quote
  const { data: ports } = await supabase.from('ports_locations').select('id').limit(2);
  const originId = ports[0].id;
  const destId = ports[1].id;

  const { data: quote, error: quoteError } = await supabase
    .from('quotes')
    .insert({
      tenant_id: tenantId,
      quote_number: `BRAND-TEST-${Date.now()}`,
      title: `Branding Test Quote ${Date.now()}`,
      status: 'draft',
      origin_port_id: originId,
      destination_port_id: destId,
      valid_until: new Date(Date.now() + 86400000).toISOString(),
      created_by: '00000000-0000-0000-0000-000000000000', // Mock UUID
    })
    .select()
    .single();

  if (quoteError) throw new Error(`❌ Failed to create quote: ${quoteError.message}`);
  console.log(`✅ Quote Created: ${quote.quote_number} (${quote.id})`);

  // 5. Trigger PDF Generation
  console.log('🖨️  Generating PDF...');
  const generateUrl = `${supabaseUrl}/functions/v1/generate-quote-pdf`;
  
  const response = await fetch(generateUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${supabaseKey}`,
      'Content-Type': 'application/json',
      'x-bypass-key': 'test-branding-flow-secret-8822'
    },
    body: JSON.stringify({
      quoteId: quote.id,
      // We don't strictly need versionId for the basic PDF generation test if the function handles it,
      // but let's see if the function requires it. The function code uses quoteId and defaults version.
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`❌ PDF Generation Failed (${response.status}): ${text}`);
  }

  const result = await response.json();
  if (!result.content) throw new Error('❌ No PDF content returned');

  // 6. Save and Verify
  const buffer = Buffer.from(result.content, 'base64');
  const filename = `test_branding_v2_${quoteNumber}.pdf`;
  fs.writeFileSync(filename, buffer);
  
  console.log(`✅ PDF Saved to ${filename} (${buffer.length} bytes)`);
  console.log('🎉 Test Passed! The new branding system is operational.');
}

runTest().catch(e => {
  console.error(e);
  process.exit(1);
});
