-- markets.ai_briefs — stores AI Portfolio Advisor briefs generated by Claude.
-- Scoped by portfolio_id + scope; 30-minute soft cache enforced at API layer.

CREATE TABLE IF NOT EXISTS markets.ai_briefs (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    portfolio_id     uuid        NOT NULL REFERENCES markets.portfolios(id) ON DELETE CASCADE,
    scope            text        NOT NULL DEFAULT 'portfolio_advisor'
                                 CHECK (scope IN ('portfolio_advisor')),
    content          text        NOT NULL,
    generated_at     timestamptz NOT NULL DEFAULT now(),
    owner_user_id    uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
    tenant_id        uuid,
    created_at       timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ai_briefs_portfolio_scope
    ON markets.ai_briefs (portfolio_id, scope, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_briefs_owner
    ON markets.ai_briefs (owner_user_id, generated_at DESC);

-- RLS
ALTER TABLE markets.ai_briefs ENABLE ROW LEVEL SECURITY;

-- Users can only read their own briefs
CREATE POLICY "ai_briefs_select_own"
    ON markets.ai_briefs
    FOR SELECT
    USING (owner_user_id = auth.uid());

-- Service role (used by the Python worker) can insert
CREATE POLICY "ai_briefs_insert_service"
    ON markets.ai_briefs
    FOR INSERT
    WITH CHECK (true);

-- Grant read to authenticated users (RLS filters per-user)
GRANT SELECT ON markets.ai_briefs TO authenticated;
-- Worker uses service_role, so no extra grant needed for INSERT
