/**
 * Auto-generated types for the core.* Postgres schema.
 *
 * To regenerate after a core.* schema change:
 *   npm run db-types:generate:core
 *
 * Phase 0 stub: only the empty `core` schema exists (Phase 0.10). Real
 * table types land in Phase 1 (master §7.4) as audit_log, outbox,
 * llm_*, idempotency_keys, feature_flags, secrets, domains get lifted
 * from platform.*, and in Phase 2 as core.parties + relationships are
 * created.
 *
 * Once tables exist, this file becomes a thin re-export of database.ts
 * which is generated by the supabase CLI.
 *
 * See: docs/plans/2026-05-28-modules/core.md §3 target schema
 */

// When `database.ts` exists, this becomes:
//   export type { Database } from "./database.js";
// Until then, the stub keeps consumers compilable.

export type Database = {
  core: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

/**
 * Convenience type re-exports go here as core.* tables are added.
 * For example, once Phase 2 ships:
 *
 *   export type Party = Database['core']['Tables']['parties']['Row'];
 *   export type PartyInsert = Database['core']['Tables']['parties']['Insert'];
 *   export type PartyUpdate = Database['core']['Tables']['parties']['Update'];
 */
