openapi: 3.0.0
info:
  title: SOS Nexus Booking Mapping API
  description: API for mapping quotations to bookings, including validation and audit logging.
  version: 1.0.0
servers:
  - url: https://api.sos-nexus.com/v1
    description: Production Server
  - url: http://localhost:54321/functions/v1
    description: Local Development (Supabase)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ValidationResult:
      type: object
      properties:
        valid:
          type: boolean
        errors:
          type: array
          items:
            type: string
        warnings:
          type: array
          items:
            type: string
        quote_summary:
          type: object
          properties:
            total:
              type: number
            currency:
              type: string
    
    MappingAuditLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
        action:
          type: string
          enum: [VALIDATE, MAP, PREVIEW]
        status:
          type: string
          enum: [SUCCESS, FAILURE, WARNING]
        details:
          type: object

security:
  - bearerAuth: []

paths:
  /rpc/validate_quote_for_booking:
    post:
      summary: Validate a quote for booking conversion
      description: Performs business rule validation (credit check, expiry, status) before mapping.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                p_quote_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '401':
          description: Unauthorized
        '500':
          description: Server Error

  /rpc/convert_quote_to_booking:
    post:
      summary: Convert Quote to Booking
      description: Creates a new booking record from an existing quote, copying line items and preserving audit trail.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                p_quote_id:
                  type: string
                  format: uuid
                p_tenant_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Booking Created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                description: The ID of the newly created booking
