-- Seed all countries into public.countries using ISO codes and continent mapping
-- NOTE: Entries are idempotent via ON CONFLICT on code_iso2

BEGIN;

-- Helper CTE with country data: name, iso2, iso3, phone_code, continent_code
WITH countries(name, iso2, iso3, phone, cont) AS (
  VALUES
  -- North America
  ('United States','US','USA','+1','NA'),
  ('Canada','CA','CAN','+1','NA'),
  ('Mexico','MX','MEX','+52','NA'),
  ('Bahamas','BS','BHS','+1-242','NA'),
  ('Barbados','BB','BRB','+1-246','NA'),
  ('Cuba','CU','CUB','+53','NA'),
  ('Dominican Republic','DO','DOM','+1-809','NA'),
  ('Haiti','HT','HTI','+509','NA'),
  ('Jamaica','JM','JAM','+1-876','NA'),
  ('Trinidad and Tobago','TT','TTO','+1-868','NA'),
  ('Puerto Rico','PR','PRI','+1-787','NA'),

  -- South America
  ('Argentina','AR','ARG','+54','SA'),
  ('Bolivia','BO','BOL','+591','SA'),
  ('Brazil','BR','BRA','+55','SA'),
  ('Chile','CL','CHL','+56','SA'),
  ('Colombia','CO','COL','+57','SA'),
  ('Ecuador','EC','ECU','+593','SA'),
  ('Guyana','GY','GUY','+592','SA'),
  ('Paraguay','PY','PRY','+595','SA'),
  ('Peru','PE','PER','+51','SA'),
  ('Suriname','SR','SUR','+597','SA'),
  ('Uruguay','UY','URY','+598','SA'),
  ('Venezuela','VE','VEN','+58','SA'),

  -- Europe
  ('United Kingdom','GB','GBR','+44','EU'),
  ('Ireland','IE','IRL','+353','EU'),
  ('France','FR','FRA','+33','EU'),
  ('Germany','DE','DEU','+49','EU'),
  ('Spain','ES','ESP','+34','EU'),
  ('Portugal','PT','PRT','+351','EU'),
  ('Italy','IT','ITA','+39','EU'),
  ('Netherlands','NL','NLD','+31','EU'),
  ('Belgium','BE','BEL','+32','EU'),
  ('Luxembourg','LU','LUX','+352','EU'),
  ('Switzerland','CH','CHE','+41','EU'),
  ('Austria','AT','AUT','+43','EU'),
  ('Sweden','SE','SWE','+46','EU'),
  ('Norway','NO','NOR','+47','EU'),
  ('Denmark','DK','DNK','+45','EU'),
  ('Finland','FI','FIN','+358','EU'),
  ('Poland','PL','POL','+48','EU'),
  ('Czechia','CZ','CZE','+420','EU'),
  ('Slovakia','SK','SVK','+421','EU'),
  ('Hungary','HU','HUN','+36','EU'),
  ('Romania','RO','ROU','+40','EU'),
  ('Bulgaria','BG','BGR','+359','EU'),
  ('Greece','GR','GRC','+30','EU'),
  ('Croatia','HR','HRV','+385','EU'),
  ('Slovenia','SI','SVN','+386','EU'),
  ('Serbia','RS','SRB','+381','EU'),
  ('Bosnia and Herzegovina','BA','BIH','+387','EU'),
  ('North Macedonia','MK','MKD','+389','EU'),
  ('Albania','AL','ALB','+355','EU'),
  ('Montenegro','ME','MNE','+382','EU'),
  ('Kosovo','XK','XXK','+383','EU'),
  ('Ukraine','UA','UKR','+380','EU'),
  ('Moldova','MD','MDA','+373','EU'),
  ('Belarus','BY','BLR','+375','EU'),
  ('Russia','RU','RUS','+7','EU'),

  -- Africa
  ('Algeria','DZ','DZA','+213','AF'),
  ('Angola','AO','AGO','+244','AF'),
  ('Benin','BJ','BEN','+229','AF'),
  ('Botswana','BW','BWA','+267','AF'),
  ('Burkina Faso','BF','BFA','+226','AF'),
  ('Burundi','BI','BDI','+257','AF'),
  ('Cameroon','CM','CMR','+237','AF'),
  ('Cape Verde','CV','CPV','+238','AF'),
  ('Central African Republic','CF','CAF','+236','AF'),
  ('Chad','TD','TCD','+235','AF'),
  ('Comoros','KM','COM','+269','AF'),
  ('Congo (Brazzaville)','CG','COG','+242','AF'),
  ('Congo (Kinshasa)','CD','COD','+243','AF'),
  ('Côte d’Ivoire','CI','CIV','+225','AF'),
  ('Djibouti','DJ','DJI','+253','AF'),
  ('Egypt','EG','EGY','+20','AF'),
  ('Equatorial Guinea','GQ','GNQ','+240','AF'),
  ('Eritrea','ER','ERI','+291','AF'),
  ('Ethiopia','ET','ETH','+251','AF'),
  ('Gabon','GA','GAB','+241','AF'),
  ('Gambia','GM','GMB','+220','AF'),
  ('Ghana','GH','GHA','+233','AF'),
  ('Guinea','GN','GIN','+224','AF'),
  ('Guinea-Bissau','GW','GNB','+245','AF'),
  ('Kenya','KE','KEN','+254','AF'),
  ('Lesotho','LS','LSO','+266','AF'),
  ('Liberia','LR','LBR','+231','AF'),
  ('Libya','LY','LBY','+218','AF'),
  ('Madagascar','MG','MDG','+261','AF'),
  ('Malawi','MW','MWI','+265','AF'),
  ('Mali','ML','MLI','+223','AF'),
  ('Mauritania','MR','MRT','+222','AF'),
  ('Mauritius','MU','MUS','+230','AF'),
  ('Morocco','MA','MAR','+212','AF'),
  ('Mozambique','MZ','MOZ','+258','AF'),
  ('Namibia','NA','NAM','+264','AF'),
  ('Niger','NE','NER','+227','AF'),
  ('Nigeria','NG','NGA','+234','AF'),
  ('Rwanda','RW','RWA','+250','AF'),
  ('São Tomé and Príncipe','ST','STP','+239','AF'),
  ('Senegal','SN','SEN','+221','AF'),
  ('Seychelles','SC','SYC','+248','AF'),
  ('Sierra Leone','SL','SLE','+232','AF'),
  ('Somalia','SO','SOM','+252','AF'),
  ('South Africa','ZA','ZAF','+27','AF'),
  ('South Sudan','SS','SSD','+211','AF'),
  ('Sudan','SD','SDN','+249','AF'),
  ('Tanzania','TZ','TZA','+255','AF'),
  ('Togo','TG','TGO','+228','AF'),
  ('Tunisia','TN','TUN','+216','AF'),
  ('Uganda','UG','UGA','+256','AF'),
  ('Zambia','ZM','ZMB','+260','AF'),
  ('Zimbabwe','ZW','ZWE','+263','AF'),

  -- Asia
  ('China','CN','CHN','+86','AS'),
  ('India','IN','IND','+91','AS'),
  ('Japan','JP','JPN','+81','AS'),
  ('South Korea','KR','KOR','+82','AS'),
  ('North Korea','KP','PRK','+850','AS'),
  ('Singapore','SG','SGP','+65','AS'),
  ('Malaysia','MY','MYS','+60','AS'),
  ('Thailand','TH','THA','+66','AS'),
  ('Vietnam','VN','VNM','+84','AS'),
  ('Philippines','PH','PHL','+63','AS'),
  ('Indonesia','ID','IDN','+62','AS'),
  ('Pakistan','PK','PAK','+92','AS'),
  ('Bangladesh','BD','BGD','+880','AS'),
  ('Sri Lanka','LK','LKA','+94','AS'),
  ('Nepal','NP','NPL','+977','AS'),
  ('Bhutan','BT','BTN','+975','AS'),
  ('Myanmar','MM','MMR','+95','AS'),
  ('Laos','LA','LAO','+856','AS'),
  ('Cambodia','KH','KHM','+855','AS'),
  ('Mongolia','MN','MNG','+976','AS'),
  ('Taiwan','TW','TWN','+886','AS'),
  ('Hong Kong','HK','HKG','+852','AS'),
  ('Macau','MO','MAC','+853','AS'),
  ('United Arab Emirates','AE','ARE','+971','AS'),
  ('Saudi Arabia','SA','SAU','+966','AS'),
  ('Qatar','QA','QAT','+974','AS'),
  ('Kuwait','KW','KWT','+965','AS'),
  ('Bahrain','BH','BHR','+973','AS'),
  ('Oman','OM','OMN','+968','AS'),
  ('Iran','IR','IRN','+98','AS'),
  ('Iraq','IQ','IRQ','+964','AS'),
  ('Jordan','JO','JOR','+962','AS'),
  ('Israel','IL','ISR','+972','AS'),
  ('Lebanon','LB','LBN','+961','AS'),
  ('Syria','SY','SYR','+963','AS'),
  ('Turkey','TR','TUR','+90','AS'),

  -- Oceania
  ('Australia','AU','AUS','+61','OC'),
  ('New Zealand','NZ','NZL','+64','OC'),
  ('Fiji','FJ','FJI','+679','OC'),
  ('Papua New Guinea','PG','PNG','+675','OC'),
  ('Samoa','WS','WSM','+685','OC'),
  ('Tonga','TO','TON','+676','OC'),
  ('Solomon Islands','SB','SLB','+677','OC'),
  ('Vanuatu','VU','VUT','+678','OC'),

  -- Antarctica (no sovereign states)
  ('Antarctica','AQ','ATA',NULL,'AN')
) 
INSERT INTO public.countries (continent_id, name, code_iso2, code_iso3, code_national, phone_code, is_active)
SELECT
  (SELECT id FROM public.continents WHERE code_international = countries.cont),
  countries.name,
  countries.iso2,
  countries.iso3,
  NULL,
  countries.phone,
  true
FROM countries
ON CONFLICT (code_iso2)
DO UPDATE SET
  name = EXCLUDED.name,
  continent_id = EXCLUDED.continent_id,
  code_iso3 = EXCLUDED.code_iso3,
  phone_code = EXCLUDED.phone_code,
  is_active = EXCLUDED.is_active;

COMMIT;
