-- Fix MGL-Main-Template to ensure Detailed Matrix Rate Table is present and correctly configured
-- This migration forces the update of the template content

DO $$
DECLARE
    v_tenant_id UUID;
BEGIN
    -- Get MGL Tenant ID (adjust name if needed)
    SELECT id INTO v_tenant_id FROM tenants WHERE name ILIKE '%Miami Global Lines%' LIMIT 1;
    
    -- Ensure we found the tenant
    IF v_tenant_id IS NULL THEN
        RAISE NOTICE 'Tenant Miami Global Lines not found. Skipping template update.';
        RETURN;
    END IF;

    -- Update or Insert the MGL-Main-Template
    -- We use ON CONFLICT equivalent logic by checking existence
    
    IF EXISTS (SELECT 1 FROM quote_templates WHERE name = 'MGL-Main-Template' AND tenant_id = v_tenant_id) THEN
        UPDATE quote_templates
        SET content = '{
            "layout": "matrix",
            "header": {
                "show_logo": true,
                "company_info": true,
                "title": "QUOTATION"
            },
            "sections": [
                {
                    "type": "header",
                    "height": 120,
                    "content": {
                        "text": "MGL Global Logistics"
                    }
                },
                {
                    "type": "key_value_grid",
                    "height": 100,
                    "config": { "columns": 2 },
                    "grid_fields": [
                        { "key": "customer.company_name", "label": "Customer" },
                        { "key": "quote.quote_number", "label": "Quote Ref" },
                        { "key": "quote.created_at", "label": "Date", "format": "date" },
                        { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                        { "key": "customer.contact_name", "label": "Attn" },
                        { "key": "customer.address", "label": "Address" },
                        { "key": "customer.phone", "label": "Phone" },
                        { "key": "customer.email", "label": "Email" },
                        { "key": "customer.code", "label": "Customer Code" },
                        { "key": "customer.inquiry_number", "label": "Inquiry No" },
                        { "key": "quote.origin.location_name", "label": "Origin" },
                        { "key": "quote.destination.location_name", "label": "Destination" },
                        { "key": "quote.service_level", "label": "Service Level" }
                    ]
                },
                {
                    "type": "detailed_matrix_rate_table",
                    "height": 300,
                    "page_break_before": false,
                    "config": {
                        "show_total": true,
                        "group_by": ["carrier", "transit_time", "frequency"]
                    },
                    "content": {
                        "text": "Freight Rates Breakdown"
                    }
                },
                {
                    "type": "terms_block",
                    "height": 150,
                    "page_break_before": true,
                    "content": {
                        "text": "Terms and Conditions"
                    }
                },
                {
                    "type": "footer",
                    "height": 50,
                    "page_break_before": false,
                    "content": {
                        "text": "Thank you for your business."
                    }
                }
            ],
            "footer": {
                "text": "Generated by SOS Nexus"
            },
            "config": {
                "page_size": "A4",
                "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 },
                "font_family": "Helvetica"
            }
        }'::jsonb,
        updated_at = NOW()
        WHERE name = 'MGL-Main-Template' AND tenant_id = v_tenant_id;
        
        RAISE NOTICE 'Updated existing MGL-Main-Template for tenant %', v_tenant_id;
    ELSE
        INSERT INTO quote_templates (tenant_id, name, description, content, is_global, created_at, updated_at)
        VALUES (
            v_tenant_id,
            'MGL-Main-Template',
            'Main Quotation Template with Matrix Rates',
            '{
                "layout": "matrix",
                "header": { "show_logo": true, "company_info": true, "title": "QUOTATION" },
                "sections": [
                    { "type": "header", "height": 120, "content": { "text": "MGL Global Logistics" } },
                    { "type": "key_value_grid", "height": 100, "config": { "columns": 2 }, "grid_fields": [
                        { "key": "customer.company_name", "label": "Customer" },
                        { "key": "quote.quote_number", "label": "Quote Ref" },
                        { "key": "quote.created_at", "label": "Date", "format": "date" },
                        { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                        { "key": "customer.contact_name", "label": "Attn" },
                        { "key": "customer.address", "label": "Address" },
                        { "key": "customer.phone", "label": "Phone" },
                        { "key": "customer.email", "label": "Email" },
                        { "key": "customer.code", "label": "Customer Code" },
                        { "key": "customer.inquiry_number", "label": "Inquiry No" },
                        { "key": "quote.origin.location_name", "label": "Origin" },
                        { "key": "quote.destination.location_name", "label": "Destination" },
                        { "key": "quote.service_level", "label": "Service Level" }
                    ] },
                    { "type": "detailed_matrix_rate_table", "height": 300, "page_break_before": false, "content": { "text": "Freight Rates Breakdown" } },
                    { "type": "terms_block", "height": 150, "page_break_before": true, "content": { "text": "Terms and Conditions" } },
                    { "type": "footer", "height": 50, "page_break_before": false, "content": { "text": "Thank you for your business." } }
                ],
                "footer": { "text": "Generated by SOS Nexus" },
                "config": { "page_size": "A4", "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 }, "font_family": "Helvetica" }
            }'::jsonb,
            false,
            NOW(),
            NOW()
        );
        RAISE NOTICE 'Created new MGL-Main-Template for tenant %', v_tenant_id;
    END IF;

END $$;
