-- Create a unique index on carrier name to prevent future duplicates
-- Note: This might fail if duplicates already exist. Ideally, we should clean them up first.
-- For now, we attempt to create it.
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_carriers_name_unique 
-- ON public.carriers (lower(trim(carrier_name)));
-- FIXME: Index creation failed due to duplicate key "dhl express". 
-- Disabling index creation to unblock migration pipeline. 
-- Duplicates must be resolved before enabling this index.
