
-- Sync Domain: Trading & Procurement
-- Generated by scripts/sync_domains.js

BEGIN;

INSERT INTO public.platform_domains (code, name, description)
VALUES ('trading', 'Trading & Procurement', 'Sourcing, inspection, and trade finance services.')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'trading';
COMMIT;
*/
