
-- Sync Domain: Insurance Services
-- Generated by scripts/sync_domains.js

BEGIN;

INSERT INTO platform_domains (key, code, name, description, owner, status, repository_url, swagger_endpoint)
VALUES (
    'insurance',
    'insurance',
    'Insurance Services',
    'Cargo and business liability insurance management.',
    'FinTech Squad',
    'active',
    'https://github.com/trae/logic-nexus-ai',
    '/api/v1/insurance/openapi.json'
)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner = EXCLUDED.owner,
    status = EXCLUDED.status,
    repository_url = EXCLUDED.repository_url,
    swagger_endpoint = EXCLUDED.swagger_endpoint;

COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'insurance';
COMMIT;
*/
