-- Update MGL-Main-Template with Detailed Matrix Rate Table and Correct Keys
DO $$
DECLARE
    v_tenant_id UUID;
BEGIN
    -- Get MGL Tenant ID
    SELECT id INTO v_tenant_id FROM tenants WHERE name ILIKE '%Miami Global Lines%' LIMIT 1;
    
    -- Ensure we found the tenant
    IF v_tenant_id IS NULL THEN
        RAISE NOTICE 'Tenant Miami Global Lines not found. Skipping MGL-Main-Template update.';
        RETURN;
    END IF;

    -- Update the template
    UPDATE quote_templates
    SET content = '{
        "layout": "matrix",
        "header": {
            "show_logo": true,
            "company_info": true,
            "title": "QUOTATION"
        },
        "sections": [
            {
                "type": "header",
                "height": 120,
                "content": {
                    "text": "MGL Global Logistics"
                }
            },
            {
                "type": "key_value_grid",
                "height": 100,
                "grid_fields": [
                    { "key": "customer.company_name", "label": "Customer" },
                    { "key": "quote.quote_number", "label": "Quote Ref" },
                    { "key": "quote.created_at", "label": "Date", "format": "date" },
                    { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                    { "key": "customer.contact_name", "label": "Attn" },
                    { "key": "customer.address", "label": "Address" },
                    { "key": "customer.phone", "label": "Phone" },
                    { "key": "customer.email", "label": "Email" },
                    { "key": "customer.code", "label": "Customer Code" },
                    { "key": "customer.inquiry_number", "label": "Inquiry No" },
                    { "key": "quote.origin.location_name", "label": "Origin" },
                    { "key": "quote.destination.location_name", "label": "Destination" },
                    { "key": "quote.service_level", "label": "Service Level" }
                ]
            },
            {
                "type": "detailed_matrix_rate_table",
                "height": 300,
                "page_break_before": false,
                "content": {
                    "text": "Freight Rates"
                }
            },
            {
                "type": "terms_block",
                "height": 150,
                "page_break_before": false,
                "content": {
                    "text": "Terms and Conditions"
                }
            },
            {
                "type": "footer",
                "height": 50,
                "page_break_before": false,
                "content": {
                    "text": "Thank you for your business."
                }
            }
        ],
        "footer": {
            "text": "Generated by SOS Nexus"
        },
        "config": {
            "page_size": "A4",
            "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 },
            "font_family": "Helvetica"
        }
    }'::jsonb
    WHERE name = 'MGL-Main-Template' AND tenant_id = v_tenant_id;

END $$;
