-- Make tenant_id nullable for global templates
ALTER TABLE public.quote_templates ALTER COLUMN tenant_id DROP NOT NULL;

-- Insert 5 System Templates
INSERT INTO public.quote_templates (name, description, category, content, is_active, version) VALUES
(
    'Standard Multi-Modal',
    'Professional layout with header, rates table, and terms. Suitable for general logistics.',
    'General',
    '{
        "layout": "standard",
        "header": {
            "show_logo": true,
            "company_info": true
        },
        "sections": [
            { "type": "customer_info", "title": "Customer Details" },
            { "type": "shipment_info", "title": "Shipment Details" },
            { "type": "rates_table", "title": "Freight Rates", "columns": ["carrier", "transit_time", "frequency", "price"] },
            { "type": "terms", "title": "Terms & Conditions" }
        ],
        "footer": { "text": "Generated by SOS Nexus" }
    }'::jsonb,
    true,
    1
),
(
    'FCL Export Specialist',
    'Optimized for Full Container Load exports with detailed container specifications.',
    'Sea Freight',
    '{
        "layout": "fcl",
        "header": { "show_logo": true },
        "sections": [
            { "type": "customer_info" },
            { "type": "container_details", "fields": ["type", "quantity", "commodity"] },
            { "type": "rates_table", "columns": ["carrier", "container_type", "validity", "all_in_rate"] },
            { "type": "terms" }
        ]
    }'::jsonb,
    true,
    1
),
(
    'LCL Import Consolidator',
    'Focuses on weight/volume calculations and local charges.',
    'Sea Freight',
    '{
        "layout": "lcl",
        "header": { "show_logo": true },
        "sections": [
            { "type": "customer_info" },
            { "type": "cargo_details", "fields": ["packages", "weight", "volume", "chargeable_weight"] },
            { "type": "rates_table", "columns": ["carrier", "w_m_rate", "min_charge", "transit"] },
            { "type": "local_charges_table" },
            { "type": "terms" }
        ]
    }'::jsonb,
    true,
    1
),
(
    'Air Freight Express',
    'Streamlined template for time-critical air shipments.',
    'Air Freight',
    '{
        "layout": "air",
        "header": { "show_logo": true, "urgent_badge": true },
        "sections": [
            { "type": "route_info", "fields": ["airport_origin", "airport_dest", "flight_no"] },
            { "type": "rates_table", "columns": ["airline", "service_level", "transit_time", "rate_per_kg", "total"] },
            { "type": "terms" }
        ]
    }'::jsonb,
    true,
    1
),
(
    'Cross-Border Road',
    'Template for trucking and rail with pickup/delivery details.',
    'Road Freight',
    '{
        "layout": "road",
        "header": { "show_logo": true },
        "sections": [
            { "type": "address_details", "fields": ["pickup_address", "delivery_address"] },
            { "type": "vehicle_details", "fields": ["truck_type", "load_type"] },
            { "type": "rates_table", "columns": ["haulier", "transit_days", "price"] },
            { "type": "terms" }
        ]
    }'::jsonb,
    true,
    1
);
