-- US Port Codes Import (AESTIR)
-- Generated from official CBP Export Reference Data Excel
-- Imported Count: 439

BEGIN;

-- Ensure necessary columns exist
ALTER TABLE public.ports_locations 
ADD COLUMN IF NOT EXISTS port_type text[];

-- Create a temp table for import
CREATE TEMP TABLE temp_us_ports (
    location_code text,
    location_name text,
    city text,
    state_province text,
    country_code text,
    port_type text[],
    location_type text
);

INSERT INTO temp_us_ports (location_code, location_name, city, state_province, country_code, port_type, location_type) VALUES
('0101', 'SOUTH PORTLAND', 'SOUTH PORTLAND', 'ME', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0102', 'BANGOR', 'BANGOR', 'ME', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0103', 'EASTPORT', 'EASTPORT', 'ME', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0104', 'JACKMAN', 'JACKMAN', 'ME', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0105', 'VANCEBORO', 'VANCEBORO', 'ME', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0106', 'HOULTON', 'HOULTON', 'ME', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0107', 'FORT FAIRFIELD', 'FORT FAIRFIELD', 'ME', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('0108', 'VAN BUREN', 'VAN BUREN', 'ME', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0109', 'MADAWASKA', 'MADAWASKA', 'ME', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0110', 'FT KENT', 'FT KENT', 'ME', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0111', 'PORTLAND', 'PORTLAND', 'ME', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0112', 'BAR HARBOR', 'BAR HARBOR', 'ME', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0115', 'CALAIS', 'CALAIS', 'ME', 'US', '{"Passenger","Fixed","Vessel","Rail"}', 'seaport'),
('0118', 'LIMESTONE', 'LIMESTONE', 'ME', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0121', 'PORTLAND', 'PORTLAND', 'ME', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0122', 'PORTLAND', 'PORTLAND', 'ME', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0127', 'BRIDGEWATER', 'BRIDGEWATER', 'ME', 'US', '{"Rail","Passenger","Road","Air","Vessel"}', 'seaport'),
('0131', 'PORTSMOUTH', 'PORTSMOUTH', 'NH', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0132', 'BELFAST', 'BELFAST', 'ME', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0152', 'PORTLAND', 'PORTLAND', 'ME', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0182', 'MANCHESTER', 'MANCHESTER', 'NH', 'US', '{"Passenger","Road","Air"}', 'airport'),
('0201', 'ST. ALBANS', 'ST. ALBANS', 'VT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0203', 'RICHFORD', 'RICHFORD', 'VT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0206', 'BEECHER FALLS', 'BEECHER FALLS', 'VT', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('0207', 'SO BURLINGTON', 'SO BURLINGTON', 'VT', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('0209', 'DERBY LINE', 'DERBY LINE', 'VT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0211', 'NORTON', 'NORTON', 'VT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0212', 'HIGHGATE SPRING', 'HIGHGATE SPRING', 'VT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0401', 'BOSTON', 'BOSTON', 'MA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0402', 'SPRINGFIELD', 'SPRINGFIELD', 'MA', 'US', '{"Passenger","Air"}', 'airport'),
('0403', 'WORCESTER', 'WORCESTER', 'MA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0404', 'BEVERLY', 'BEVERLY', 'MA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0405', 'NEW BEDFORD', 'NEW BEDFORD', 'MA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0406', 'NEW BEDFORD', 'NEW BEDFORD', 'MA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0407', 'NEW BEDFORD', 'NEW BEDFORD', 'MA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0408', 'BEVERLY', 'BEVERLY', 'MA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0410', 'BRIDGEPORT', 'BRIDGEPORT', 'CT', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0411', 'WINDOSOR LOCKS', 'WINDOSOR LOCKS', 'CT', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0412', 'NEW HAVEN', 'NEW HAVEN', 'CT', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0413', 'HARTFORD', 'HARTFORD', 'CT', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0416', 'BEVERLY', 'BEVERLY', 'MA', 'US', '{"Passenger","Air"}', 'airport'),
('0417', 'EAST BOSTON', 'EAST BOSTON', 'MA', 'US', '{"Passenger","Air"}', 'airport'),
('0481', 'BEDFORD', 'BEDFORD', 'MA', 'US', '{"Passenger","Air"}', 'airport'),
('0501', 'PROVIDENCE', 'PROVIDENCE', 'RI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0502', 'PROVIDENCE', 'PROVIDENCE', 'RI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0503', 'PROVIDENCE', 'PROVIDENCE', 'RI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0701', 'OGDENSBURG', 'OGDENSBURG', 'NY', 'US', '{"Passenger","Vessel","Road"}', 'seaport'),
('0704', 'ROOSEVELTOWN', 'ROOSEVELTOWN', 'NY', 'US', '{"Passenger","Vessel","Road"}', 'seaport'),
('0706', 'ALEXANDRIA BAY', 'ALEXANDRIA BAY', 'NY', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0708', 'ALEXANDRIA BAY', 'ALEXANDRIA BAY', 'NY', 'US', '{"Passenger","Vessel","Road"}', 'seaport'),
('0712', 'CHAMPLAIN', 'CHAMPLAIN', 'NY', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('0714', 'OGDENSBURG', 'OGDENSBURG', 'NY', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0715', 'CONSTABLE', 'CONSTABLE', 'NY', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('0901', 'BUFFALO', 'BUFFALO', 'NY', 'US', '{"Rail","Passenger","Fixed","Air","Vessel"}', 'seaport'),
('0903', 'ROCHESTER', 'ROCHESTER', 'NY', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0904', 'N. SYRACUSE', 'N. SYRACUSE', 'NY', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0905', 'BUFFALO', 'BUFFALO', 'NY', 'US', '{"Passenger","Vessel"}', 'seaport'),
('0906', 'SYRACUSE', 'SYRACUSE', 'NY', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('0981', 'BINGHAMTON', 'BINGHAMTON', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('1001', 'NEWARK', 'NEWARK', 'NJ', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1002', 'ALBANY', 'ALBANY', 'NY', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1101', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1102', 'NEW CASTLE', 'NEW CASTLE', 'DE', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1103', 'NEW CASTLE', 'NEW CASTLE', 'DE', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1104', 'PITTSBURGH', 'PITTSBURGH', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1105', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1106', 'AVOCA', 'AVOCA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1107', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1108', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1109', 'MECHANICSBURG', 'MECHANICSBURG', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1119', 'ALLENTOWN, PA', 'ALLENTOWN, PA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1182', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1183', 'PHILADELPHIA', 'PHILADELPHIA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1195', 'PHILADEPHIA', 'PHILADEPHIA', 'PA', 'US', '{"Passenger","Air"}', 'airport'),
('1301', 'BALTIMORE', 'BALTIMORE', 'MD', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1302', 'BALTIMORE', 'BALTIMORE', 'MD', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1303', 'BALTIMORE', 'BALTIMORE', 'MD', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1304', 'BALTIMORE', 'BALTIMORE', 'MD', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1305', 'BALTIMORE', 'BALTIMORE', 'MD', 'US', '{"Passenger","Air"}', 'airport'),
('1401', 'NORFOLK', 'NORFOLK', 'VA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1404', 'RICHMOND', 'RICHMOND', 'VA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1409', 'CHARLESTON', 'CHARLESTON', 'WV', 'US', '{"Passenger","Air"}', 'airport'),
('1410', 'RICHMOND', 'RICHMOND', 'VA', 'US', '{"Passenger","Air"}', 'airport'),
('1412', 'DUBLIN', 'DUBLIN', 'VA', 'US', '{"Passenger","Air"}', 'airport'),
('1501', 'WILMINGTON', 'WILMINGTON', 'NC', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1502', 'GREENSBORO', 'GREENSBORO', 'NC', 'US', '{"Passenger","Air"}', 'airport'),
('1503', 'RALEIGH', 'RALEIGH', 'NC', 'US', '{"Passenger","Air"}', 'airport'),
('1511', 'MOREHEAD CITY', 'MOREHEAD CITY', 'NC', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1512', 'CHARLOTTE', 'CHARLOTTE', 'NC', 'US', '{"Passenger","Air"}', 'airport'),
('1601', 'CHARLESTON', 'CHARLESTON', 'SC', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1602', 'CHARLESTON', 'CHARLESTON', 'SC', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1603', 'GREER', 'GREER', 'SC', 'US', '{"Passenger","Air"}', 'airport'),
('1604', 'WEST COLUMBIA', 'WEST COLUMBIA', 'SC', 'US', '{"Passenger","Air"}', 'airport'),
('1681', 'MYRTLE BEACH', 'MYRTLE BEACH', 'SC', 'US', '{"Passenger","Air"}', 'airport'),
('1701', 'BRUNSWICK', 'BRUNSWICK', 'GA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1703', 'SAVANNAH', 'SAVANNAH', 'GA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1704', 'ATLANTA', 'ATLANTA', 'GA', 'US', '{"Passenger","Air"}', 'airport'),
('1801', 'TAMPA', 'TAMPA', 'FL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1803', 'JACKSONVILLE', 'JACKSONVILLE', 'FL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1805', 'FERNANDINA BCH', 'FERNANDINA BCH', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1807', 'TAMPA', 'TAMPA', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1808', 'ORLANDO', 'ORLANDO', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1809', 'SANFORD', 'SANFORD', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1814', 'CLEARWATER', 'CLEARWATER', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1816', 'CAPE CANAVERAL', 'CAPE CANAVERAL', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1818', 'PANAMA CITY', 'PANAMA CITY', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1819', 'PENSACOLA', 'PENSACOLA', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1821', 'PALMETTO', 'PALMETTO', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1822', 'FORT MYERS', 'FORT MYERS', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1880', 'NAPLES', 'NAPLES', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1883', 'SARASOTA', 'SARASOTA', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1884', 'DAYTONA BEACH', 'DAYTONA BEACH', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1885', 'MELBOURNE', 'MELBOURNE', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1887', 'LEESBURG', 'LEESBURG', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1888', 'ORLANDO', 'ORLANDO', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1889', 'ST AUGUSTINE', 'ST AUGUSTINE', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('1901', 'MOBILE', 'MOBILE', 'AL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('1902', 'GULFPORT', 'GULFPORT', 'MS', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1903', 'PASCAGOULA', 'PASCAGOULA', 'MS', 'US', '{"Passenger","Vessel"}', 'seaport'),
('1904', 'BIRMINGHAM', 'BIRMINGHAM', 'AL', 'US', '{"Passenger","Air"}', 'airport'),
('1910', 'HUNTSVILLE', 'HUNTSVILLE', 'AL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2001', 'CUT OFF', 'CUT OFF', 'LA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2002', 'NEW ORLEANS', 'NEW ORLEANS', 'LA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2003', 'LITTLE ROCK', 'LITTLE ROCK', 'AR', 'US', '{"Passenger","Air"}', 'airport'),
('2004', 'BATON ROUGE', 'BATON ROUGE', 'LA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2006', 'MEMPHIS', 'MEMPHIS', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2007', 'NASHVILLE', 'NASHVILLE', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2008', 'CHATTANOOGA', 'CHATTANOOGA', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2010', 'GRAMERCY', 'GRAMERCY', 'LA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2011', 'FLOWOOD', 'FLOWOOD', 'MS', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2015', 'FLOWOOD', 'FLOWOOD', 'MS', 'US', '{"Passenger","Air"}', 'airport'),
('2016', 'KNOXVILLE,', 'KNOXVILLE,', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2017', 'LAKE CHARLES', 'LAKE CHARLES', 'LA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2018', 'SHREVEPORT', 'SHREVEPORT', 'LA', 'US', '{"Passenger","Air"}', 'airport'),
('2027', 'BLOUNTVILLE', 'BLOUNTVILLE', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2095', 'MEMPHIS', 'MEMPHIS', 'TN', 'US', '{"Passenger","Air"}', 'airport'),
('2101', 'PORT ARTHUR', 'PORT ARTHUR', 'TX', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2102', 'PORT ARTHUR', 'PORT ARTHUR', 'TX', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2103', 'PORT ARTHUR', 'PORT ARTHUR', 'TX', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2104', 'PORT ARTHUR', 'PORT ARTHUR', 'TX', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2301', 'BROWNSVILLE', 'BROWNSVILLE', 'TX', 'US', '{"Rail","Passenger","Fixed","Road","Air","Vessel"}', 'seaport'),
('2302', 'DEL RIO', 'DEL RIO', 'TX', 'US', '{"Passenger","Road"}', 'terminal'),
('2303', 'EAGLE PASS', 'EAGLE PASS', 'TX', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('2304', 'LAREDO', 'LAREDO', 'TX', 'US', '{"Rail","Passenger","Fixed","Road","Air"}', 'airport'),
('2305', 'PHARR,', 'PHARR,', 'TX', 'US', '{"Passenger","Fixed","Road","Air"}', 'airport'),
('2307', 'RIO GRANDE CITY', 'RIO GRANDE CITY', 'TX', 'US', '{"Passenger","Road"}', 'terminal'),
('2309', 'PROGRESO', 'PROGRESO', 'TX', 'US', '{"Passenger","Road"}', 'terminal'),
('2310', 'ROMA', 'ROMA', 'TX', 'US', '{"Passenger","Road"}', 'terminal'),
('2383', 'HARLINGEN', 'HARLINGEN', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('2402', 'EL PASO', 'EL PASO', 'TX', 'US', '{"Rail","Passenger","Fixed","Road","Air"}', 'airport'),
('2403', 'PRESIDIO', 'PRESIDIO', 'TX', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('2404', 'TORNILLO', 'TORNILLO', 'TX', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('2406', 'COLUMBUS', 'COLUMBUS', 'NM', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('2407', 'ALBUQUERQUE', 'ALBUQUERQUE', 'NM', 'US', '{"Passenger","Air"}', 'airport'),
('2408', 'SANTA TERESA', 'SANTA TERESA', 'NM', 'US', '{"Passenger","Road"}', 'terminal'),
('2481', 'SANTA TERESA', 'SANTA TERESA', 'NM', 'US', '{"Passenger","Air"}', 'airport'),
('2501', 'SAN DIEGO', 'SAN DIEGO', 'CA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2502', 'WINTERHAVEN', 'WINTERHAVEN', 'CA', 'US', '{"Passenger","Road"}', 'terminal'),
('2503', 'CALEXICO', 'CALEXICO', 'CA', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('2504', 'SAN YSIDRO', 'SAN YSIDRO', 'CA', 'US', '{"Passenger","Fixed","Rail","Air"}', 'airport'),
('2505', 'TECATE', 'TECATE', 'CA', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('2506', 'SAN DIEGO', 'SAN DIEGO', 'CA', 'US', '{"Rail","Passenger","Fixed","Road","Air"}', 'airport'),
('2507', 'CALEXICO', 'CALEXICO', 'CA', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('2601', 'DOUGLAS', 'DOUGLAS', 'AZ', 'US', '{"Passenger","Fixed","Road"}', 'terminal'),
('2602', 'LUKEVILLE', 'LUKEVILLE', 'AZ', 'US', '{"Passenger","Road"}', 'terminal'),
('2603', 'NACO', 'NACO', 'AZ', 'US', '{"Passenger","Road"}', 'terminal'),
('2604', 'NOGALES', 'NOGALES', 'AZ', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('2605', 'PHOENIX', 'PHOENIX', 'AZ', 'US', '{"Passenger","Air"}', 'airport'),
('2606', 'SASABE', 'SASABE', 'AZ', 'US', '{"Passenger","Road"}', 'terminal'),
('2608', 'SAN LUIS', 'SAN LUIS', 'AZ', 'US', '{"Passenger","Road"}', 'terminal'),
('2609', 'TUCSON', 'TUCSON', 'AZ', 'US', '{"Passenger","Air"}', 'airport'),
('2704', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2709', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2711', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2712', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2713', 'PORT HUENEME', 'PORT HUENEME', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2715', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2719', 'LONG BEACH', 'LONG BEACH', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2720', 'LOS ANGELES', 'LOS ANGELES', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2721', 'ONTARIO', 'ONTARIO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2722', 'LAS VEGAS', 'LAS VEGAS', 'NV', 'US', '{"Passenger","Air"}', 'airport'),
('2770', 'LOS ANGELES', 'LOS ANGELES', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2775', 'LOS ANGELES', 'LOS ANGELES', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2776', 'LOS ANGELES', 'LOS ANGELES', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2781', 'PALM SPRINGS', 'PALM SPRINGS', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2782', 'SAN BERNARDINO', 'SAN BERNARDINO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2786', 'BAKERSFIELD', 'BAKERSFIELD', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2791', 'LOS ANGELES', 'LOS ANGELES', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2795', 'ONTARIO', 'ONTARIO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2801', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2802', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2803', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2805', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2809', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2810', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2811', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('2812', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2813', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2815', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2820', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2821', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2827', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2828', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2829', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2830', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2833', 'RENO', 'RENO', 'NV', 'US', '{"Passenger","Air"}', 'airport'),
('2834', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2835', 'SACRAMENTO', 'SACRAMENTO', 'CA', 'US', '{"Passenger","Vessel","Road","Air"}', 'seaport'),
('2870', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2871', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2872', 'SAN FRANCISCO', 'SAN FRANCISCO', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2895', 'OAKLAND', 'OAKLAND', 'CA', 'US', '{"Passenger","Air"}', 'airport'),
('2901', 'ASTORIA', 'ASTORIA', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2902', 'NEWPORT', 'NEWPORT', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2903', 'NORTH BEND', 'NORTH BEND', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2904', 'PORTLAND', 'PORTLAND', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2905', 'LONGVIEW', 'LONGVIEW', 'WA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2907', 'BOISE', 'BOISE', 'ID', 'US', '{"Passenger","Air"}', 'airport'),
('2908', 'PORTLAND', 'PORTLAND', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2909', 'PORTLAND', 'PORTLAND', 'OR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('2910', 'PORTLAND', 'PORTLAND', 'OR', 'US', '{"Passenger","Air"}', 'airport'),
('3001', 'SEATTLE', 'SEATTLE', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3002', 'TACOMA', 'TACOMA', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3003', 'ABDERDEEN', 'ABDERDEEN', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3004', 'BLAINE', 'BLAINE', 'WA', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('3005', 'BELLINGHAM', 'BELLINGHAM', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3006', 'EVERETT', 'EVERETT', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3007', 'PORT ANGELES', 'PORT ANGELES', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3008', 'PORT TOWNSEND', 'PORT TOWNSEND', 'WA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3009', 'SUMAS', 'SUMAS', 'WA', 'US', '{"Passenger","Fixed","Rail"}', 'railway_terminal'),
('3010', 'ANACORTES', 'ANACORTES', 'WA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3011', 'LOOMIS', 'LOOMIS', 'WA', 'US', '{"Passenger","Road"}', 'terminal'),
('3012', 'DANVILLE', 'DANVILLE', 'WA', 'US', '{"Passenger","Road"}', 'terminal'),
('3013', 'CURLEW', 'CURLEW', 'WA', 'US', '{"Passenger","Road"}', 'terminal'),
('3014', 'FRIDAY HARBOR', 'FRIDAY HARBOR', 'WA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3015', 'COLVILLE', 'COLVILLE', 'WA', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3016', 'LAURIER', 'LAURIER', 'WA', 'US', '{"Rail","Passenger","Road","Air"}', 'airport'),
('3017', 'POINT ROBERTS', 'POINT ROBERTS', 'WA', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('3018', 'SEATTLE', 'SEATTLE', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3019', 'OROVILLE', 'OROVILLE', 'WA', 'US', '{"Passenger","Road","Air"}', 'airport'),
('3020', 'NORTHPORT', 'NORTHPORT', 'WA', 'US', '{"Passenger","Road"}', 'terminal'),
('3022', 'SPOKANE', 'SPOKANE', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3023', 'LYNDEN', 'LYNDEN', 'WA', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3025', 'METALINE FALLS', 'METALINE FALLS', 'WA', 'US', '{"Passenger","Road"}', 'terminal'),
('3026', 'TACOMA', 'TACOMA', 'WA', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3029', 'SEATTLE', 'SEATTLE', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3071', 'SEATTLE', 'SEATTLE', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3072', 'SEATAC', 'SEATAC', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3073', 'SEATAC', 'SEATAC', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3074', 'SEATAC', 'SEATAC', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3082', 'MOSES LAKE', 'MOSES LAKE', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3095', 'SEATAC', 'SEATAC', 'WA', 'US', '{"Passenger","Air"}', 'airport'),
('3101', 'JUNEAU', 'JUNEAU', 'AK', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3102', 'KETCHIKAN', 'KETCHIKAN', 'AK', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3103', 'SKAGWAY', 'SKAGWAY', 'AK', 'US', '{"Rail","Passenger","Road","Air","Vessel"}', 'seaport'),
('3104', 'TOK', 'TOK', 'AK', 'US', '{"Passenger","Road","Air"}', 'airport'),
('3105', 'WRANGELL', 'WRANGELL', 'AK', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3106', 'HAINES', 'HAINES', 'AK', 'US', '{"Passenger","Vessel","Road","Air"}', 'seaport'),
('3111', 'FAIRBANKS', 'FAIRBANKS', 'AK', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3115', 'SITKA', 'SITKA', 'AK', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3126', 'ANCHORAGE', 'ANCHORAGE', 'AK', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3195', 'ANCHORAGE', 'ANCHORAGE', 'AK', 'US', '{"Passenger","Air"}', 'airport'),
('3196', 'ANCHORAGE', 'ANCHORAGE', 'AK', 'US', '{"Passenger","Air"}', 'airport'),
('3201', 'HONOLULU', 'HONOLULU', 'HI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3202', 'KAILUA-KONA', 'KAILUA-KONA', 'HI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3203', 'KAHULUI', 'KAHULUI', 'HI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3204', 'HONOLULU', 'HONOLULU', 'HI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3205', 'HONOLULU', 'HONOLULU', 'HI', 'US', '{"Passenger","Air"}', 'airport'),
('3206', 'KAILUA-KONA', 'KAILUA-KONA', 'HI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3295', 'HONOLULU', 'HONOLULU', 'HI', 'US', '{"Passenger","Air"}', 'airport'),
('3301', 'RAYMOND', 'RAYMOND', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3302', 'EASTPORT', 'EASTPORT', 'ID', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3303', 'SALT LAKE CITY', 'SALT LAKE CITY', 'UT', 'US', '{"Passenger","Air"}', 'airport'),
('3304', 'GREAT FALLS', 'GREAT FALLS', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3305', 'BUTTE', 'BUTTE', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3306', 'TURNER', 'TURNER', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3307', 'DENVER', 'DENVER', 'CO', 'US', '{"Passenger","Air"}', 'airport'),
('3308', 'PORTHILL', 'PORTHILL', 'ID', 'US', '{"Passenger","Road"}', 'terminal'),
('3309', 'SCOBEY', 'SCOBEY', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3310', 'SWEETGRASS', 'SWEETGRASS', 'MT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3316', 'BABB', 'BABB', 'MT', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3317', 'OPHEIM', 'OPHEIM', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3318', 'EUREKA', 'EUREKA', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3319', 'LORING', 'LORING', 'MT', 'US', '{"Passenger"}', 'terminal'),
('3321', 'WHITLASH', 'WHITLASH', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3322', 'CUT BANK', 'CUT BANK', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3323', 'HAVRE', 'HAVRE', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3324', 'KALISPELL', 'KALISPELL', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3325', 'HAVRE', 'HAVRE', 'MT', 'US', '{"Passenger","Road"}', 'terminal'),
('3384', 'ENGLEWOOD', 'ENGLEWOOD', 'CO', 'US', '{"Passenger","Air"}', 'airport'),
('3385', 'GYPSUM', 'GYPSUM', 'CO', 'US', '{"Passenger","Air"}', 'airport'),
('3386', 'BELGRADE', 'BELGRADE', 'MT', 'US', '{"Passenger","Air"}', 'airport'),
('3401', 'PEMBINA', 'PEMBINA', 'ND', 'US', '{"Rail","Passenger","Fixed","Road","Air"}', 'airport'),
('3403', 'PORTAL', 'PORTAL', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3404', 'NECHE', 'NECHE', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3405', 'ST JOHN', 'ST JOHN', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3406', 'FLAXTON', 'FLAXTON', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3407', 'WALHALLA', 'WALHALLA', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3408', 'HANNAH', 'HANNAH', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3409', 'SARLES', 'SARLES', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3410', 'AMBROSE', 'AMBROSE', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3411', 'FARGO,', 'FARGO,', 'ND', 'US', '{"Passenger","Air"}', 'airport'),
('3413', 'ANTLER', 'ANTLER', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3414', 'SHERWOOD', 'SHERWOOD', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3415', 'HANSBORO', 'HANSBORO', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3416', 'MAIDA', 'MAIDA', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3417', 'FORTUNA', 'FORTUNA', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3419', 'WESTHOPE', 'WESTHOPE', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3420', 'NOONAN', 'NOONAN', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3421', 'SOURIS', 'SOURIS', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3422', 'DUNSEITH', 'DUNSEITH', 'ND', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3423', 'WARROAD', 'WARROAD', 'MN', 'US', '{"Rail","Passenger","Road"}', 'railway_terminal'),
('3424', 'BAUDETTE', 'BAUDETTE', 'MN', 'US', '{"Passenger","Road"}', 'terminal'),
('3425', 'ROSEAU', 'ROSEAU', 'MN', 'US', '{"Passenger","Road"}', 'terminal'),
('3426', 'ROSEAU', 'ROSEAU', 'MN', 'US', '{"Passenger","Road"}', 'terminal'),
('3427', 'GRAND FORKS', 'GRAND FORKS', 'ND', 'US', '{"Passenger","Air"}', 'airport'),
('3430', 'LANCASTER', 'LANCASTER', 'MN', 'US', '{"Passenger","Fixed","Road"}', 'terminal'),
('3433', 'WILLISTON', 'WILLISTON', 'ND', 'US', '{"Passenger","Air"}', 'airport'),
('3434', 'MINOT', 'MINOT', 'ND', 'US', '{"Passenger","Air"}', 'airport'),
('3501', 'SAINT PAUL', 'SAINT PAUL', 'MN', 'US', '{"Passenger","Air"}', 'airport'),
('3502', 'SIOUX FALLS', 'SIOUX FALLS', 'SD', 'US', '{"Passenger","Air"}', 'airport'),
('3510', 'DULUTH', 'DULUTH', 'MN', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3511', 'DULUTH', 'DULUTH', 'MN', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3512', 'OMAHA', 'OMAHA', 'NE', 'US', '{"Passenger","Air"}', 'airport'),
('3513', 'DES MOINES', 'DES MOINES', 'IA', 'US', '{"Passenger","Air"}', 'airport'),
('3581', 'ROCHESTER', 'ROCHESTER', 'MN', 'US', '{"Passenger","Air"}', 'airport'),
('3604', 'INT''L FALLS', 'INT''L FALLS', 'MN', 'US', '{"Rail","Passenger","Road","Air","Vessel"}', 'seaport'),
('3613', 'GRAND PORTAGE', 'GRAND PORTAGE', 'MN', 'US', '{"Passenger","Vessel","Road"}', 'seaport'),
('3701', 'MILWAUKEE', 'MILWAUKEE', 'WI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3702', 'GREEN BAY', 'GREEN BAY', 'WI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3703', 'GREEN BAY', 'GREEN BAY', 'WI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3706', 'GREEN BAY', 'GREEN BAY', 'WI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3707', 'GREEN BAY', 'GREEN BAY', 'WI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3708', 'RACINE', 'RACINE', 'WI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3801', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Rail","Passenger","Fixed","Air","Vessel"}', 'seaport'),
('3802', 'PORT HURON', 'PORT HURON', 'MI', 'US', '{"Rail","Passenger","Fixed","Road","Vessel"}', 'seaport'),
('3803', 'SAULT STE MARIE', 'SAULT STE MARIE', 'MI', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('3804', 'FREELAND', 'FREELAND', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3805', 'BATTLE CREEK', 'BATTLE CREEK', 'MI', 'US', '{"Vessel"}', 'seaport'),
('3806', 'GRAND RAPIDS', 'GRAND RAPIDS', 'MI', 'US', '{"Passenger","Air"}', 'airport'),
('3807', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Air"}', 'airport'),
('3808', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3809', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3814', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Rail","Passenger","Vessel","Road"}', 'seaport'),
('3815', 'GRAND RAPIDS', 'GRAND RAPIDS', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3816', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3818', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3819', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3842', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3843', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3881', 'DETROIT', 'DETROIT', 'MI', 'US', '{"Passenger","Air"}', 'airport'),
('3882', 'YPSILANTI', 'YPSILANTI', 'MI', 'US', '{"Passenger","Air"}', 'airport'),
('3883', 'LANSING', 'LANSING', 'MI', 'US', '{"Passenger","Air"}', 'airport'),
('3901', 'ROSEMONT', 'ROSEMONT', 'IL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('3902', 'PEORIA,', 'PEORIA,', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('3905', 'CHICAGO', 'CHICAGO', 'IL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('3908', 'MILAN,', 'MILAN,', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('3909', 'ROCKFORD', 'ROCKFORD', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('3910', 'CHICAGO', 'CHICAGO', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('3971', 'ROSEMONT', 'ROSEMONT', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('3983', 'WHEELING', 'WHEELING', 'IL', 'US', '{"Air"}', 'airport'),
('3984', 'WEST CHICAGO', 'WEST CHICAGO', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('4101', 'MIDDLEBURG HTS', 'MIDDLEBURG HTS', 'OH', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4102', 'ERLANGER,', 'ERLANGER,', 'KY', 'US', '{"Passenger","Air"}', 'airport'),
('4103', 'GROVEPORT', 'GROVEPORT', 'OH', 'US', '{"Passenger","Air"}', 'airport'),
('4104', 'VANDALIA', 'VANDALIA', 'OH', 'US', '{"Passenger","Air"}', 'airport'),
('4105', 'TOLEDO', 'TOLEDO', 'OH', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4106', 'ERIE', 'ERIE', 'PA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4110', 'INDIANAPOLIS', 'INDIANAPOLIS', 'IN', 'US', '{"Passenger","Air"}', 'airport'),
('4115', 'LOUISVILLE', 'LOUISVILLE', 'KY', 'US', '{"Passenger","Air"}', 'airport'),
('4116', 'EVANSVILLE', 'EVANSVILLE', 'IN', 'US', '{"Passenger","Air"}', 'airport'),
('4117', 'HURON', 'HURON', 'OH', 'US', '{"Passenger","Vessel"}', 'seaport'),
('4121', 'MIDDLEBURG HTS', 'MIDDLEBURG HTS', 'OH', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4122', 'ASHTABULA', 'ASHTABULA', 'OH', 'US', '{"Passenger","Vessel"}', 'seaport'),
('4183', 'FORT WAYNE', 'FORT WAYNE', 'IN', 'US', '{"Passenger","Air"}', 'airport'),
('4184', 'LEXINGTON', 'LEXINGTON', 'KY', 'US', '{"Passenger","Air"}', 'airport'),
('4196', 'LOUISVILLE', 'LOUISVILLE', 'KY', 'US', '{"Passenger","Air"}', 'airport'),
('4197', 'CINCINNATI', 'CINCINNATI', 'OH', 'US', '{"Passenger","Air"}', 'airport'),
('4198', 'INDIANAPOLIS', 'INDIANAPOLIS', 'IN', 'US', '{"Passenger","Air"}', 'airport'),
('4501', 'KANSAS CITY', 'KANSAS CITY', 'MO', 'US', '{"Passenger","Air"}', 'airport'),
('4502', 'ST LOUIS', 'ST LOUIS', 'MO', 'US', '{"Passenger","Air"}', 'airport'),
('4503', 'ST LOUIS', 'ST LOUIS', 'MO', 'US', '{"Passenger","Air"}', 'airport'),
('4504', 'WICHITA', 'WICHITA', 'KS', 'US', '{"Passenger","Air"}', 'airport'),
('4505', 'SPRINGFIELD', 'SPRINGFIELD', 'MO', 'US', '{"Passenger","Air"}', 'airport'),
('4581', 'MASCOUTAH', 'MASCOUTAH', 'IL', 'US', '{"Passenger","Air"}', 'airport'),
('4601', 'NEWARK', 'NEWARK', 'NJ', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4602', 'PERTH AMBOY', 'PERTH AMBOY', 'NJ', 'US', '{"Passenger","Vessel"}', 'seaport'),
('4670', 'NEWARK', 'NEWARK', 'NJ', 'US', '{"Passenger","Air"}', 'airport'),
('4671', 'NEWARK', 'NEWARK', 'NJ', 'US', '{"Passenger","Air"}', 'airport'),
('4681', 'MORRISTOWN', 'MORRISTOWN', 'NJ', 'US', '{"Passenger","Air"}', 'airport'),
('4701', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4771', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4772', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4773', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4774', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4778', 'JAMAICA', 'JAMAICA', 'NY', 'US', '{"Passenger","Air"}', 'airport'),
('4901', 'AGUADILLA', 'AGUADILLA', 'PR', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4904', 'FAJARDO', 'FAJARDO', 'PR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('4907', 'MAYAGUEZ', 'MAYAGUEZ', 'PR', 'US', '{"Passenger","Vessel"}', 'seaport'),
('4908', 'PONCE', 'PONCE', 'PR', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4909', 'OLD SAN JUAN', 'OLD SAN JUAN', 'PR', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('4913', 'OLD SAN JUAN', 'OLD SAN JUAN', 'PR', 'US', '{"Passenger","Air"}', 'airport'),
('5101', 'ST THOMAS', 'ST THOMAS', 'VI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5102', 'ST JOHN', 'ST JOHN', 'VI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5104', 'ST CROIX', 'ST CROIX', 'VI', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5105', 'ST CROIX', 'ST CROIX', 'VI', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5201', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5202', 'KEY WEST', 'KEY WEST', 'FL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5203', 'FT LAUDERDALE', 'FT LAUDERDALE', 'FL', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5204', 'RIVIERA BEACH', 'RIVIERA BEACH', 'FL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5205', 'FORT PIERCE', 'FORT PIERCE', 'FL', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5206', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5210', 'FT LAUDERDALE', 'FT LAUDERDALE', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5295', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5296', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5297', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5298', 'MIAMI', 'MIAMI', 'FL', 'US', '{"Passenger","Air"}', 'airport'),
('5301', 'HOUSTON', 'HOUSTON', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5306', 'HOUSTON', 'HOUSTON', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5309', 'HOUSTON', 'HOUSTON', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5310', 'GALVESTON', 'GALVESTON', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5311', 'FREEPORT', 'FREEPORT', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5312', 'CORPUS CHRISTI', 'CORPUS CHRISTI', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5313', 'CORPUS CHRISTI', 'CORPUS CHRISTI', 'TX', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5381', 'SUGAR LAND', 'SUGAR LAND', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5401', 'STERLING', 'STERLING', 'VA', 'US', '{"Passenger","Vessel","Air"}', 'seaport'),
('5402', 'ANDREWS AFB', 'ANDREWS AFB', 'MD', 'US', '{"Passenger","Vessel"}', 'seaport'),
('5501', 'DFW INTL APRT', 'DFW INTL APRT', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5502', 'AMARILLO', 'AMARILLO', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5503', 'LUBBOCK', 'LUBBOCK', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5504', 'OKLAHOMA CITY', 'OKLAHOMA CITY', 'OK', 'US', '{"Passenger","Air"}', 'airport'),
('5505', 'TULSA', 'TULSA', 'OK', 'US', '{"Passenger","Air"}', 'airport'),
('5506', 'AUSTIN', 'AUSTIN', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5507', 'SAN ANTONIO', 'SAN ANTONIO', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5582', 'MIDLAND', 'MIDLAND', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5583', 'FORT WORTH', 'FORT WORTH', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5584', 'ADDISON', 'ADDISON', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('5588', 'DALLAS', 'DALLAS', 'TX', 'US', '{"Passenger","Air"}', 'airport'),
('8000', 'WASHINGTON', 'WASHINGTON', 'DC', 'US', '{"Mail"}', 'terminal');


-- 1. Update existing ports by location_code
UPDATE public.ports_locations pl
SET 
    location_name = t.location_name,
    city = t.city,
    state_province = t.state_province,
    country_code = t.country_code,
    country = CASE WHEN t.country_code = 'US' THEN 'United States' ELSE pl.country END,
    port_type = t.port_type,
    location_type = t.location_type,
    schedule_d_code = t.location_code, -- Sync Schedule D code with Location Code for these US ports
    updated_at = NOW()
FROM temp_us_ports t
WHERE pl.location_code = t.location_code;

-- 2. Insert NEW ports
INSERT INTO public.ports_locations (
    location_code,
    location_name,
    city,
    state_province,
    country_code,
    country,
    port_type,
    location_type,
    schedule_d_code,
    is_active,
    customs_available,
    created_at,
    updated_at
)
SELECT 
    t.location_code,
    t.location_name,
    t.city,
    t.state_province,
    t.country_code,
    CASE WHEN t.country_code = 'US' THEN 'United States' ELSE NULL END,
    t.port_type,
    t.location_type,
    t.location_code,
    TRUE, -- Assume active if in the list
    TRUE, -- Assume customs available for official ports
    NOW(),
    NOW()
FROM temp_us_ports t
WHERE NOT EXISTS (
    SELECT 1 FROM public.ports_locations pl 
    WHERE pl.location_code = t.location_code
);

-- 3. Log the operation
INSERT INTO public.audit_logs (action, resource_type, details)
VALUES (
    'IMPORT_US_PORTS', 
    'ports_locations', 
    jsonb_build_object(
        'description', 'Import from AESTIR US_Port_Codes',
        'record_count', 439,
        'source', 'AESTIR_Export_Reference_Data.xlsx'
    )
);

DROP TABLE temp_us_ports;

COMMIT;
