
-- Sync Domain: Trading & Procurement
-- Generated by scripts/sync_domains.js

BEGIN;

INSERT INTO platform_domains (key, code, name, description, owner, status, repository_url, swagger_endpoint)
VALUES (
    'trading',
    'trading',
    'Trading & Procurement',
    'Sourcing, inspection, and trade finance services.',
    'Trading Squad',
    'beta',
    'https://github.com/trae/logic-nexus-ai',
    '/api/v1/trading/openapi.json'
)
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    owner = EXCLUDED.owner,
    status = EXCLUDED.status,
    repository_url = EXCLUDED.repository_url,
    swagger_endpoint = EXCLUDED.swagger_endpoint;

COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'trading';
COMMIT;
*/
