
-- Sync Domain: E-Commerce
-- Generated by scripts/sync_domains.js

BEGIN;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.platform_domains WHERE name = 'E-Commerce') THEN
    UPDATE public.platform_domains
      SET code = 'ecommerce',
          description = 'E-Commerce and Retail'
      WHERE name = 'E-Commerce';
  ELSE
    INSERT INTO public.platform_domains (code, name, description)
    VALUES ('ecommerce', 'E-Commerce', 'E-Commerce and Retail')
    ON CONFLICT (code) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description;
  END IF;
END $$;
COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'ECOMMERCE';
COMMIT;
*/
