-- AES-AESTIR Full Appendix D Seeding (Excel Source)
-- Generated from official CBP Export Reference Data Excel
-- Seeded Count: 440

BEGIN;

-- Ensure port_type column exists
ALTER TABLE public.ports_locations 
ADD COLUMN IF NOT EXISTS port_type text[];

-- Create a temp table for the new data
CREATE TEMP TABLE temp_aes_ports_full (
    code text,
    name text,
    modes text[]
);

INSERT INTO temp_aes_ports_full (code, name, modes) VALUES
('0101', 'PORTLAND, ME', '{"Vessel","Air","Passenger"}'),
('0102', 'BANGOR, ME', '{"Vessel","Air","Passenger"}'),
('0103', 'EASTPORT, ME', '{"Vessel","Passenger"}'),
('0104', 'JACKMAN, ME', '{"Rail","Passenger","Road"}'),
('0105', 'VANCEBORO, ME', '{"Rail","Passenger","Road"}'),
('0106', 'HOULTON, ME', '{"Rail","Passenger","Road"}'),
('0107', 'FORT FAIRFIELD, ME', '{"Rail","Air","Road","Passenger"}'),
('0108', 'VAN BUREN, ME', '{"Rail","Passenger","Road"}'),
('0109', 'MADAWASKA, ME', '{"Rail","Passenger","Road"}'),
('0110', 'FORT KENT, ME', '{"Vessel","Rail","Passenger","Road"}'),
('0111', 'BATH, ME', '{"Vessel","Passenger"}'),
('0112', 'BAR HARBOR, ME', '{"Vessel","Rail","Passenger","Road"}'),
('0115', 'CALAIS, ME', '{"Vessel","Rail","Passenger","Fixed"}'),
('0118', 'LIMESTONE, ME', '{"Vessel","Rail","Passenger","Road"}'),
('0121', 'ROCKLAND, ME', '{"Vessel","Passenger"}'),
('0122', 'JONESPORT, ME', '{"Vessel","Rail","Passenger","Road"}'),
('0127', 'BRIDGEWATER, ME', '{"Vessel","Passenger","Air","Road","Rail"}'),
('0131', 'PORTSMOUTH, NH', '{"Vessel","Air","Passenger"}'),
('0132', 'BELFAST, ME', '{"Vessel","Passenger"}'),
('0152', 'SEARSPORT, ME', '{"Vessel","Air","Passenger"}'),
('0182', 'MANCHESTER AIRPORT', '{"Air","Road","Passenger"}'),
('0201', 'ST. ALBANS, VT', '{"Rail","Passenger","Road"}'),
('0203', 'RICHFORD, VT', '{"Rail","Passenger","Road"}'),
('0206', 'BEECHER FALLS, VT', '{"Rail","Air","Road","Passenger"}'),
('0207', 'BURLINGTON, VT', '{"Rail","Air","Road","Passenger"}'),
('0209', 'DERBY LINE, VT', '{"Rail","Passenger","Road"}'),
('0211', 'NORTON, VT', '{"Rail","Passenger","Road"}'),
('0212', 'HIGHGATE SPRINGS/ALBURG', '{"Rail","Passenger","Road"}'),
('0401', 'BOSTON, MA', '{"Vessel","Air","Passenger"}'),
('0402', 'SPRINGFIELD, MA', '{"Air","Passenger"}'),
('0403', 'WORCESTER, MA', '{"Vessel","Air","Passenger"}'),
('0404', 'GLOUCESTER, MA', '{"Vessel","Passenger"}'),
('0405', 'NEW BEDFORD, MA', '{"Vessel","Passenger"}'),
('0406', 'PLYMOUTH, MA', '{"Vessel","Passenger"}'),
('0407', 'FALL RIVER, MA', '{"Vessel","Passenger"}'),
('0408', 'BEVERLY, MA', '{"Vessel","Passenger"}'),
('0410', 'BRIDGEPORT, CT', '{"Vessel","Air","Passenger"}'),
('0411', 'HARTFORD, CT', '{"Vessel","Air","Passenger"}'),
('0412', 'NEW HAVEN, CT', '{"Vessel","Passenger"}'),
('0413', 'NEW LONDON, CT', '{"Vessel","Air","Passenger"}'),
('0416', 'LAWRENCE, MA', '{"Air","Passenger"}'),
('0417', 'LOGAN AIRPORT, MA', '{"Air","Passenger"}'),
('0481', 'HANSCOM USER FEE AIRPORT', '{"Air","Passenger"}'),
('0501', 'NEWPORT, RI', '{"Vessel","Passenger"}'),
('0502', 'PROVIDENCE, RI', '{"Vessel","Passenger"}'),
('0503', 'MELLVILLE, RI', '{"Vessel","Passenger"}'),
('0701', 'OGDENSBURG, NY', '{"Vessel","Passenger","Road"}'),
('0704', 'MASSENA, NY', '{"Vessel","Passenger","Road"}'),
('0706', 'CAPE VINCENT, NY', '{"Vessel","Rail","Passenger","Road"}'),
('0708', 'ALEXANDRIA BAY, NY', '{"Vessel","Passenger","Road"}'),
('0712', 'CHAMPLAIN-ROUSES POINT', '{"Vessel","Rail","Passenger","Road"}'),
('0714', 'CLAYTON, NY', '{"Vessel","Passenger"}'),
('0715', 'TROUT RIVER, NY', '{"Rail","Passenger","Road"}'),
('0901', 'BUFFALO-NIAGARA FALLS', '{"Vessel","Passenger","Air","Rail","Fixed"}'),
('0903', 'ROCHESTER, NY', '{"Vessel","Air","Passenger"}'),
('0904', 'OSWEGO, NY', '{"Vessel","Passenger"}'),
('0905', 'SODUS POINT, NY', '{"Vessel","Passenger"}'),
('0906', 'SYRACUSE, NY', '{"Vessel","Air","Passenger"}'),
('0981', 'BINGHAMTON REGIONAL (UFA', '{"Air","Passenger"}'),
('1001', 'NEW YORK, NY', '{"Vessel","Air","Passenger"}'),
('1002', 'ALBANY, NY', '{"Vessel","Air","Passenger"}'),
('1101', 'PHILADELPHIA, PA', '{"Vessel","Air","Passenger"}'),
('1102', 'CHESTER, PA', '{"Vessel","Passenger"}'),
('1103', 'WILMINGTON, DE', '{"Vessel","Air","Passenger"}'),
('1104', 'PITTSBURGH, PA', '{"Air","Passenger"}'),
('1105', 'PAULSBORO, NJ', '{"Vessel","Passenger"}'),
('1106', 'WILKES-BARRE/SCRANTON, P', '{"Air","Passenger"}'),
('1107', 'CAMDEN, NJ', '{"Vessel","Passenger"}'),
('1108', 'PHILA. INTERNATIONAL AIR', '{"Air","Passenger"}'),
('1109', 'HARRISBURG, PA', '{"Air","Passenger"}'),
('1113', 'GLOUCESTER CITY', '{"Vessel","Air","Passenger"}'),
('1119', 'ALLENTOWN, PA', '{"Air","Passenger"}'),
('1182', 'ATLANTIC CITY AIRPORT', '{"Air","Passenger"}'),
('1183', 'TRENTON/MERCER CTY ARPT', '{"Air","Passenger"}'),
('1195', 'UPS HUB, PHILADELPHIA, P', '{"Air","Passenger"}'),
('1301', 'ANNAPOLIS, MD', '{"Vessel","Passenger"}'),
('1302', 'CAMBRIDGE, MD', '{"Vessel","Passenger"}'),
('1303', 'BALTIMORE, MD', '{"Vessel","Passenger"}'),
('1304', 'CRISFIELD, MD', '{"Vessel","Passenger"}'),
('1305', 'BWI AIRPORT', '{"Air","Passenger"}'),
('1401', 'NORFOLK-NEWPORT NEWS, VA', '{"Vessel","Air","Passenger"}'),
('1404', 'RICHMOND-PETERSBURG, VA', '{"Vessel","Air","Passenger"}'),
('1409', 'CHARLESTON, WV', '{"Air","Passenger"}'),
('1410', 'FRONT ROYAL, VA', '{"Air","Passenger"}'),
('1412', 'NO STAFF-CSMS 13-000148', '{"Air","Passenger"}'),
('1501', 'WILMINGTON, NC', '{"Vessel","Air","Passenger"}'),
('1502', 'WINSTON-SALEM, NC', '{"Air","Passenger"}'),
('1503', 'DURHAM, NC', '{"Air","Passenger"}'),
('1511', 'BEAUFORT-MOREHEAD CTY,NC', '{"Vessel","Passenger"}'),
('1512', 'CHARLOTTE, NC', '{"Air","Passenger"}'),
('1601', 'CHARLESTON, SC', '{"Vessel","Air","Passenger"}'),
('1602', 'GEORGETOWN, SC', '{"Vessel","Passenger"}'),
('1603', 'GREENVILLE-SPARTANBRG SC', '{"Air","Passenger"}'),
('1604', 'COLUMBIA, SC', '{"Air","Passenger"}'),
('1681', 'MYRTLE BEACH INTL AIRPOR', '{"Air","Passenger"}'),
('1701', 'BRUNSWICK, GA', '{"Vessel","Passenger"}'),
('1703', 'SAVANNAH, GA', '{"Vessel","Air","Passenger"}'),
('1704', 'ATLANTA, GA', '{"Air","Passenger"}'),
('1801', 'TAMPA, FL', '{"Vessel","Air","Passenger"}'),
('1803', 'JACKSONVILLE, FL', '{"Vessel","Air","Passenger"}'),
('1805', 'FERNANDINA BEACH, FL', '{"Vessel","Passenger"}'),
('1807', 'BOCA GRANDE, FL', '{"Vessel","Passenger"}'),
('1808', 'ORLANDO, FL', '{"Air","Passenger"}'),
('1809', 'ORLANDO SANFORD AIRPORT', '{"Air","Passenger"}'),
('1814', 'ST. PETERSBURG, FL', '{"Vessel","Passenger"}'),
('1816', 'PORT CANAVERAL, FL', '{"Vessel","Passenger"}'),
('1818', 'PANAMA CITY, FL', '{"Vessel","Passenger"}'),
('1819', 'PENSACOLA, FL', '{"Vessel","Passenger"}'),
('1821', 'PORT MANATEE, FL', '{"Vessel","Passenger"}'),
('1822', 'FORT MYERS', '{"Air","Passenger"}'),
('1880', 'NAPLES MUNICIPAL AIRPORT', '{"Air","Passenger"}'),
('1883', 'SARASOTA BRADENTON AIRPT', '{"Air","Passenger"}'),
('1884', 'DAYTONA BEACH INTL AIRPO', '{"Air","Passenger"}'),
('1885', 'MELBOURNE AIRPORT', '{"Air","Passenger"}'),
('1887', 'LEESBURG REGIONAL AIRPT', '{"Air","Passenger"}'),
('1888', 'ORLANDO EXECUTIVE AIRPT', '{"Air","Passenger"}'),
('1889', 'ST AUGUSTINE ARPT UFA', '{"Air","Passenger"}'),
('1901', 'MOBILE, AL', '{"Vessel","Air","Passenger"}'),
('1902', 'GULFPORT, MS', '{"Vessel","Passenger"}'),
('1903', 'PASCAGOULA, MS', '{"Vessel","Passenger"}'),
('1904', 'BIRMINGHAM, AL', '{"Air","Passenger"}'),
('1910', 'HUNTSVILLE, AL', '{"Vessel","Air","Passenger"}'),
('2001', 'MORGAN CITY, LA', '{"Vessel","Air","Passenger"}'),
('2002', 'NEW ORLEANS, LA', '{"Vessel","Air","Passenger"}'),
('2003', 'LITTLE ROCK, AR', '{"Air","Passenger"}'),
('2004', 'BATON ROUGE, LA', '{"Vessel","Passenger"}'),
('2006', 'MEMPHIS, TN', '{"Air","Passenger"}'),
('2007', 'NASHVILLE, TN', '{"Air","Passenger"}'),
('2008', 'CHATTANOOGA, TN', '{"Air","Passenger"}'),
('2010', 'GRAMERCY, LA', '{"Vessel","Passenger"}'),
('2011', 'GREENVILLE, MS', '{"Vessel","Passenger"}'),
('2015', 'VICKSBURG, MS', '{"Air","Passenger"}'),
('2016', 'KNOXVILLE, TN', '{"Air","Passenger"}'),
('2017', 'LAKE CHARLES, LA', '{"Vessel","Air","Passenger"}'),
('2018', 'SHREVEPORT/BOSSIER CITY', '{"Air","Passenger"}'),
('2027', 'PORT OF TRI-CITIES', '{"Air","Passenger"}'),
('2095', 'FEDEX COURIER, MEMPHIS T', '{"Air","Passenger"}'),
('2101', 'PORT ARTHUR, TX', '{"Vessel","Air","Passenger"}'),
('2102', 'SABINE, TX', '{"Vessel","Air","Passenger"}'),
('2103', 'ORANGE, TX', '{"Vessel","Air","Passenger"}'),
('2104', 'BEAUMONT, TX', '{"Vessel","Air","Passenger"}'),
('2301', 'BROWNSVILLE, TX', '{"Vessel","Passenger","Air","Road","Rail","Fixed"}'),
('2302', 'DEL RIO, TX', '{"Passenger","Road"}'),
('2303', 'EAGLE PASS, TX', '{"Rail","Air","Road","Passenger"}'),
('2304', 'LAREDO, TX', '{"Passenger","Air","Road","Rail","Fixed"}'),
('2305', 'HIDALGO, TX', '{"Air","Fixed","Road","Passenger"}'),
('2307', 'RIO GRANDE CITY, TX', '{"Passenger","Road"}'),
('2309', 'PROGRESO, TX', '{"Passenger","Road"}'),
('2310', 'ROMA, TX', '{"Passenger","Road"}'),
('2383', 'VALLEY INTL AIRPORT  UFA', '{"Air","Passenger"}'),
('2402', 'EL PASO, TX', '{"Passenger","Air","Road","Rail","Fixed"}'),
('2403', 'PRESIDIO, TX', '{"Rail","Passenger","Road"}'),
('2404', 'TORNILLO, TX', '{"Rail","Passenger","Road"}'),
('2406', 'COLUMBUS, NM', '{"Rail","Passenger","Road"}'),
('2407', 'ALBUQUERQUE, NM', '{"Air","Passenger"}'),
('2408', 'SANTA TERESA NM', '{"Passenger","Road"}'),
('2481', 'SANTA TERESA AIRPORT', '{"Air","Passenger"}'),
('2501', 'SAN DIEGO, CA', '{"Vessel","Air","Passenger"}'),
('2502', 'ANDRADE, CA', '{"Passenger","Road"}'),
('2503', 'CALEXICO, CA', '{"Rail","Air","Road","Passenger"}'),
('2504', 'SAN YSIDRO', '{"Rail","Air","Fixed","Passenger"}'),
('2505', 'TECATE, CA', '{"Rail","Passenger","Road"}'),
('2506', 'OTAY MESA', '{"Passenger","Air","Road","Rail","Fixed"}'),
('2507', 'CALEXICO-EAST', '{"Rail","Passenger","Road"}'),
('2601', 'DOUGLAS, AZ', '{"Passenger","Fixed","Road"}'),
('2602', 'LUKEVILLE, AZ', '{"Passenger","Road"}'),
('2603', 'NACO, AZ', '{"Passenger","Road"}'),
('2604', 'NOGALES, AZ', '{"Rail","Air","Road","Passenger"}'),
('2605', 'PHOENIX, AZ', '{"Air","Passenger"}'),
('2606', 'SASABE, AZ', '{"Passenger","Road"}'),
('2608', 'SAN LUIS, AZ', '{"Passenger","Road"}'),
('2609', 'TUCSON, AZ', '{"Air","Passenger"}'),
('2704', 'LOS ANGELES, CA', '{"Vessel","Passenger"}'),
('2709', 'LONG BEACH, CA', '{"Vessel","Passenger"}'),
('2711', 'EL SEGUNDO, CA', '{"Vessel","Passenger"}'),
('2712', 'VENTURA, CA', '{"Vessel","Passenger"}'),
('2713', 'PORT HUENEME, CA', '{"Vessel","Passenger"}'),
('2715', 'CAPITAN, CA', '{"Vessel","Passenger"}'),
('2719', 'MORRO BAY, CA', '{"Vessel","Passenger"}'),
('2720', 'LOS ANGELES INT AIRPORT', '{"Air","Passenger"}'),
('2721', 'ONTARIO INTL AIRPORT', '{"Air","Passenger"}'),
('2722', 'LAS VEGAS, NV', '{"Air","Passenger"}'),
('2770', 'INACTIVE DO NOT USE', '{"Air","Passenger"}'),
('2775', 'TNT EXPRESS WORLDWIDE', '{"Air","Passenger"}'),
('2776', 'INT''L BONDED COURIERS', '{"Air","Passenger"}'),
('2781', 'PALM SPRINGS USER FEE', '{"Air","Passenger"}'),
('2782', 'SAN BERNARDINO U.F. AIRP', '{"Air","Passenger"}'),
('2786', 'MEADOWS FIELD AIRPORT', '{"Air","Passenger"}'),
('2791', 'DHL- HUB', '{"Air","Passenger"}'),
('2795', 'UPS-ONTARIO', '{"Air","Passenger"}'),
('2801', 'SAN FRANCISCO INTL AIRPO', '{"Air","Passenger"}'),
('2802', 'EUREKA, CA', '{"Vessel","Passenger"}'),
('2803', 'FRESNO, CA', '{"Air","Passenger"}'),
('2805', 'MONTEREY, CA', '{"Vessel","Passenger"}'),
('2809', 'SAN FRANCISCO, CA', '{"Vessel","Passenger"}'),
('2810', 'STOCKTON, CA', '{"Vessel","Passenger"}'),
('2811', 'OAKLAND, CA', '{"Vessel","Air","Passenger"}'),
('2812', 'RICHMOND,CA', '{"Vessel","Passenger"}'),
('2813', 'ALAMEDA,CA', '{"Vessel","Passenger"}'),
('2815', 'CROCKETT,CA', '{"Vessel","Passenger"}'),
('2820', 'MARTINEZ,CA', '{"Vessel","Passenger"}'),
('2821', 'REDWOOD CITY,CA', '{"Vessel","Passenger"}'),
('2827', 'SELBY,CA', '{"Vessel","Passenger"}'),
('2828', 'SAN JUAQUIN RIVER,CA', '{"Vessel","Passenger"}'),
('2829', 'SAN PABLO BAY,CA', '{"Vessel","Passenger"}'),
('2830', 'CARQUINEZ STRAIT,CA', '{"Vessel","Passenger"}'),
('2833', 'RENO, NV', '{"Air","Passenger"}'),
('2834', 'SAN JOSE INTL AIRPORT', '{"Air","Passenger"}'),
('2835', 'SACRAMENTO INT AIRPORT', '{"Vessel","Air","Road","Passenger"}'),
('2870', 'DHL WORLDWIDE EXPRESS', '{"Air","Passenger"}'),
('2871', 'AIRCARGO HANDLING SERVIC', '{"Air","Passenger"}'),
('2872', 'TNT SKYPAK', '{"Air","Passenger"}'),
('2895', 'FEDEX COURIER FACILITY', '{"Air","Passenger"}'),
('2901', 'ASTORIA, OR', '{"Vessel","Passenger"}'),
('2902', 'NEWPORT, OR', '{"Vessel","Passenger"}'),
('2903', 'COOS BAY, OR', '{"Vessel","Passenger"}'),
('2904', 'PORTLAND, OR', '{"Vessel","Passenger"}'),
('2905', 'LONGVIEW, WA', '{"Vessel","Passenger"}'),
('2907', 'BOISE, ID', '{"Air","Passenger"}'),
('2908', 'VANCOUVER, WA', '{"Vessel","Passenger"}'),
('2909', 'KALAMA, WA', '{"Vessel","Passenger"}'),
('2910', 'PORTLAND INTL AIRPORT, O', '{"Air","Passenger"}'),
('3001', 'SEATTLE, WA', '{"Vessel","Air","Passenger"}'),
('3002', 'TACOMA, WA', '{"Vessel","Air","Passenger"}'),
('3003', 'ABERDEEN, WA', '{"Vessel","Air","Passenger"}'),
('3004', 'BLAINE, WA', '{"Vessel","Rail","Passenger","Road"}'),
('3005', 'BELLINGHAM, WA', '{"Vessel","Air","Passenger"}'),
('3006', 'EVERETT, WA', '{"Vessel","Air","Passenger"}'),
('3007', 'PORT ANGELES, WA', '{"Vessel","Air","Passenger"}'),
('3008', 'PORT TOWNSEND, WA', '{"Vessel","Air","Passenger"}'),
('3009', 'SUMAS, WA', '{"Rail","Passenger","Fixed"}'),
('3010', 'ANACORTES, WA', '{"Vessel","Passenger"}'),
('3011', 'NIGHTHAWK, WA', '{"Passenger","Road"}'),
('3012', 'DANVILLE, WA', '{"Passenger","Road"}'),
('3013', 'FERRY, WA', '{"Passenger","Road"}'),
('3014', 'FRIDAY HARBOR, WA', '{"Vessel","Passenger"}'),
('3015', 'BOUNDARY, WA', '{"Rail","Passenger","Road"}'),
('3016', 'LAURIER, WA', '{"Rail","Air","Road","Passenger"}'),
('3017', 'POINT ROBERTS, WA', '{"Vessel","Rail","Passenger","Road"}'),
('3018', 'KENMORE AIR HARBOR, WA', '{"Air","Passenger"}'),
('3019', 'OROVILLE, WA', '{"Air","Road","Passenger"}'),
('3020', 'FRONTIER, WA', '{"Passenger","Road"}'),
('3022', 'SPOKANE, WA', '{"Air","Passenger"}'),
('3023', 'LYNDEN, WA', '{"Rail","Passenger","Road"}'),
('3025', 'METALINE FALLS', '{"Passenger","Road"}'),
('3026', 'OLYMPIA, WA', '{"Vessel","Passenger"}'),
('3029', 'SEATTLE-TACOMA INTL AIRP', '{"Air","Passenger"}'),
('3071', 'U.P.S.', '{"Air","Passenger"}'),
('3072', 'AVION BROKERS @ SEATAC', '{"Air","Passenger"}'),
('3073', 'DHL WORLDWIDE EXP', '{"Air","Passenger"}'),
('3074', 'AIRBORNE EXPRESS @SEATAC', '{"Air","Passenger"}'),
('3082', 'GRANT COUNTY AIRPORT', '{"Air","Passenger"}'),
('3095', 'UPS COURIER HUB', '{"Air","Passenger"}'),
('3101', 'JUNEAU, AK', '{"Vessel","Passenger"}'),
('3102', 'KETCHIKAN, AK', '{"Vessel","Passenger"}'),
('3103', 'SKAGWAY, AK', '{"Vessel","Passenger","Air","Road","Rail"}'),
('3104', 'ALCAN, AK', '{"Air","Road","Passenger"}'),
('3105', 'WRANGELL, AK', '{"Vessel","Air","Passenger"}'),
('3106', 'DALTON CACHE, AK', '{"Vessel","Air","Road","Passenger"}'),
('3111', 'FAIRBANKS, AK', '{"Vessel","Air","Passenger"}'),
('3115', 'SITKA, AK', '{"Vessel","Air","Passenger"}'),
('3126', 'ANCHORAGE, AK', '{"Vessel","Air","Passenger"}'),
('3195', 'FEDERAL EXPRESS COURIER', '{"Air","Passenger"}'),
('3196', 'UPS COURIER HUB, AK', '{"Air","Passenger"}'),
('3201', 'HONOLULU, HI', '{"Vessel","Passenger"}'),
('3202', 'HILO, HI', '{"Vessel","Air","Passenger"}'),
('3203', 'KAHULUI, HI', '{"Vessel","Air","Passenger"}'),
('3204', 'NAWILIWILI-PORT ALLEN, H', '{"Vessel","Passenger"}'),
('3205', 'HONOLULU AIRPORT', '{"Air","Passenger"}'),
('3206', 'KONA HI', '{"Vessel","Air","Passenger"}'),
('3295', 'HONOLULU INTL AP INACTIV', '{"Air","Passenger"}'),
('3301', 'RAYMOND, MT', '{"Passenger","Road"}'),
('3302', 'EASTPORT, ID', '{"Rail","Passenger","Road"}'),
('3303', 'SALT LAKE CITY, UT', '{"Air","Passenger"}'),
('3304', 'GREAT FALLS, MT', '{"Air","Passenger"}'),
('3305', 'BUTTE, MT', '{"Air","Passenger"}'),
('3306', 'TURNER, MT', '{"Passenger","Road"}'),
('3307', 'DENVER, CO', '{"Air","Passenger"}'),
('3308', 'PORTHILL, ID', '{"Passenger","Road"}'),
('3309', 'SCOBEY, MT', '{"Passenger","Road"}'),
('3310', 'SWEETGRASS, MT', '{"Rail","Passenger","Road"}'),
('3316', 'PIEGAN, MT', '{"Rail","Passenger","Road"}'),
('3317', 'OPHEIM, MT', '{"Passenger","Road"}'),
('3318', 'ROOSVILLE, MT', '{"Passenger","Road"}'),
('3319', 'MORGAN, MT', '{"Passenger"}'),
('3321', 'WHITLASH, MT', '{"Air","Passenger"}'),
('3322', 'DEL BONITA, MT', '{"Air","Passenger"}'),
('3323', 'WILDHORSE, MT', '{"Passenger","Road"}'),
('3324', 'KALISPELL, MT', '{"Air","Passenger"}'),
('3325', 'WILLOW CREEK, MT', '{"Passenger","Road"}'),
('3384', 'CENTENNIAL AIRPORT', '{"Air","Passenger"}'),
('3385', 'EAGLE COUNTY REGNL AIRPT', '{"Air","Passenger"}'),
('3386', 'BOZEMAN YELLOWSTONE UFA', '{"Air","Passenger"}'),
('3401', 'PEMBINA, ND', '{"Passenger","Air","Road","Rail","Fixed"}'),
('3403', 'PORTAL, ND', '{"Rail","Passenger","Road"}'),
('3404', 'NECHE, ND', '{"Rail","Passenger","Road"}'),
('3405', 'ST JOHN, ND', '{"Rail","Passenger","Road"}'),
('3406', 'NORTHGATE, ND', '{"Rail","Passenger","Road"}'),
('3407', 'WALHALLA, ND', '{"Rail","Passenger","Road"}'),
('3408', 'HANNAH, ND', '{"Rail","Passenger","Road"}'),
('3409', 'SARLES, ND', '{"Rail","Passenger","Road"}'),
('3410', 'AMBROSE, ND', '{"Rail","Passenger","Road"}'),
('3411', 'FARGO INT''L AIRPORT, ND', '{"Air","Passenger"}'),
('3413', 'ANTLER, ND', '{"Rail","Passenger","Road"}'),
('3414', 'SHERWOOD, ND', '{"Rail","Passenger","Road"}'),
('3415', 'HANSBORO, ND', '{"Rail","Passenger","Road"}'),
('3416', 'MAIDA, ND', '{"Rail","Passenger","Road"}'),
('3417', 'FORTUNA, ND', '{"Rail","Passenger","Road"}'),
('3419', 'WESTHOPE, ND', '{"Rail","Passenger","Road"}'),
('3420', 'NOONAN, ND', '{"Rail","Passenger","Road"}'),
('3421', 'CARBURY, ND', '{"Rail","Passenger","Road"}'),
('3422', 'DUNSEITH, ND', '{"Rail","Passenger","Road"}'),
('3423', 'WARROAD, MN', '{"Rail","Passenger","Road"}'),
('3424', 'BAUDETTE, MN', '{"Passenger","Road"}'),
('3425', 'PINECREEK, MN', '{"Passenger","Road"}'),
('3426', 'ROSEAU, MN', '{"Passenger","Road"}'),
('3427', 'GRAND FORKS AIRPORT', '{"Air","Passenger"}'),
('3430', 'LANCASTER, MN', '{"Passenger","Fixed","Road"}'),
('3433', 'WILLISTON AIRPORT', '{"Air","Passenger"}'),
('3434', 'MINOT AIRPORT', '{"Air","Passenger"}'),
('3501', 'MINNEAPOLIS-ST. PAUL, MN', '{"Air","Passenger"}'),
('3502', 'SIOUX FALLS, SD', '{"Air","Passenger"}'),
('3510', 'DULUTH, MN', '{"Vessel","Air","Passenger"}'),
('3511', 'ASHLAND, WI', '{"Vessel","Passenger"}'),
('3512', 'OMAHA, NE', '{"Air","Passenger"}'),
('3513', 'DES MOINES, IA', '{"Air","Passenger"}'),
('3581', 'ROCHESTER, MN', '{"Air","Passenger"}'),
('3604', 'INTERNATIONAL FALLS, MN', '{"Vessel","Passenger","Air","Road","Rail"}'),
('3613', 'GRAND PORTAGE, MN', '{"Vessel","Passenger","Road"}'),
('3701', 'MILWAUKEE, WI', '{"Vessel","Air","Passenger"}'),
('3702', 'MARINETTE, WI', '{"Vessel","Passenger"}'),
('3703', 'GREEN BAY, WI', '{"Vessel","Air","Passenger"}'),
('3706', 'MANITOWOC, WI', '{"Vessel","Passenger"}'),
('3707', 'SHEBOYGAN, WI', '{"Vessel","Passenger"}'),
('3708', 'RACINE, WI', '{"Vessel","Passenger"}'),
('3801', 'DETROIT, MI', '{"Vessel","Passenger","Air","Rail","Fixed"}'),
('3802', 'PORT HURON, MI', '{"Vessel","Passenger","Road","Rail","Fixed"}'),
('3803', 'SAULT STE. MARIE, MI', '{"Vessel","Rail","Passenger","Road"}'),
('3804', 'SAGINAW/BAY CITY, MI', '{"Vessel","Passenger"}'),
('3805', 'BATTLE CREEK, MI', '{"Vessel"}'),
('3806', 'GRAND RAPIDS, MI', '{"Air","Passenger"}'),
('3807', 'DETROIT METROPLTN AIRPRT', '{"Air","Passenger"}'),
('3808', 'ESCANABA, MI', '{"Vessel","Passenger"}'),
('3809', 'MARQUETTE, MI', '{"Vessel","Passenger"}'),
('3814', 'ALGONAC, MI', '{"Vessel","Rail","Passenger","Road"}'),
('3815', 'MUSKEGON, MI', '{"Vessel","Passenger"}'),
('3816', 'GRAND HAVEN, MI', '{"Vessel","Passenger"}'),
('3818', 'ROGERS CITY, MI', '{"Vessel","Passenger"}'),
('3819', 'DETOUR, MI', '{"Vessel","Passenger"}'),
('3842', 'PRESQUE ISLE, MI', '{"Vessel","Passenger"}'),
('3843', 'ALPENA, MI', '{"Vessel","Passenger"}'),
('3881', 'OAKLAND COUNTY INT''L AIR', '{"Air","Passenger"}'),
('3882', 'WILLOW RUN AIRPORT', '{"Air","Passenger"}'),
('3883', 'CAPITAL REGION INTL AIRP', '{"Air","Passenger"}'),
('3901', 'CHICAGO, IL', '{"Vessel","Air","Passenger"}'),
('3902', 'PEORIA, IL', '{"Air","Passenger"}'),
('3905', 'GARY, IN', '{"Vessel","Passenger"}'),
('3908', 'DAVENPORT-ROCK ISLAND', '{"Air","Passenger"}'),
('3909', 'ROCKFORD AIRPORT', '{"Air","Passenger"}'),
('3910', 'MIDWAY INT''L AIRPORT', '{"Air","Passenger"}'),
('3971', 'ECCF TNT CHICAGO', '{"Air","Passenger"}'),
('3983', 'CHICAGO EXECUTIVE AIRPOR', '{"Air"}'),
('3984', 'DUPAGE AIRPORT AUTH', '{"Air","Passenger"}'),
('4101', 'CLEVELAND, OH', '{"Vessel","Air","Passenger"}'),
('4102', 'CINCINNATI, OH', '{"Air","Passenger"}'),
('4103', 'COLUMBUS, OH', '{"Air","Passenger"}'),
('4104', 'DAYTON, OH', '{"Air","Passenger"}'),
('4105', 'TOLEDO, OH', '{"Vessel","Air","Passenger"}'),
('4106', 'ERIE, PA', '{"Vessel","Air","Passenger"}'),
('4110', 'INDIANAPOLIS, IN', '{"Air","Passenger"}'),
('4115', 'LOUISVILLE, KY', '{"Air","Passenger"}'),
('4116', 'OWENSBORO-EVANSVILLE', '{"Air","Passenger"}'),
('4117', 'HURON, OH', '{"Vessel","Passenger"}'),
('4121', 'LORAIN, OH', '{"Vessel","Air","Passenger"}'),
('4122', 'ASHTABULA/CONNEAUT', '{"Vessel","Passenger"}'),
('4183', 'FORT WAYNE AIRPORT', '{"Air","Passenger"}'),
('4184', 'BLUE GRASS AIRPORT', '{"Air","Passenger"}'),
('4196', 'UPS COURIER LOUISVILLE', '{"Air","Passenger"}'),
('4197', 'DHL COURIER', '{"Air","Passenger"}'),
('4198', 'FEDERAL EXPRESS HUB', '{"Air","Passenger"}'),
('4501', 'KANSAS CITY, MO', '{"Air","Passenger"}'),
('4502', 'ST JOSEPH, MO', '{"Air","Passenger"}'),
('4503', 'ST LOUIS, MO', '{"Air","Passenger"}'),
('4504', 'WICHITA, KS', '{"Air","Passenger"}'),
('4505', 'SPRINGFIELD, MO', '{"Air","Passenger"}'),
('4581', 'MIDAMERICA AIRPORT', '{"Air","Passenger"}'),
('4601', 'NEW YORK/NEWARK AREA', '{"Vessel","Air","Passenger"}'),
('4602', 'PERTH AMBOY, NJ', '{"Vessel","Passenger"}'),
('4670', 'UPS NEWARK, NJ', '{"Air","Passenger"}'),
('4671', 'FEDERAL EXPRESS ECCF', '{"Air","Passenger"}'),
('4681', 'MORRISTOWN AIRPORT, NJ', '{"Air","Passenger"}'),
('4701', 'JOHN F KENNEDY AIRPORT', '{"Air","Passenger"}'),
('4771', 'NYACC (ECCF)', '{"Air","Passenger"}'),
('4772', 'DHL AIRWAYS', '{"Air","Passenger"}'),
('4773', 'MICOM (ECCF)', '{"Air","Passenger"}'),
('4774', 'IBC (ECCF)', '{"Air","Passenger"}'),
('4778', 'TNT SKYPAK (ECCF)', '{"Air","Passenger"}'),
('4901', 'AGUADILLA, PR', '{"Vessel","Air","Passenger"}'),
('4904', 'FAJARDO, PR', '{"Vessel","Passenger"}'),
('4907', 'MAYAGUEZ, PR', '{"Vessel","Passenger"}'),
('4908', 'PONCE, PR', '{"Vessel","Air","Passenger"}'),
('4909', 'SAN JUAN, PR', '{"Vessel","Air","Passenger"}'),
('4913', 'SAN JUAN INTL AIRPORT', '{"Air","Passenger"}'),
('5101', 'CHARLOTTE AMALIE, VI', '{"Vessel","Air","Passenger"}'),
('5102', 'CRUZ BAY, VI', '{"Vessel","Passenger"}'),
('5104', 'CHRISTIANSTED, VI', '{"Vessel","Air","Passenger"}'),
('5105', 'FREDERIKSTED, VI', '{"Vessel","Passenger"}'),
('5201', 'MIAMI, FL', '{"Vessel","Passenger"}'),
('5202', 'KEY WEST, FL', '{"Vessel","Air","Passenger"}'),
('5203', 'PORT EVERGLADES, FL', '{"Vessel","Passenger"}'),
('5204', 'WEST PALM BEACH, FL', '{"Vessel","Air","Passenger"}'),
('5205', 'FORT PIERCE, FL', '{"Vessel","Air","Passenger"}'),
('5206', 'MIAMI INTERNATIONAL AIRP', '{"Air","Passenger"}'),
('5210', 'FT LAUDERDALE INTL AIRPT', '{"Air","Passenger"}'),
('5295', 'UPS MIAMI INTL AIRPORT', '{"Air","Passenger"}'),
('5296', 'DHL WORLDWIDE EX MIAMI', '{"Air","Passenger"}'),
('5297', 'FEDEX COURIER HUB MIAMI', '{"Air","Passenger"}'),
('5298', 'IBC COURIER HUB MIAMI', '{"Air","Passenger"}'),
('5301', 'HOUSTON, TX', '{"Vessel","Passenger"}'),
('5306', 'TEXAS CITY, TX', '{"Vessel","Passenger"}'),
('5309', 'HOUSTON GEO. BUSH INTERC', '{"Air","Passenger"}'),
('5310', 'GALVESTON, TX', '{"Vessel","Passenger"}'),
('5311', 'FREEPORT, TX', '{"Vessel","Passenger"}'),
('5312', 'CORPUS CHRISTI, TX', '{"Vessel","Passenger"}'),
('5313', 'PORT LAVACA, TX', '{"Vessel","Passenger"}'),
('5381', 'SUGAR LAND REGIONAL AIRP', '{"Air","Passenger"}'),
('5401', 'WASHINGTON, DC  (DULLES)', '{"Vessel","Air","Passenger"}'),
('5402', 'ALEXANDRIA, VA', '{"Vessel","Passenger"}'),
('5501', 'DALLAS/FT WORTH TX', '{"Air","Passenger"}'),
('5502', 'AMARILLO, TX', '{"Air","Passenger"}'),
('5503', 'LUBBOCK, TX', '{"Air","Passenger"}'),
('5504', 'OKLAHOMA CITY, OK', '{"Air","Passenger"}'),
('5505', 'TULSA, OK', '{"Air","Passenger"}'),
('5506', 'AUSTIN, TX', '{"Air","Passenger"}'),
('5507', 'SAN ANTONIO, TX', '{"Air","Passenger"}'),
('5582', 'MIDLAND INTERNATIONAL AI', '{"Air","Passenger"}'),
('5583', 'FORT WORTH ALLIANCE AP', '{"Air","Passenger"}'),
('5584', 'ADDISON AIRPORT', '{"Air","Passenger"}'),
('5588', 'DALLAS LOVE FIELD (DAL)', '{"Air","Passenger"}'),
('8000', 'US MAIL EEI PORT CODE', '{"Mail"}');


-- 1. Update existing ports with Schedule D code and name normalization
UPDATE public.ports_locations pl
SET 
    location_name = t.name,
    port_type = t.modes,
    schedule_d_code = t.code, -- Ensure Schedule D is set
    updated_at = NOW()
FROM temp_aes_ports_full t
WHERE pl.location_code = t.code OR pl.schedule_d_code = t.code;

-- 2. Insert NEW ports that don't exist
INSERT INTO public.ports_locations (
    location_code,
    location_name,
    schedule_d_code,
    port_type,
    country_code,
    country,
    created_at,
    updated_at
)
SELECT 
    t.code,
    t.name,
    t.code,
    t.modes,
    'US',
    'United States',
    NOW(),
    NOW()
FROM temp_aes_ports_full t
WHERE NOT EXISTS (
    SELECT 1 FROM public.ports_locations pl 
    WHERE pl.location_code = t.code OR pl.schedule_d_code = t.code
);

-- 3. Log the operation
INSERT INTO public.audit_logs (action, resource_type, details)
VALUES (
    'SEED_AES_APPENDIX_D_FULL', 
    'ports_locations', 
    jsonb_build_object(
        'description', 'Full seeding from AESTIR Excel',
        'record_count', 440,
        'source', 'AESTIR_Export_Reference_Data.xlsx'
    )
);

DROP TABLE temp_aes_ports_full;

COMMIT;
