-- Migration to add MGL-Main-Template with Matrix Rate Table

DO $$
DECLARE
    v_tenant_id UUID;
    v_template_id UUID;
BEGIN
    -- Get MGL Tenant ID (assuming it exists, otherwise this will be global or fail gracefully)
    -- If no tenant found, we insert as global template (tenant_id IS NULL)
    SELECT id INTO v_tenant_id FROM tenants WHERE name LIKE '%Miami Global Lines%' LIMIT 1;

    -- Delete existing if any (to allow re-run)
    DELETE FROM quote_templates WHERE name = 'MGL-Main-Template';

    INSERT INTO quote_templates (tenant_id, name, description, category, content, is_active, version)
    VALUES (
        v_tenant_id,
        'MGL-Main-Template',
        'Main template for MGL with Matrix Rate Table',
        'General',
        '{
            "layout": "mgl_matrix",
            "header": {
                "show_logo": true,
                "company_info": true,
                "title": "QUOTATION"
            },
            "sections": [
                {
                    "type": "header",
                    "height": 120,
                    "content": {
                        "text": "MGL Global Logistics",
                        "alignment": "left"
                    }
                },
                {
                    "type": "key_value_grid",
                    "height": 100,
                    "grid_fields": [
                        { "key": "customer.company_name", "label": "Customer" },
                        { "key": "quote.quote_number", "label": "Quote Ref" },
                        { "key": "quote.created_at", "label": "Date", "format": "date" },
                        { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                        { "key": "customer.contact_name", "label": "Attn" },
                        { "key": "legs[0].pol", "label": "Origin" },
                        { "key": "legs[0].pod", "label": "Destination" },
                        { "key": "items[0].commodity", "label": "Commodity" }
                    ]
                },
                {
                    "type": "matrix_rate_table",
                    "height": 300,
                    "page_break_before": false,
                    "content": {
                        "text": "Freight Rates"
                    }
                },
                {
                    "type": "terms_block",
                    "height": 150,
                    "page_break_before": false,
                    "content": {
                        "text": "Terms and Conditions"
                    }
                },
                {
                    "type": "footer",
                    "height": 50,
                    "content": {
                        "text": "Thank you for your business."
                    }
                }
            ],
            "footer": {
                "text": "Generated by SOS Nexus"
            },
            "config": {
                "page_size": "A4",
                "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 },
                "font_family": "Helvetica"
            }
        }'::jsonb,
        true,
        1
    );

END $$;
