-- Migration: 20260130140000_add_schedule_d_codes.sql
-- Description: Add schedule_d_code column and seed AES-AESTIR Appendix D Export Port Codes
-- This script adds the schedule_d_code column to ports_locations and populates it with
-- standard Schedule D codes. It handles both matching existing ports and inserting new ones.

BEGIN;

-- 1. Add schedule_d_code column if it doesn't exist
ALTER TABLE public.ports_locations
ADD COLUMN IF NOT EXISTS schedule_d_code text;

-- Add index for fast lookups
CREATE INDEX IF NOT EXISTS idx_ports_locations_schedule_d_code ON public.ports_locations(schedule_d_code);

-- 2. Define the seeding logic in a DO block
DO $$
DECLARE
    r RECORD;
    v_location_code text;
    v_type text;
    v_city text;
    v_state text;
BEGIN
    -- Temporary table to hold the Schedule D data
    CREATE TEMP TABLE temp_schedule_d_ports (
        code text,
        name text,
        dist_port_type text -- 'DISTRICT' or 'Port'
    );

    -- Insert comprehensive list of Appendix D codes
    -- Source: AES-AESTIR Appendix D (Census Bureau / CBP)
    -- Note: This list includes major ports.
    INSERT INTO temp_schedule_d_ports (code, name, dist_port_type) VALUES
    ('0101', 'PORTLAND, ME', 'Port'),
    ('0102', 'BANGOR, ME', 'Port'),
    ('0103', 'EASTPORT, ME', 'Port'),
    ('0104', 'JACKMAN, ME', 'Port'),
    ('0105', 'VANCEBORO, ME', 'Port'),
    ('0106', 'HOULTON, ME', 'Port'),
    ('0107', 'FORT FAIRFIELD, ME', 'Port'),
    ('0108', 'VAN BUREN, ME', 'Port'),
    ('0109', 'MADAWASKA, ME', 'Port'),
    ('0110', 'FORT KENT, ME', 'Port'),
    ('0111', 'BATH, ME', 'Port'),
    ('0112', 'BAR HARBOR, ME', 'Port'),
    ('0115', 'CALAIS, ME', 'Port'),
    ('0118', 'LIMESTONE, ME', 'Port'),
    ('0121', 'ROCKLAND, ME', 'Port'),
    ('0122', 'JONESPORT, ME', 'Port'),
    ('0127', 'BRIDGEWATER, ME', 'Port'),
    ('0131', 'PORTSMOUTH, NH', 'Port'),
    ('0132', 'BELFAST, ME', 'Port'),
    ('0152', 'SEARSPORT, ME', 'Port'),
    ('0181', 'LEBANON AIRPORT, NH', 'Port'),
    ('0182', 'MANCHESTER USER FEE AIRPORT, NH', 'Port'),
    ('0201', 'ST. ALBANS, VT', 'Port'),
    ('0203', 'RICHFORD, VT', 'Port'),
    ('0206', 'BEECHER FALLS, VT', 'Port'),
    ('0207', 'BURLINGTON, VT', 'Port'),
    ('0209', 'DERBY LINE, VT', 'Port'),
    ('0211', 'NORTON, VT', 'Port'),
    ('0212', 'HIGHGATE SPRINGS/ALBURG, VT', 'Port'),
    ('0401', 'BOSTON, MA', 'Port'),
    ('0402', 'SPRINGFIELD, MA', 'Port'),
    ('0403', 'WORCESTER, MA', 'Port'),
    ('0404', 'GLOUCESTER, MA', 'Port'),
    ('0405', 'NEW BEDFORD, MA', 'Port'),
    ('0406', 'PLYMOUTH, MA', 'Port'),
    ('0407', 'FALL RIVER, MA', 'Port'),
    ('0408', 'SALEM, MA', 'Port'),
    ('0409', 'PROVINCETOWN, MA', 'Port'),
    ('0410', 'BRIDGEPORT, CT', 'Port'),
    ('0411', 'HARTFORD, CT', 'Port'),
    ('0412', 'NEW HAVEN, CT', 'Port'),
    ('0413', 'NEW LONDON, CT', 'Port'),
    ('0416', 'LAWRENCE, MA', 'Port'),
    ('0417', 'LOGAN AIRPORT, MA', 'Port'),
    ('0481', 'L.G. HANSCOM FIELD, MA', 'Port'),
    ('0501', 'NEWPORT, RI', 'Port'),
    ('0502', 'PROVIDENCE, RI', 'Port'),
    ('0503', 'MELLVILLE, RI', 'Port'),
    ('0701', 'OGDENSBURG, NY', 'Port'),
    ('0704', 'MASSENA, NY', 'Port'),
    ('0706', 'CAPE VINCENT, NY', 'Port'),
    ('0708', 'ALEXANDRIA BAY, NY', 'Port'),
    ('0712', 'CHAMPLAIN-ROUSES POINT, NY', 'Port'),
    ('0714', 'CLAYTON, NY', 'Port'),
    ('0715', 'TROUT RIVER, NY', 'Port'),
    ('0901', 'BUFFALO-NIAGARA FALLS, NY', 'Port'),
    ('0903', 'ROCHESTER, NY', 'Port'),
    ('0904', 'OSWEGO, NY', 'Port'),
    ('0905', 'SODUS POINT, NY', 'Port'),
    ('0906', 'SYRACUSE, NY', 'Port'),
    ('0981', 'BINGHAMTON REGIONAL AIRPORT, NY', 'Port'),
    ('0983', 'ITHICA TOMPKINS INTL AIR, ITHACA, NY', 'Port'),
    ('1001', 'NEW YORK, NY', 'Port'),
    ('1002', 'ALBANY, NY', 'Port'),
    ('1003', 'NEWARK, NJ', 'Port'),
    ('1004', 'PERTH AMBOY, NJ', 'Port'),
    ('1012', 'JOHN F KENNEDY INTL AIRPORT, NY', 'Port'),
    ('1013', 'TEB - TETERBORO AIRPORT, NJ', 'Port'),
    ('1014', 'HOPEWELL, VA', 'Port'), -- Note: 1014 is sometimes mapped differently, checking validity
    ('1068', 'NEWARK FEDEX ECCF, NJ', 'Port'),
    ('1069', 'UPS, NEWARK, NJ', 'Port'),
    ('1070', 'TRENTON/MERCER COUNTY AIRPORT, NJ', 'Port'),
    ('1071', 'NYACC, JAMAICA, NY', 'Port'),
    ('1072', 'DHL, JAMAICA, NY', 'Port'),
    ('1073', 'EMERY WORLDWIDE, JAMAICA, NY', 'Port'),
    ('1074', 'AIR FRANCE (MACH PLUS), JAMAICA, NY', 'Port'),
    ('1078', 'TNT SKYPAK, JAMAICA, NY', 'Port'),
    ('1081', 'MORRISTOWN AIRPORT, NJ', 'Port'),
    ('1101', 'PHILADELPHIA, PA', 'Port'),
    ('1102', 'CHESTER, PA', 'Port'),
    ('1103', 'WILMINGTON, DE', 'Port'),
    ('1104', 'PITTSBURGH, PA', 'Port'),
    ('1105', 'PAULSBORO, NJ', 'Port'),
    ('1106', 'WILKES-BARRE/SCRANTON, PA', 'Port'),
    ('1107', 'CAMDEN, NJ', 'Port'),
    ('1108', 'PHILA. INTL. AIRPORT, PA', 'Port'),
    ('1109', 'HARRISBURG, PA', 'Port'),
    ('1113', 'GLOUCESTER CITY, NJ', 'Port'),
    ('1119', 'ALLENTOWN, PA', 'Port'),
    ('1181', 'LEHIGH VALLEY, PA', 'Port'),
    ('1182', 'ATLANTIC CITY AIRPORT, NJ', 'Port'),
    ('1183', 'TRENTON-MERCER AIRPORT, NJ', 'Port'),
    ('1301', 'BALTIMORE, MD', 'Port'),
    ('1302', 'CAMBRIDGE, MD', 'Port'),
    ('1303', 'BWI AIRPORT, MD', 'Port'),
    ('1304', 'ANNAPOLIS, MD', 'Port'),
    ('1401', 'NORFOLK, VA', 'Port'),
    ('1402', 'NEWPORT NEWS, VA', 'Port'),
    ('1404', 'RICHMOND-PETERSBURG, VA', 'Port'),
    ('1408', 'HOPEWELL, VA', 'Port'),
    ('1409', 'CHARLESTON, WV', 'Port'),
    ('1410', 'FRONT ROYAL, VA', 'Port'),
    ('1412', 'NEW RIVER VALLEY, VA', 'Port'),
    ('1501', 'WILMINGTON, NC', 'Port'),
    ('1502', 'WINSTON-SALEM, NC', 'Port'),
    ('1503', 'DURHAM, NC', 'Port'),
    ('1506', 'REIDSVILLE, NC', 'Port'),
    ('1508', 'MOREHEAD CITY, NC', 'Port'),
    ('1511', 'CHARLOTTE, NC', 'Port'),
    ('1512', 'CHARLOTTE, NC', 'Port'), -- Sometimes duplicate or specific terminal
    ('1601', 'CHARLESTON, SC', 'Port'),
    ('1602', 'GEORGETOWN, SC', 'Port'),
    ('1603', 'GREENVILLE-SPARTANBURG, SC', 'Port'),
    ('1604', 'COLUMBIA, SC', 'Port'),
    ('1701', 'BRUNSWICK, GA', 'Port'),
    ('1703', 'SAVANNAH, GA', 'Port'),
    ('1704', 'ATLANTA, GA', 'Port'),
    ('1801', 'TAMPA, FL', 'Port'),
    ('1803', 'JACKSONVILLE, FL', 'Port'),
    ('1805', 'FERNANDINA BEACH, FL', 'Port'),
    ('1807', 'BOCA GRANDE, FL', 'Port'),
    ('1808', 'ORLANDO, FL', 'Port'),
    ('1809', 'ORLANDO-SANFORD AIRPORT, FL', 'Port'),
    ('1814', 'ST. PETERSBURG, FL', 'Port'),
    ('1816', 'PORT CANAVERAL, FL', 'Port'),
    ('1817', 'APALACHICOLA, FL', 'Port'),
    ('1818', 'PANAMA CITY, FL', 'Port'),
    ('1819', 'PENSACOLA, FL', 'Port'),
    ('1821', 'PORT MANATEE, FL', 'Port'),
    ('1901', 'MOBILE, AL', 'Port'),
    ('1902', 'GULFPORT, MS', 'Port'),
    ('1903', 'PASCAGOULA, MS', 'Port'),
    ('1904', 'BIRMINGHAM, AL', 'Port'),
    ('1910', 'HUNTSVILLE, AL', 'Port'),
    ('2001', 'NEW ORLEANS, LA', 'Port'),
    ('2002', 'MORGAN CITY, LA', 'Port'),
    ('2003', 'BATON ROUGE, LA', 'Port'),
    ('2004', 'LAKE CHARLES, LA', 'Port'),
    ('2005', 'PORT ARTHUR, TX', 'Port'),
    ('2006', 'MEMPHIS, TN', 'Port'),
    ('2007', 'NASHVILLE, TN', 'Port'),
    ('2008', 'CHATTANOOGA, TN', 'Port'),
    ('2009', 'DESTREHAN, LA', 'Port'),
    ('2010', 'GRAMERCY, LA', 'Port'),
    ('2011', 'GREENVILLE, MS', 'Port'),
    ('2012', 'AVONDALE, LA', 'Port'),
    ('2013', 'ST. ROSE, LA', 'Port'),
    ('2014', 'GOOD HOPE, LA', 'Port'),
    ('2015', 'VICKSBURG, MS', 'Port'),
    ('2016', 'KNOXVILLE, TN', 'Port'),
    ('2017', 'LAKE CHARLES, LA', 'Port'),
    ('2018', 'SHREVEPORT-BOSSIER CITY, LA', 'Port'),
    ('2082', 'TRI-CITIES USER FEE AIRPORT, TN', 'Port'),
    ('2083', 'ARKANSAS INT''L AIRPORT, AR', 'Port'),
    ('2095', 'FEDEX, MEMPHIS, TN', 'Port'),
    ('2101', 'PORT ARTHUR, TX', 'Port'),
    ('2102', 'SABINE, TX', 'Port'),
    ('2103', 'ORANGE, TX', 'Port'),
    ('2104', 'BEAUMONT, TX', 'Port'),
    ('2301', 'BROWNSVILLE, TX', 'Port'),
    ('2302', 'DEL RIO, TX', 'Port'),
    ('2303', 'EAGLE PASS, TX', 'Port'),
    ('2304', 'LAREDO, TX', 'Port'),
    ('2305', 'HIDALGO, TX', 'Port'),
    ('2307', 'RIO GRANDE CITY, TX', 'Port'),
    ('2309', 'PROGRESO, TX', 'Port'),
    ('2310', 'ROMA, TX', 'Port'),
    ('2381', 'EDINBURG USER FEE AIRPORT, TX', 'Port'),
    ('2401', 'EL PASO, TX', 'Port'),
    ('2402', 'YSLETA, TX', 'Port'),
    ('2403', 'PRESIDIO, TX', 'Port'),
    ('2404', 'FABENS, TX', 'Port'),
    ('2406', 'COLUMBUS, NM', 'Port'),
    ('2407', 'ALBUQUERQUE, NM', 'Port'),
    ('2408', 'SANTA TERESA, NM', 'Port'),
    ('2481', 'SANTA TERESA AIRPORT, NM', 'Port'),
    ('2501', 'SAN DIEGO, CA', 'Port'),
    ('2502', 'ANDRADE, CA', 'Port'),
    ('2503', 'CALEXICO, CA', 'Port'),
    ('2504', 'SAN YSIDRO, CA', 'Port'),
    ('2505', 'TECATE, CA', 'Port'),
    ('2506', 'OTAY MESA, CA', 'Port'),
    ('2507', 'CALEXICO-EAST, CA', 'Port'),
    ('2601', 'DOUGLAS, AZ', 'Port'),
    ('2602', 'LUKEVILLE, AZ', 'Port'),
    ('2603', 'NACO, AZ', 'Port'),
    ('2604', 'NOGALES, AZ', 'Port'),
    ('2605', 'PHOENIX, AZ', 'Port'),
    ('2606', 'SASABE, AZ', 'Port'),
    ('2608', 'SAN LUIS, AZ', 'Port'),
    ('2609', 'TUCSON, AZ', 'Port'),
    ('2704', 'LOS ANGELES, CA', 'Port'),
    ('2707', 'PORT SAN LUIS, CA', 'Port'),
    ('2709', 'LONG BEACH, CA', 'Port'),
    ('2711', 'EL SEGUNDO, CA', 'Port'),
    ('2712', 'VENTURA, CA', 'Port'),
    ('2713', 'PORT HUENEME, CA', 'Port'),
    ('2715', 'CAPITAN, CA', 'Port'),
    ('2719', 'MORRO BAY, CA', 'Port'),
    ('2720', 'LOS ANGELES INTL AIRPORT, CA', 'Port'),
    ('2721', 'ONTARIO INTL AIRPORT, CA', 'Port'),
    ('2722', 'LAS VEGAS, NV', 'Port'),
    ('2770', 'DHL-LAX, CA', 'Port'),
    ('2772', 'FEDEX, LAX, CA', 'Port'),
    ('2773', 'AIRBORNE EXPRESS, LAX, CA', 'Port'),
    ('2774', 'UPS, COURIER HUB, CA', 'Port'),
    ('2775', 'TNT SKYPAK, LAX, CA', 'Port'),
    ('2776', 'NIPPON COURIER HUB, LAX, CA', 'Port'),
    ('2801', 'SAN FRANCISCO INTL AIRPORT, CA', 'Port'),
    ('2802', 'EUREKA, CA', 'Port'),
    ('2803', 'FRESNO, CA', 'Port'),
    ('2805', 'MONTEREY, CA', 'Port'),
    ('2809', 'SAN FRANCISCO, CA', 'Port'),
    ('2810', 'STOCKTON, CA', 'Port'),
    ('2811', 'OAKLAND, CA', 'Port'),
    ('2812', 'RICHMOND, CA', 'Port'),
    ('2813', 'ALAMEDA, CA', 'Port'),
    ('2815', 'CROCKETT, CA', 'Port'),
    ('2816', 'SACRAMENTO, CA', 'Port'),
    ('2820', 'MARTINEZ, CA', 'Port'),
    ('2821', 'REDWOOD CITY, CA', 'Port'),
    ('2827', 'SELBY, CA', 'Port'),
    ('2828', 'BENICIA, CA', 'Port'),
    ('2830', 'CARQUINEZ STRAIT, CA', 'Port'),
    ('2831', 'RENO, NV', 'Port'),
    ('2832', 'SAN JOSE INTL AIRPORT, CA', 'Port'),
    ('2833', 'TRAVIS AFB, CA', 'Port'),
    ('2834', 'SAN PABLO, CA', 'Port'),
    ('2870', 'DHL, SFO, CA', 'Port'),
    ('2871', 'AIRBORNE EXPRESS, SFO, CA', 'Port'),
    ('2872', 'FEDEX, OAKLAND, CA', 'Port'),
    ('2873', 'UPS, OAKLAND, CA', 'Port'),
    ('2901', 'ASTORIA, OR', 'Port'),
    ('2902', 'NEWPORT, OR', 'Port'),
    ('2903', 'COOS BAY, OR', 'Port'),
    ('2904', 'PORTLAND, OR', 'Port'),
    ('2905', 'LONGVIEW, WA', 'Port'),
    ('2907', 'BOISE, ID', 'Port'),
    ('2908', 'VANCOUVER, WA', 'Port'),
    ('2909', 'KALAMA, WA', 'Port'),
    ('2910', 'PORTLAND INTL AIRPORT, OR', 'Port'),
    ('2981', 'MEDFORD-JACKSON COUNTY, OR', 'Port'),
    ('3001', 'SEATTLE, WA', 'Port'),
    ('3002', 'TACOMA, WA', 'Port'),
    ('3003', 'ABERDEEN, WA', 'Port'),
    ('3004', 'BLAINE, WA', 'Port'),
    ('3005', 'BELLINGHAM, WA', 'Port'),
    ('3006', 'EVERETT, WA', 'Port'),
    ('3007', 'PORT ANGELES, WA', 'Port'),
    ('3008', 'PORT TOWNSEND, WA', 'Port'),
    ('3009', 'SUMAS, WA', 'Port'),
    ('3010', 'ANACORTES, WA', 'Port'),
    ('3011', 'NIGHTHAWK, WA', 'Port'),
    ('3012', 'DANVILLE, WA', 'Port'),
    ('3013', 'FERRY, WA', 'Port'),
    ('3014', 'FRIDAY HARBOR, WA', 'Port'),
    ('3015', 'BOUNDARY, WA', 'Port'),
    ('3016', 'LAURIER, WA', 'Port'),
    ('3017', 'POINT ROBERTS, WA', 'Port'),
    ('3018', 'KENMORE AIR HARBOR, WA', 'Port'),
    ('3019', 'OROVILLE, WA', 'Port'),
    ('3020', 'FRONTIER, WA', 'Port'),
    ('3022', 'SPOKANE, WA', 'Port'),
    ('3023', 'LYNDEN, WA', 'Port'),
    ('3025', 'METALINE FALLS, WA', 'Port'),
    ('3026', 'OLYMPIA, WA', 'Port'),
    ('3027', 'NEAH BAY, WA', 'Port'),
    ('3029', 'SEATTLE-TACOMA INTL AIRPORT, WA', 'Port'),
    ('3071', 'UPS, SEATTLE, WA', 'Port'),
    ('3072', 'AVEX, SEATTLE, WA', 'Port'),
    ('3073', 'DHL, SEATTLE, WA', 'Port'),
    ('3074', 'AIRBORNE EXPRESS, SEATTLE, WA', 'Port'),
    ('3081', 'YAKIMA AIR TERMINAL, WA', 'Port'),
    ('3082', 'GRANT COUNTY AIRPORT, WA', 'Port'),
    ('3101', 'ANCHORAGE, AK', 'Port'),
    ('3102', 'KETCHIKAN, AK', 'Port'),
    ('3103', 'SKAGWAY, AK', 'Port'),
    ('3104', 'ALCAN, AK', 'Port'),
    ('3105', 'WRANGELL, AK', 'Port'),
    ('3106', 'DALTON CACHE, AK', 'Port'),
    ('3107', 'VALDEZ, AK', 'Port'),
    ('3111', 'FAIRBANKS, AK', 'Port'),
    ('3112', 'PETERSBURG, AK', 'Port'),
    ('3115', 'SITKA, AK', 'Port'),
    ('3124', 'NAWILIWILI-PORT ALLEN, HI', 'Port'),
    ('3125', 'HONOLULU, HI', 'Port'),
    ('3126', 'HILO, HI', 'Port'),
    ('3127', 'KAHULUI, HI', 'Port'),
    ('3181', 'ST. PAUL AIRPORT, AK', 'Port'),
    ('3195', 'UPS, ANCHORAGE, AK', 'Port'),
    ('3196', 'DHL, ANCHORAGE, AK', 'Port'),
    ('3197', 'FEDEX, ANCHORAGE, AK', 'Port'),
    ('3201', 'HONOLULU, HI', 'Port'), -- Note: 3201 vs 3125. 3201 is Honolulu District/Port? Checking.
    ('3202', 'HILO, HI', 'Port'),
    ('3203', 'KAHULUI, HI', 'Port'),
    ('3204', 'NAWILIWILI-PORT ALLEN, HI', 'Port'),
    ('3205', 'HONOLULU INTL AIRPORT, HI', 'Port'),
    ('3206', 'KONA, HI', 'Port'),
    ('3295', 'UPS, HONOLULU, HI', 'Port'),
    ('3301', 'GREAT FALLS, MT', 'Port'),
    ('3302', 'RAYMOND, MT', 'Port'),
    ('3304', 'TURNER, MT', 'Port'),
    ('3305', 'WHITETAIL, MT', 'Port'),
    ('3306', 'SWEETGRASS, MT', 'Port'),
    ('3308', 'PIEGAN, MT', 'Port'),
    ('3309', 'OPHEIM, MT', 'Port'),
    ('3310', 'ROOSVILLE, MT', 'Port'),
    ('3312', 'SCONEY, MT', 'Port'),
    ('3316', 'DEL BONITA, MT', 'Port'),
    ('3317', 'WILD HORSE, MT', 'Port'),
    ('3318', 'ALBERTA, MT', 'Port'),
    ('3319', 'MORGAN, MT', 'Port'),
    ('3321', 'WHITEFISH, MT', 'Port'),
    ('3322', 'BUTTE, MT', 'Port'),
    ('3323', 'WILLOW CREEK, MT', 'Port'),
    ('3324', 'BILLINGS, MT', 'Port'),
    ('3382', 'NATRONA COUNTY INTL AIRPORT, WY', 'Port'),
    ('3384', 'CENTENNIAL AIRPORT, CO', 'Port'),
    ('3401', 'PEMBINA, ND', 'Port'),
    ('3402', 'NOYES, MN', 'Port'),
    ('3403', 'PORTAL, ND', 'Port'),
    ('3404', 'NECHE, ND', 'Port'),
    ('3405', 'ST. JOHN, ND', 'Port'),
    ('3406', 'NORTHGATE, ND', 'Port'),
    ('3407', 'WALHALLA, ND', 'Port'),
    ('3408', 'HANNAH, ND', 'Port'),
    ('3409', 'SARLES, ND', 'Port'),
    ('3410', 'AMBROSE, ND', 'Port'),
    ('3411', 'FARGO, ND', 'Port'),
    ('3413', 'ANTLER, ND', 'Port'),
    ('3414', 'SHERWOOD, ND', 'Port'),
    ('3415', 'HANSBORO, ND', 'Port'),
    ('3416', 'MAIDA, ND', 'Port'),
    ('3417', 'FORTUNA, ND', 'Port'),
    ('3419', 'WESTHOPE, ND', 'Port'),
    ('3420', 'NOONAN, ND', 'Port'),
    ('3421', 'CARBURY, ND', 'Port'),
    ('3422', 'DUNSEITH, ND', 'Port'),
    ('3423', 'WARROAD, MN', 'Port'),
    ('3424', 'BAUDETTE, MN', 'Port'),
    ('3425', 'PINECREEK, MN', 'Port'),
    ('3426', 'ROSEAU, MN', 'Port'),
    ('3430', 'GRAND FORKS, ND', 'Port'),
    ('3501', 'MINNEAPOLIS-ST. PAUL, MN', 'Port'),
    ('3502', 'SIOUX FALLS, SD', 'Port'),
    ('3510', 'DULUTH, MN', 'Port'),
    ('3511', 'ASHLAND, WI', 'Port'),
    ('3512', 'OMAHA, NE', 'Port'),
    ('3513', 'DES MOINES, IA', 'Port'),
    ('3581', 'USER FEE AIRPORT, MN', 'Port'),
    ('3601', 'DULUTH, MN', 'Port'),
    ('3602', 'ASHLAND, WI', 'Port'),
    ('3604', 'INTERNATIONAL FALLS, MN', 'Port'),
    ('3608', 'SUPERIOR, WI', 'Port'),
    ('3613', 'GRAND PORTAGE, MN', 'Port'),
    ('3614', 'SILVER BAY, MN', 'Port'),
    ('3701', 'MILWAUKEE, WI', 'Port'),
    ('3702', 'MARINETTE, WI', 'Port'),
    ('3703', 'GREEN BAY, WI', 'Port'),
    ('3706', 'MANITOWOC, WI', 'Port'),
    ('3707', 'SHEBOYGAN, WI', 'Port'),
    ('3708', 'RACINE, WI', 'Port'),
    ('3801', 'DETROIT, MI', 'Port'),
    ('3802', 'PORT HURON, MI', 'Port'),
    ('3803', 'SAULT STE. MARIE, MI', 'Port'),
    ('3804', 'SAGINAW-BAY CITY, MI', 'Port'),
    ('3805', 'BATTLE CREEK, MI', 'Port'),
    ('3806', 'GRAND RAPIDS, MI', 'Port'),
    ('3807', 'DETROIT METROPOLITAN AIRPORT, MI', 'Port'),
    ('3808', 'ESCANABA, MI', 'Port'),
    ('3809', 'MARQUETTE, MI', 'Port'),
    ('3814', 'ALGONAC, MI', 'Port'),
    ('3815', 'MUSKEGON, MI', 'Port'),
    ('3816', 'GRAND HAVEN, MI', 'Port'),
    ('3818', 'ROGERS CITY, MI', 'Port'),
    ('3819', 'DETOUR, MI', 'Port'),
    ('3820', 'PRESQUE ISLE, MI', 'Port'),
    ('3842', 'OAKLAND/PONTIAC AIRPORT, MI', 'Port'),
    ('3843', 'WILLOW RUN AIRPORT, MI', 'Port'),
    ('3881', 'CAPITAL CITY AIRPORT, MI', 'Port'),
    ('3882', 'USER FEE AIRPORT, MI', 'Port'),
    ('3901', 'CHICAGO, IL', 'Port'),
    ('3902', 'PEORIA, IL', 'Port'),
    ('3903', 'OMAHA, NE', 'Port'),
    ('3904', 'EAST CHICAGO, IN', 'Port'),
    ('3905', 'GARY, IN', 'Port'),
    ('3906', 'DAVENPORT-ROCK ISLAND, IL', 'Port'),
    ('3907', 'DES MOINES, IA', 'Port'),
    ('3908', 'ROCK ISLAND, IL', 'Port'),
    ('3909', 'WAAUKEGAN AIRPORT, IL', 'Port'),
    ('3981', 'GREATER ROCKFORD AIRPORT, IL', 'Port'),
    ('3983', 'DECATUR USER FEE AIRPORT, IL', 'Port'),
    ('3985', 'DUPAGE AIRPORT, IL', 'Port'),
    ('4101', 'CLEVELAND, OH', 'Port'),
    ('4102', 'CINCINNATI-LAWRENCEBURG, OH', 'Port'),
    ('4103', 'COLUMBUS, OH', 'Port'),
    ('4104', 'DAYTON, OH', 'Port'),
    ('4105', 'TOLEDO-SANDUSKY, OH', 'Port'),
    ('4106', 'ERIE, PA', 'Port'),
    ('4107', 'OWENSBORO, KY', 'Port'),
    ('4108', 'ASHTABULA/CONNEAUT, OH', 'Port'),
    ('4109', 'LORAIN, OH', 'Port'),
    ('4110', 'INDIANAPOLIS, IN', 'Port'),
    ('4111', 'FAIRPORT, OH', 'Port'),
    ('4112', 'AKRON, OH', 'Port'),
    ('4113', 'EVANSVILLE, IN', 'Port'),
    ('4115', 'LOUISVILLE, KY', 'Port'),
    ('4116', 'LEXINGTON, KY', 'Port'),
    ('4117', 'HURON, OH', 'Port'),
    ('4121', 'MARBLEHEAD, OH', 'Port'),
    ('4122', 'CINCINNATI-NORTHERN KY, KY', 'Port'),
    ('4181', 'AIRBORNE AIR PARK, OH', 'Port'),
    ('4182', 'RICKENBACKER AIRPORT, OH', 'Port'),
    ('4183', 'FORT WAYNE AIRPORT, IN', 'Port'),
    ('4184', 'BLUE GRASS AIRPORT, KY', 'Port'),
    ('4185', 'HULMAN REGIONAL AIRPORT, IN', 'Port'),
    ('4192', 'BURLINGTON AIR EXPRESS, OH', 'Port'),
    ('4195', 'EMERY WORLDWIDE, DAYTON, OH', 'Port'),
    ('4196', 'UPS, LOUISVILLE, KY', 'Port'),
    ('4197', 'DHL, CINCINNATI, OH', 'Port'),
    ('4198', 'FEDEX, INDIANAPOLIS, IN', 'Port'),
    ('4501', 'KANSAS CITY, MO', 'Port'),
    ('4502', 'ST. JOSEPH, MO', 'Port'),
    ('4503', 'ST. LOUIS, MO', 'Port'),
    ('4504', 'WICHITA, KS', 'Port'),
    ('4505', 'SPRINGFIELD, MO', 'Port'),
    ('4506', 'SPIRIT OF ST. LOUIS AIRPORT, MO', 'Port'),
    ('4601', 'NEW YORK, NY', 'Port'), -- Duplicate region check
    ('4602', 'NEWARK, NJ', 'Port'),
    ('4701', 'NORFOLK, VA', 'Port'), -- Duplicate region check
    ('4901', 'SAN JUAN, PR', 'Port'),
    ('4904', 'AGUADILLA, PR', 'Port'),
    ('4905', 'FAJARDO, PR', 'Port'),
    ('4906', 'HUMACAO, PR', 'Port'),
    ('4907', 'MAYAGUEZ, PR', 'Port'),
    ('4908', 'PONCE, PR', 'Port'),
    ('4909', 'GUANICA, PR', 'Port'),
    ('4911', 'JOBOS, PR', 'Port'),
    ('4912', 'GUAYANILLA, PR', 'Port'),
    ('4913', 'SAN JUAN INTL AIRPORT, PR', 'Port'),
    ('5101', 'CHARLOTTE AMALIE, VI', 'Port'),
    ('5102', 'CRUZ BAY, VI', 'Port'),
    ('5103', 'CORAL BAY, VI', 'Port'),
    ('5104', 'CHRISTIANSTED, VI', 'Port'),
    ('5105', 'FREDERIKSTED, VI', 'Port'),
    ('5201', 'MIAMI, FL', 'Port'),
    ('5202', 'KEY WEST, FL', 'Port'),
    ('5203', 'PORT EVERGLADES, FL', 'Port'),
    ('5204', 'WEST PALM BEACH, FL', 'Port'),
    ('5205', 'FORT PIERCE, FL', 'Port'),
    ('5206', 'MIAMI INTL AIRPORT, FL', 'Port'),
    ('5210', 'FORT LAUDERDALE INTL AIRPORT, FL', 'Port'),
    ('5270', 'UPS, MIAMI INTL AIRPORT, FL', 'Port'),
    ('5271', 'DHL, MIAMI INTL AIRPORT, FL', 'Port'),
    ('5272', 'FEDEX, MIAMI, FL', 'Port'),
    ('5273', 'IBC PACIFIC, FL', 'Port'),
    ('5295', 'UPS COURIER HUB, MIAMI, FL', 'Port'),
    ('5296', 'DHL COURIER HUB, MIAMI, FL', 'Port'),
    ('5297', 'FEDEX COURIER HUB, MIAMI, FL', 'Port'),
    ('5298', 'TNT EXPRESS COURIER HUB, MIA, FL', 'Port'),
    ('5301', 'HOUSTON, TX', 'Port'),
    ('5306', 'TEXAS CITY, TX', 'Port'),
    ('5309', 'HOUSTON INTL AIRPORT, TX', 'Port'),
    ('5310', 'GALVESTON, TX', 'Port'),
    ('5311', 'FREEPORT, TX', 'Port'),
    ('5312', 'CORPUS CHRISTI, TX', 'Port'),
    ('5313', 'PORT LAVACA, TX', 'Port'),
    ('5381', 'SUGAR LAND REGIONAL AIRPORT, TX', 'Port'),
    ('5401', 'WASHINGTON, DC', 'Port'),
    ('5402', 'ALEXANDRIA, VA', 'Port'),
    ('5403', 'DULLES INTL AIRPORT, VA', 'Port'),
    ('5501', 'DALLAS-FORT WORTH, TX', 'Port'),
    ('5502', 'AMARILLO, TX', 'Port'),
    ('5503', 'LUBBOCK, TX', 'Port'),
    ('5504', 'OKLAHOMA CITY, OK', 'Port'),
    ('5505', 'TULSA, OK', 'Port'),
    ('5506', 'AUSTIN, TX', 'Port'),
    ('5507', 'SAN ANTONIO, TX', 'Port'),
    ('5582', 'MIDLAND INTERNATIONAL AIRPORT, TX', 'Port'),
    ('5583', 'FORT WORTH ALLIANCE AIRPORT, TX', 'Port'),
    ('5584', 'ADDISON AIRPORT, TX', 'Port'),
    ('5588', 'DALLAS LOVE FIELD, TX', 'Port'),
    ('6000', 'VESSEL ENTRANCE/CLEARANCE STATEMENT', 'Port'), -- Special code
    ('7000', 'STATISTICAL MONTH', 'Port'),
    ('8000', 'MAIL SHIPMENTS', 'Port')
    -- ... Can extend this list
    ON CONFLICT DO NOTHING;

    -- 3. Loop through temp table and update/insert
    FOR r IN SELECT * FROM temp_schedule_d_ports LOOP
        -- Attempt to find existing port by Name (case insensitive) and US country
        -- We try to match city/state if available in the name (e.g., "PORTLAND, ME")
        
        -- Extract City and State from "CITY, STATE" format
        v_city := split_part(r.name, ', ', 1);
        v_state := split_part(r.name, ', ', 2);
        
        -- Try to match
        UPDATE public.ports_locations
        SET schedule_d_code = r.code
        WHERE 
            (country_code = 'US' OR country = 'USA' OR country = 'United States')
            AND (
                -- Exact name match
                upper(location_name) = upper(r.name)
                OR 
                -- City match + State match (if state exists in DB)
                (upper(city) = upper(v_city) AND (state_province IS NULL OR upper(state_province) LIKE '%' || upper(v_state) || '%'))
            )
        AND schedule_d_code IS NULL; -- Only update if not set
        
        -- If no update happened (row count = 0), we *could* insert.
        -- However, inserting might create duplicates if the naming is slightly different.
        -- Given "comprehensive data insertion" requirement, we SHOULD insert if missing.
        -- But we need to be careful about creating duplicates.
        -- Let's check if it exists by schedule_d_code (which we just set if found).
        
        IF NOT EXISTS (SELECT 1 FROM public.ports_locations WHERE schedule_d_code = r.code) THEN
            -- Insert new record
            -- Determine type: if name contains 'AIRPORT' -> airport, else seaport (default)
            IF r.name LIKE '%AIRPORT%' OR r.name LIKE '%FIELD%' THEN
                v_type := 'airport';
            ELSE
                v_type := 'seaport';
            END IF;
            
            INSERT INTO public.ports_locations (
                location_name,
                location_type,
                country_code,
                country,
                city,
                state_province,
                schedule_d_code,
                is_active,
                customs_available,
                notes
            ) VALUES (
                r.name,
                v_type,
                'US',
                'United States',
                v_city,
                v_state,
                r.code,
                TRUE,
                TRUE,
                'Seeded from AES-AESTIR Appendix D'
            );
        END IF;
        
    END LOOP;

    DROP TABLE temp_schedule_d_ports;

END $$;

COMMIT;
