-- AES-AESTIR Appendix D Seeding Migration
-- Generated from official CBP Appendix D PDF
-- Seeded Count: 384

BEGIN;

-- Ensure port_type column exists
ALTER TABLE public.ports_locations 
ADD COLUMN IF NOT EXISTS port_type text[];

-- Create a temp table for the new data
CREATE TEMP TABLE temp_aes_ports (
    code text,
    name text,
    modes text[]
);

INSERT INTO temp_aes_ports (code, name, modes) VALUES
('0101', 'PORTLAND, ME', '{"Vessel","Air"}'),
('0102', 'BANGOR, ME', '{"Vessel","Air"}'),
('0103', 'EASTPORT, ME', '{"Vessel"}'),
('0104', 'JACKMAN, ME', '{"Rail","Road"}'),
('0105', 'VANCEBORO, ME', '{"Rail","Road"}'),
('0106', 'HOULTON, ME', '{"Rail","Road"}'),
('0107', 'FORT FAIRFIELD, ME', '{"Rail","Road"}'),
('0108', 'VAN BUREN, ME', '{"Rail","Road"}'),
('0109', 'MADAWASKA, ME', '{"Rail","Road"}'),
('0110', 'FORT KENT, ME', '{"Rail","Road"}'),
('0111', 'BATH, ME', '{"Vessel"}'),
('0112', 'BAR HARBOR, ME', '{"Vessel"}'),
('0115', 'CALAIS, ME', '{"Vessel","Rail","Road","Fixed"}'),
('0118', 'LIMESTONE, ME', '{"Rail","Road"}'),
('0121', 'ROCKLAND, ME', '{"Vessel"}'),
('0122', 'JONESPORT, ME', '{"Vessel"}'),
('0127', 'BRIDGEWATER, ME', '{"Rail","Road"}'),
('0131', 'PORTSMOUTH, NH', '{"Vessel","Air"}'),
('0152', 'SEARSPORT, ME', '{"Vessel"}'),
('0182', 'MANCHESTER USER FEE AIRPORT, NH', '{"Air"}'),
('0201', 'ST. ALBANS, VT', '{"Road"}'),
('0203', 'RICHFORD, VT', '{"Rail","Road"}'),
('0206', 'BEECHER FALLS, VT', '{"Rail","Road","Fixed"}'),
('0207', 'BURLINGTON, VT', '{"Air"}'),
('0209', 'DERBY LINE, VT', '{"Rail","Road"}'),
('0211', 'NORTON, VT', '{"Rail","Road","Fixed"}'),
('0212', 'HIGHGATE SPRINGS/ALBURG', '{"Rail","Road"}'),
('0401', 'BOSTON, MA', '{"Vessel","Air"}'),
('0402', 'SPRINGFIELD, MA', '{"Air"}'),
('0403', 'WORCESTER, MA', '{"Air"}'),
('0404', 'GLOUCESTER, MA', '{"Vessel"}'),
('0405', 'NEW BEDFORD, MA', '{"Vessel"}'),
('0406', 'PLYMOUTH, MA', '{"Vessel"}'),
('0407', 'FALL RIVER, MA', '{"Vessel"}'),
('0408', 'SALEM, MA', '{"Vessel"}'),
('0410', 'BRIDGEPORT, CT', '{"Vessel"}'),
('0411', 'HARTFORD, CT', '{"Vessel","Air"}'),
('0412', 'NEW HAVEN, CT', '{"Vessel"}'),
('0413', 'NEW LONDON, CT', '{"Vessel"}'),
('0416', 'LAWRENCE, MA', '{"Air"}'),
('0417', 'LOGAN AIRPORT, MA', '{"Air"}'),
('0481', 'L.G. HANSCOM FIELD, BEDFIELD, MA', '{"Air"}'),
('0501', 'NEWPORT, RI', '{"Vessel"}'),
('0502', 'PROVIDENCE, RI', '{"Vessel"}'),
('0503', 'MELLVILLE, RI', '{"Vessel"}'),
('0701', 'OGDENSBURG, NY', '{"Vessel","Road"}'),
('0704', 'MASSENA, NY', '{"Vessel","Road"}'),
('0706', 'CAPE VINCENT, NY', '{"Vessel","Road"}'),
('0708', 'ALEXANDRIA BAY, NY', '{"Vessel","Road"}'),
('0712', 'CHAMPLAIN-ROUSES POINT, NY', '{"Vessel","Rail","Road"}'),
('0714', 'CLAYTON, NY', '{"Vessel"}'),
('0715', 'TROUT RIVER, NY', '{"Rail","Road"}'),
('0901', 'BUFFALO-NIAGARA FALLS NY', '{"Vessel","Air","Rail","Road","Fixed"}'),
('0903', 'ROCHESTER, NY', '{"Vessel","Air"}'),
('0904', 'OSWEGO, NY', '{"Vessel"}'),
('0905', 'SODUS POINT, NY', '{"Vessel"}'),
('0906', 'SYRACUSE, NY', '{"Vessel","Air"}'),
('0981', 'BINGHAMTON REGIONAL AIRPORT, NY', '{"Air"}'),
('0983', 'ITHACA TOMPKINS INT’L AIR, ITHACA, NY', '{"Air"}'),
('1001', 'NEW YORK, NY', '{"Vessel","Air"}'),
('1002', 'ALBANY, NY', '{"Vessel","Air"}'),
('1101', 'PHILADELPHIA, PA', '{"Vessel","Air"}'),
('1102', 'CHESTER, PA', '{"Vessel"}'),
('1103', 'WILMINGTON, DE', '{"Vessel","Air"}'),
('1104', 'PITTSBURGH, PA', '{"Air"}'),
('1106', 'WILKES-BARRE/SCRANTON PA', '{"Air"}'),
('1108', 'PHILA. INTL. AIRPORT, PA', '{"Air"}'),
('1109', 'HARRISBURG, PA', '{"Air"}'),
('1113', 'GLOUCESTER CITY, NJ', '{"Vessel","Air"}'),
('1119', 'ALLENTOWN, PA (LEHIGH VALLEY INT’L AIRPORT)', '{"Air"}'),
('1182', 'ATLANTIC CITY REGIONAL AIRPORT, NJ', '{"Air"}'),
('1183', 'TRENTON/MERCER COUNTY AIRPORT, NJ', '{"Air"}'),
('1195', 'UPS, PHILADELPHIA, PA', '{"Air"}'),
('1301', 'ANNAPOLIS, MD', '{"Vessel"}'),
('1302', 'CAMBRIDGE, MD', '{"Vessel"}'),
('1303', 'BALTIMORE, MD', '{"Vessel"}'),
('1304', 'CRISFIELD, MD', '{"Vessel"}'),
('1305', 'BWI AIRPORT', '{"Air"}'),
('1401', 'NORFOLK-NEWPORT NEWS, VA', '{"Vessel","Air"}'),
('1404', 'RICHMOND-PETERSBURG, VA', '{"Vessel","Air"}'),
('1409', 'CHARLESTON, WV', '{"Air"}'),
('1410', 'FRONT ROYAL, VA', '{"Air"}'),
('1412', 'NEW RIVER VALLEY AIRPORT, VA', '{"Air"}'),
('1501', 'WILMINGTON, NC', '{"Vessel","Air"}'),
('1502', 'WINSTON-SALEM, NC', '{"Air"}'),
('1503', 'DURHAM, NC', '{"Air"}'),
('1511', 'BEAUFORT-MOREHEAD CTY,NC', '{"Vessel"}'),
('1512', 'CHARLOTTE, NC', '{"Air"}'),
('1601', 'CHARLESTON, SC', '{"Vessel","Air"}'),
('1602', 'GEORGETOWN, SC', '{"Vessel"}'),
('1603', 'GREENVILLE-SPARTANBRG SC', '{"Air"}'),
('1604', 'COLUMBIA, SC', '{"Air"}'),
('1681', 'MYRTLE BEACH INT’L AIRPORT, SC', '{"Air"}'),
('1701', 'BRUNSWICK, GA', '{"Vessel"}'),
('1703', 'SAVANNAH, GA', '{"Vessel","Air","Rail","Road"}'),
('1704', 'ATLANTA, GA', '{"Air"}'),
('1801', 'TAMPA, FL', '{"Vessel","Air"}'),
('1803', 'JACKSONVILLE, FL', '{"Vessel","Air"}'),
('1805', 'FERNANDINA BEACH, FL', '{"Vessel"}'),
('1807', 'BOCA GRANDE, FL', '{"Vessel"}'),
('1808', 'ORLANDO, FL', '{"Air"}'),
('1809', 'ORLANDO-SANFORD AIRPORT, FL', '{"Air"}'),
('1814', 'ST. PETERSBURG, FL', '{"Vessel"}'),
('1816', 'PORT CANAVERAL, FL', '{"Vessel","Air"}'),
('1818', 'PANAMA CITY, FL', '{"Vessel"}'),
('1819', 'PENSACOLA, FL', '{"Vessel"}'),
('1821', 'PORT MANATEE, FL', '{"Vessel"}'),
('1822', 'FORT MYERS AIRPORT', '{"Air"}'),
('1880', 'NAPLES MUNICIPAL USER FEE AIRPORT', '{"Air"}'),
('1883', 'SARASOTA BRADENTON AIRPT', '{"Air"}'),
('1884', 'DAYTONA BEACH INT''L AIRP', '{"Air"}'),
('1885', 'MELBOURNE REGIONAL AIRPORT, FL', '{"Air"}'),
('1887', 'LEESBURG REGIONAL AIRPORT, FL', '{"Air"}'),
('1888', 'ORLANDO EXECUTIVE AIRPORT, FL', '{"Air"}'),
('1889', 'St. AUGUSTINE AIPRORT, FL', '{"Air"}'),
('1901', 'MOBILE, AL', '{"Vessel","Air"}'),
('1902', 'GULFPORT, MS', '{"Vessel"}'),
('1903', 'PASCAGOULA, MS', '{"Vessel"}'),
('1904', 'BIRMINGHAM, AL', '{"Air"}'),
('1910', 'HUNTSVILLE, AL', '{"Vessel","Air"}'),
('2001', 'MORGAN CITY, LA', '{"Vessel","Air"}'),
('2002', 'NEW ORLEANS, LA', '{"Vessel","Air"}'),
('2003', 'LITTLE ROCK, AR', '{"Air"}'),
('2004', 'BATON ROUGE, LA', '{"Vessel"}'),
('2006', 'MEMPHIS, TN', '{"Air"}'),
('2007', 'NASHVILLE, TN', '{"Air"}'),
('2008', 'CHATTANOOGA, TN', '{"Air"}'),
('2010', 'GRAMERCY, LA', '{"Vessel"}'),
('2011', 'GREENVILLE, MS', '{"Vessel"}'),
('2015', 'VICKSBURG, MS', '{"Air"}'),
('2016', 'KNOXVILLE, TN', '{"Air"}'),
('2017', 'LAKE CHARLES, LA', '{"Vessel"}'),
('2018', 'SHREVEPORT/BOSSIER CITY', '{"Air"}'),
('2027', 'TRI-CITY AIRPORT, TN', '{"Air"}'),
('2095', 'FEDERAL EXPRESS, MEMPHIS, TN', '{"Air"}'),
('2101', 'PORT ARTHUR, TX', '{"Vessel","Air"}'),
('2102', 'SABINE, TX', '{"Vessel","Air"}'),
('2103', 'ORANGE, TX', '{"Vessel","Air"}'),
('2104', 'BEAUMONT, TX', '{"Vessel","Air"}'),
('2301', 'BROWNSVILLE, TX', '{"Vessel","Air","Rail","Road","Fixed"}'),
('2302', 'DEL RIO, TX', '{"Air","Road"}'),
('2303', 'EAGLE PASS, TX', '{"Air","Rail","Road"}'),
('2304', 'LAREDO, TX', '{"Air","Rail","Road","Fixed"}'),
('2305', 'HIDALGO,TX', '{"Air","Road","Fixed"}'),
('2307', 'RIO GRANDE CITY, TX', '{"Road"}'),
('2309', 'PROGRESO, TX', '{"Road"}'),
('2310', 'ROMA, TX', '{"Road"}'),
('2383', 'VALLEY INT’L. AIRPORT, HARLINGEN, TX', '{"Air"}'),
('2401', 'PORT OF YSLETA, TX', '{"Road"}'),
('2402', 'EL PASO, TX', '{"Air","Rail","Road","Fixed"}'),
('2403', 'PRESIDIO, TX', '{"Rail","Road"}'),
('2404', 'FABENS, TX', '{"Rail","Road"}'),
('2406', 'COLUMBUS, NM', '{"Rail","Road"}'),
('2407', 'ALBUQUERQUE, NM', '{"Air"}'),
('2408', 'SANTA TERESA, NM', '{"Road"}'),
('2481', 'SANTA TERESA AIRPORT, NM', '{"Air"}'),
('2501', 'SAN DIEGO, CA', '{"Vessel","Air"}'),
('2502', 'ANDRADE, CA', '{"Road"}'),
('2503', 'CALEXICO, CA', '{"Air","Rail","Road"}'),
('2504', 'SAN YSIDRO, CA', '{"Air","Rail","Road"}'),
('2505', 'TECATE, CA', '{"Rail","Road"}'),
('2506', 'OTAY MESA, CA', '{"Air","Rail","Road","Fixed"}'),
('2507', 'CALEXICO-EAST, CA', '{"Rail","Road"}'),
('2601', 'DOUGLAS, AZ', '{"Road","Fixed"}'),
('2602', 'LUKEVILLE, AZ', '{"Road"}'),
('2603', 'NACO, AZ', '{"Road"}'),
('2604', 'NOGALES, AZ', '{"Air","Rail","Road"}'),
('2605', 'PHOENIX, AZ', '{"Air"}'),
('2606', 'SASABE, AZ', '{"Road"}'),
('2608', 'SAN LUIS, AZ', '{"Road"}'),
('2609', 'TUCSON, AZ', '{"Air"}'),
('2704', 'LOS ANGELES, CA', '{"Vessel"}'),
('2709', 'LONG BEACH, CA', '{"Vessel"}'),
('2712', 'VENTURA, CA', '{"Vessel"}'),
('2713', 'PORT HUENEME, CA', '{"Vessel"}'),
('2715', 'CAPITAN, CA', '{"Vessel"}'),
('2719', 'MORRO BAY, CA', '{"Vessel"}'),
('2720', 'LOS ANGELES INT ARPT, CA', '{"Air"}'),
('2721', 'ONTARIO INTL AIRPORT, CA', '{"Air"}'),
('2722', 'LAS VEGAS, NV', '{"Air"}'),
('2775', 'TNT EXPRESS, LAX, CA', '{"Air"}'),
('2776', 'IBC PACIFIC', '{"Air"}'),
('3013', 'FERRY, WA', '{"Road"}'),
('3014', 'FRIDAY HARBOR, WA', '{"Vessel"}'),
('3015', 'BOUNDARY, WA', '{"Rail","Road"}'),
('3016', 'LAURIER, WA', '{"Air","Rail","Road"}'),
('3017', 'POINT ROBERTS, WA', '{"Vessel","Rail","Road"}'),
('3018', 'KENMORE AIR HARBOR, WA', '{"Air"}'),
('3019', 'OROVILLE, WA', '{"Air","Road"}'),
('3020', 'FRONTIER, WA', '{"Road"}'),
('3022', 'SPOKANE, WA', '{"Air"}'),
('3023', 'LYNDEN, WA', '{"Rail","Road"}'),
('3025', 'METALINE FALLS', '{"Road"}'),
('3026', 'OLYMPIA, WA', '{"Vessel"}'),
('3029', 'SEATTLE-TACOMA INTL ARPT', '{"Air"}'),
('3071', 'UPS, SEATTLE, WA', '{"Air"}'),
('3072', 'AVION BROKERS @ SEATAC', '{"Air"}'),
('3073', 'DHL, SEATTLE, WA', '{"Air"}'),
('3074', 'AIRBORNE EXPRESS @SEATAC', '{"Air"}'),
('3082', 'GRANT COUNTY AIRPORT, WA', '{"Air"}'),
('3095', 'UPS, SEATTLE, WA', '{"Air"}'),
('3101', 'JUNEAU, AK', '{"Vessel"}'),
('3102', 'KETCHIKAN, AK', '{"Vessel"}'),
('3103', 'SKAGWAY, AK', '{"Vessel","Air","Rail","Road"}'),
('3104', 'ALCAN, AK', '{"Air","Road"}'),
('3105', 'WRANGELL, AK', '{"Vessel","Air"}'),
('3106', 'DALTON CACHE, AK', '{"Vessel","Air","Road"}'),
('3111', 'FAIRBANKS, AK', '{"Vessel","Air"}'),
('3115', 'SITKA, AK', '{"Vessel","Air"}'),
('3126', 'ANCHORAGE, AK', '{"Vessel","Air"}'),
('3195', 'FEDERAL EXPRESS, ANCHORAGE, AK', '{"Air"}'),
('3196', 'UPS, ANCHORAGE, AK', '{"Air"}'),
('3201', 'HONOLULU, HI', '{"Vessel"}'),
('3202', 'HIL0, HI', '{"Vessel","Air"}'),
('3203', 'KAHULUI, HI', '{"Vessel","Air"}'),
('3204', 'NAWILIWILI-PORT ALLEN, HI', '{"Vessel"}'),
('3205', 'HONOLULU INTL AIRPRT, HI', '{"Air"}'),
('3206', 'KAILUA-KONA, HI', '{"Vessel","Air"}'),
('3301', 'RAYMOND, MT', '{"Road"}'),
('3302', 'EASTPORT, ID', '{"Rail","Road"}'),
('3303', 'SALT LAKE CITY, UT', '{"Air","Rail"}'),
('3304', 'GREAT FALLS, MT', '{"Air"}'),
('3305', 'BUTTE, MT', '{"Air"}'),
('3306', 'TURNER, MT', '{"Road"}'),
('3307', 'DENVER, CO', '{"Air"}'),
('3308', 'PORTHILL, ID', '{"Road"}'),
('3309', 'SCOBY, MT', '{"Road"}'),
('3310', 'SWEETGRASS, MT', '{"Rail","Road"}'),
('3316', 'PIEGAN, MT', '{"Rail","Road"}'),
('3317', 'OPHEIM, MT', '{"Road"}'),
('3318', 'ROOSVILLE, MT', '{"Road"}'),
('3319', 'MORGAN, MT', '{"Road"}'),
('3321', 'WHITLASH, MT', '{"Air"}'),
('3322', 'DEL BONITA, MT', '{"Air","Rail","Road"}'),
('3323', 'WILDHORSE, MT', '{"Road"}'),
('3324', 'KALISPELL AIRPORT, MT', '{"Air"}'),
('3325', 'WILLOW CREEK, HAVRE, MT', '{"Road"}'),
('3384', 'ARAPAHOE COUNTY PUBLIC AIRPORT, CO', '{"Air"}'),
('3385', 'EAGLE COUNTY REGIONAL AIRPORT', '{"Air"}'),
('3386', 'BOZEMAN YELLOWSTONE USER FEE AIRPORT', '{"Air"}'),
('3401', 'PEMBINA, ND', '{"Air","Rail","Road","Fixed"}'),
('3403', 'PORTAL, ND', '{"Rail","Road"}'),
('3404', 'NECHE, ND', '{"Rail","Road"}'),
('3405', 'ST JOHN, ND', '{"Rail","Road"}'),
('3406', 'NORTHGATE, ND', '{"Rail","Road"}'),
('3407', 'WALHALLA, ND', '{"Rail","Road"}'),
('3408', 'HANNAH, ND', '{"Rail","Road"}'),
('3409', 'SARLES, ND', '{"Rail","Road"}'),
('3410', 'AMBROSE, ND', '{"Rail","Road"}'),
('3411', 'FARGO, ND', '{"Air"}'),
('3413', 'ANTLER, ND', '{"Rail","Road"}'),
('3414', 'SHERWOOD, ND', '{"Rail","Road"}'),
('3415', 'HANSBORO, ND', '{"Rail","Road"}'),
('3416', 'MAIDA, ND', '{"Rail","Road"}'),
('3417', 'FORTUNA, ND', '{"Rail","Road"}'),
('3419', 'WESTHOPE, ND', '{"Rail","Road"}'),
('3420', 'NOONAN, ND', '{"Rail","Road"}'),
('3421', 'CARBURY, ND', '{"Rail","Road"}'),
('3422', 'DUNSEITH, ND', '{"Rail","Road"}'),
('3423', 'WARROAD, MN', '{"Rail","Road"}'),
('3424', 'BAUDETTE, MN', '{"Road"}'),
('3425', 'PINECREEK, MN', '{"Road"}'),
('3426', 'ROSEAU, MN', '{"Road"}'),
('3427', 'GRAND FORKS, ND', '{"Air"}'),
('3430', 'LANCASTER, MN', '{"Road","Fixed"}'),
('3433', 'WILLISTON AIRPORT, ND', '{"Air"}'),
('3434', 'MINOT AIRPORT, ND', '{"Air"}'),
('3501', 'MINNEAPOLIS-ST. PAUL, MN', '{"Air"}'),
('3502', 'SOUIX FALLS, SD', '{"Air"}'),
('3510', 'DULUTH, MN – SUPERIOR, WI', '{"Vessel","Air"}'),
('3511', 'ASHLAND, WI', '{"Vessel"}'),
('3512', 'OMAHA, NE', '{"Air"}'),
('3513', 'DES MOINES, IA', '{"Air"}'),
('3581', 'USER FEE AIRPORT, MN', '{"Air"}'),
('3604', 'INTERNATIONAL FALLS, MN', '{"Vessel","Air","Rail","Road"}'),
('3613', 'GRAND PORTAGE, MN', '{"Vessel","Road"}'),
('3701', 'MILWAUKEE, WI', '{"Vessel","Air"}'),
('3702', 'MARINETTE, WI', '{"Vessel"}'),
('3703', 'GREEN BAY, WI', '{"Vessel","Air"}'),
('3706', 'MANITOWOC, WI', '{"Vessel"}'),
('3708', 'RACINE, WI', '{"Vessel"}'),
('3801', 'DETROIT, MI', '{"Vessel","Rail","Road","Fixed"}'),
('3802', 'PORT HURON, MI', '{"Vessel","Rail","Road","Fixed"}'),
('3803', 'SAULT STE. MARIE, MI', '{"Vessel","Air","Rail","Road"}'),
('3804', 'SAGINAW/BAY CITY, MI', '{"Vessel"}'),
('3805', 'BATTLE CREEK, MI', '{"Vessel","Air"}'),
('3806', 'GRAND RAPIDS, MI', '{"Air"}'),
('3807', 'DETROIT METROPOLITAN AIRPORT', '{"Air"}'),
('3808', 'ESCANABA, MI', '{"Vessel"}'),
('3809', 'MARQUETTE, MI', '{"Vessel"}'),
('3814', 'ALGONAC, MI', '{"Vessel","Rail","Road"}'),
('3815', 'MUSKEGON, MI', '{"Vessel"}'),
('3816', 'GRAND HAVEN, MI', '{"Vessel"}'),
('3818', 'ROGERS CITY, MI', '{"Vessel"}'),
('3819', 'DETOUR, MI', '{"Vessel"}'),
('3842', 'PRESQUE ISLE, MI', '{"Vessel"}'),
('3843', 'ALPENA, MI', '{"Vessel"}'),
('3881', 'OAKLAND/PONTIAC AIRPORT, MI', '{"Air"}'),
('3882', 'WILLOW RUN AIRPORT, MI', '{"Air"}'),
('3883', 'CAPITAL REGION INTL AIPRORT, MI', '{"Air"}'),
('3901', 'CHICAGO, IL', '{"Vessel","Air"}'),
('3902', 'PEORIA, IL', '{"Air"}'),
('3905', 'GARY, IN', '{"Vessel"}'),
('3908', 'DAVENPORT-ROCK ISLAND, IL', '{"Air"}'),
('3909', 'GREATER ROCKFORD AIRPORT, IL', '{"Air"}'),
('3910', 'CHICAGO MIDWAY INT’L AIRPORT, IL', '{"Air"}'),
('3971', 'TNT EXPRESS CONSIGNMENT, CHICAGO, IL', '{"Air"}'),
('3983', 'CHICAGO EXECUTIVE AIRPORT', '{"Air"}'),
('3987', 'UFA UI WILLARD AIRPORT, SAVOY, IL', '{"Air"}'),
('4101', 'CLEVELAND, OH', '{"Vessel","Air"}'),
('4102', 'CINCINNATI, OH', '{"Air"}'),
('4103', 'COLUMBUS, OH', '{"Air"}'),
('4104', 'DAYTON, OH', '{"Air"}'),
('4105', 'TOLEDO, OH', '{"Vessel","Air"}'),
('4106', 'ERIE, PA', '{"Vessel"}'),
('4110', 'INDIANAPOLIS, IN', '{"Air"}'),
('4115', 'LOUISVILLE, KY', '{"Air"}'),
('4116', 'OWENSBORO, KY', '{"Air"}'),
('4121', 'LORAIN, OH', '{"Vessel","Air"}'),
('4122', 'ASHTABULA/CONNEAUT, OH', '{"Vessel"}'),
('4183', 'FORT WAYNE AIRPORT, IN', '{"Air"}'),
('4184', 'BLUE GRASS AIRPORT, KY', '{"Air"}'),
('4196', 'UPS, LOUISVILLE, KY', '{"Air"}'),
('4197', 'DHL CINCINNATI, OH', '{"Air"}'),
('4198', 'FEDERAL EXPRESS, INDIANAPOLIS, IN', '{"Air"}'),
('4501', 'KANSAS CITY, MO', '{"Air"}'),
('4502', 'ST JOSEPH, MO', '{"Air"}'),
('4503', 'ST LOUIS, MO', '{"Air"}'),
('4504', 'WICHITA, KS', '{"Air"}'),
('4505', 'SPRINGFIELD, MO', '{"Air"}'),
('4581', 'MIDAMERICAN AIRPORT, MASCOUTAH, IL', '{"Air"}'),
('4601', 'NEWARK, NJ', '{"Vessel","Air"}'),
('4602', 'PERTH AMBOY, NJ', '{"Vessel"}'),
('4670', 'UPS, NEWARK, NJ', '{"Air"}'),
('4671', 'FEDERAL EXPRESS, NEWARK, NJ', '{"Air"}'),
('4681', 'MORRISTOWN AIRPORT, NJ', '{"Air"}'),
('4701', 'JOHN F KENNEDY AIRPORT, NY', '{"Air"}'),
('4771', 'NYACC', '{"Air"}'),
('4772', 'DHL, JAMAICA, NY', '{"Air"}'),
('4773', 'MICOM, NY', '{"Air"}'),
('4774', 'AIR FRANCE (MACH PLUS), NY', '{"Air"}'),
('4778', 'TNT SKYPAK, NY', '{"Air"}'),
('4901', 'AGUADILLA, PR', '{"Vessel","Air"}'),
('4904', 'FAJARDO, PR', '{"Vessel"}'),
('4907', 'MAYAGUEZ, PR', '{"Vessel"}'),
('4908', 'PONCE, PR', '{"Vessel","Air"}'),
('4909', 'SAN JUAN, PR', '{"Vessel","Air"}'),
('4913', 'INTL AIRPORT, PR', '{"Air"}'),
('5101', 'CHARLOTTE AMALIE, VI', '{"Vessel","Air"}'),
('5102', 'CRUZ BAY, VI', '{"Vessel"}'),
('5104', 'CHRISTIANSTED, VI', '{"Vessel","Air"}'),
('5105', 'FREDERIKSTED, VI', '{"Vessel"}'),
('5201', 'MIAMI, FL', '{"Vessel"}'),
('5202', 'KEY WEST, FL', '{"Vessel","Air"}'),
('5203', 'PORT EVERGLADES, FL', '{"Vessel"}'),
('5204', 'WEST PALM BEACH, FL', '{"Vessel","Air"}'),
('5205', 'FORT PIERCE, FL', '{"Vessel","Air"}'),
('5206', 'MIAMI INTL AIRPORT, FL', '{"Air"}'),
('5210', 'FT. LAUDERDALE-HOLLYWOOD INTL.', '{"Air"}'),
('5295', 'UPS, MIAMI INTL AIRPORT, FL', '{"Air"}'),
('5296', 'DHL WORLDWIDE EXPRESS, MIAMI, FL', '{"Air"}'),
('5297', 'FEDERAL EXPRESS, MIAMI, FL', '{"Air"}'),
('5298', 'IBC COURIER HUB, MIAMI, FL', '{"Air"}'),
('5301', 'HOUSTON, TX', '{"Vessel"}'),
('5306', 'TEXAS CITY, TX', '{"Vessel"}'),
('5309', 'HOUSTON INTERCONTL, TX', '{"Air"}'),
('5310', 'GALVESTON, TX', '{"Vessel"}'),
('5311', 'FREEPORT, TX', '{"Vessel"}'),
('5312', 'CORPUS CHRISTI, TX', '{"Vessel"}'),
('5313', 'PORT LAVACA, TX', '{"Vessel"}'),
('5381', 'SUGAR LAND REGIONAL AIRPORT, TX', '{"Air"}'),
('5401', 'WASHINGTON, DC', '{"Vessel","Air"}'),
('5402', 'ALEXANDRIA, VA', '{"Vessel"}'),
('5501', 'DALLAS/FT. WORTH, TX', '{"Air"}'),
('5502', 'AMARILLO, TX', '{"Air"}'),
('5503', 'LUBBOCK, TX', '{"Air"}'),
('5504', 'OKLAHOMA CITY, OK', '{"Air"}'),
('5505', 'TULSA, OK', '{"Air"}'),
('5506', 'AUSTIN, TX', '{"Air"}'),
('5507', 'SAN ANTONIO, TX', '{"Air"}'),
('5582', 'MIDLAND INTER AIRPORT, TX', '{"Air"}'),
('5583', 'FORTH WORTH ALLIANCE AIRPORT, TX', '{"Air"}'),
('5584', 'ADDISON AIRPORT, TX', '{"Air"}'),
('8000', 'U.S. MAIL EXPORTS', '{"Vessel","Air","Rail","Road"}');


-- Update existing ports with Schedule D code and name normalization
-- We match primarily on Code if it exists (but it might not be in port_locations yet)
-- Or we match on Name if code is missing in DB

-- 1. Update existing records where Schedule D code matches (if any)
UPDATE public.ports_locations pl
SET 
    location_name = t.name,
    port_type = t.modes,
    updated_at = NOW()
FROM temp_aes_ports t
WHERE pl.schedule_d_code = t.code;

-- 1b. Cleanup: Reset schedule_d_code for ports that are NOT in the authoritative list
-- This removes invalid/outdated codes (like the bad 2786 assignments)
UPDATE public.ports_locations
SET schedule_d_code = NULL, port_type = NULL
WHERE schedule_d_code IS NOT NULL
AND schedule_d_code NOT IN (SELECT code FROM temp_aes_ports);

-- 2. Update existing records by Name where Schedule D code is NULL
UPDATE public.ports_locations pl
SET 
    schedule_d_code = t.code,
    port_type = t.modes,
    updated_at = NOW()
FROM temp_aes_ports t
WHERE pl.schedule_d_code IS NULL
AND (
    upper(pl.location_name) = upper(t.name)
    OR upper(pl.city) || ', ' || upper(pl.state_province) = upper(t.name) -- Match "CITY, ST" format
    OR upper(pl.location_name) LIKE upper(t.name) || '%' -- Partial match
);

-- 3. Insert NEW ports that don't exist
INSERT INTO public.ports_locations (
    location_name,
    schedule_d_code,
    port_type,
    country_code, -- Default to US for Appendix D
    country,
    created_at,
    updated_at
)
SELECT 
    t.name,
    t.code,
    t.modes,
    'US',
    'United States',
    NOW(),
    NOW()
FROM temp_aes_ports t
WHERE NOT EXISTS (
    SELECT 1 FROM public.ports_locations pl 
    WHERE pl.schedule_d_code = t.code
);

-- 4. Log the operation
INSERT INTO public.audit_logs (action, resource_type, details)
VALUES (
    'SEED_AES_APPENDIX_D', 
    'ports_locations', 
    jsonb_build_object(
        'description', 'Full seeding from Appendix D PDF',
        'record_count', 384,
        'source', 'appendix_d_port_cd_122025_508c.pdf'
    )
);

DROP TABLE temp_aes_ports;

COMMIT;
