-- Migration to seed MGL Matrix Quote with 4 carriers
-- Run this to create QUO-MGL-MATRIX-TEST for PDF generation testing

DO $$
DECLARE
  v_tenant_id uuid;
  v_customer_id uuid;
  v_quote_id uuid;
  v_version_id uuid;
  v_user_id uuid;
  v_template_id uuid;
  
  -- Master Data IDs
  v_curr_usd uuid;
  v_side_sell uuid;
  v_cat_freight uuid;
  v_cat_origin uuid;
  v_cat_dest uuid;
  v_cat_doc uuid;
  v_basis_cont uuid;
  v_basis_bl uuid;
  
  -- Location IDs
  v_port_origin uuid;
  v_port_dest uuid;
  
  -- Container IDs
  SELECT s.id INTO v_cont_20sd
  FROM container_sizes s
  JOIN container_types t ON s.container_type_id = t.id
  WHERE t.code IN ('20SD', '20GP') OR t.name ILIKE '%20%Standard%'
  LIMIT 1;

  SELECT s.id INTO v_cont_40sd
  FROM container_sizes s
  JOIN container_types t ON s.container_type_id = t.id
  WHERE t.code IN ('40SD', '40GP') OR t.name ILIKE '%40%Standard%'
  LIMIT 1;

  SELECT s.id INTO v_cont_40hq
  FROM container_sizes s
  JOIN container_types t ON s.container_type_id = t.id
  WHERE t.code = '40HC' OR t.name ILIKE '%40%High Cube%'
  LIMIT 1;
  v_carr_msc uuid;
  v_carr_maersk uuid;
  v_carr_cma uuid;
  v_carr_hl uuid;
  
  -- Option IDs
  v_opt_id uuid;
  
BEGIN
  -- 1. Get/Create Context (Tenant, User)
  SELECT id INTO v_tenant_id FROM public.tenants LIMIT 1;
  
  IF v_tenant_id IS NULL THEN
    INSERT INTO public.tenants (name, slug, subscription_tier)
    VALUES ('Miami Global Lines', 'mgl', 'enterprise')
    RETURNING id INTO v_tenant_id;
  END IF;

  SELECT id INTO v_user_id FROM auth.users LIMIT 1;
  
  -- 1.5 Get/Create/Update MGL-Main-Template
  -- This ensures the template exists and has the correct configuration for matrix table
  SELECT id INTO v_template_id FROM quote_templates WHERE name = 'MGL-Main-Template' AND tenant_id = v_tenant_id LIMIT 1;
  
  IF v_template_id IS NULL THEN
      INSERT INTO quote_templates (tenant_id, name, description, category, content, is_active, version)
      VALUES (
          v_tenant_id,
          'MGL-Main-Template',
          'Main Quotation Template with Matrix Rates',
          'General',
          '{
                "layout": "mgl_matrix",
                "header": { "show_logo": true, "company_info": true, "title": "QUOTATION" },
                "sections": [
                    { "type": "header", "height": 120, "content": { "text": "MGL Global Logistics" } },
                    { "type": "key_value_grid", "height": 100, "config": { "columns": 2 }, "grid_fields": [
                        { "key": "customer.company_name", "label": "Customer" },
                        { "key": "quote.quote_number", "label": "Quote Ref" },
                        { "key": "quote.created_at", "label": "Date", "format": "date" },
                        { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                        { "key": "customer.contact_name", "label": "Attn" },
                        { "key": "customer.address", "label": "Address" },
                        { "key": "customer.phone", "label": "Phone" },
                        { "key": "customer.email", "label": "Email" },
                        { "key": "customer.code", "label": "Customer Code" },
                        { "key": "customer.inquiry_number", "label": "Inquiry No" },
                        { "key": "quote.origin.location_name", "label": "Origin" },
                        { "key": "quote.destination.location_name", "label": "Destination" },
                        { "key": "quote.service_level", "label": "Service Level" }
                    ] },
                    {
                        "type": "detailed_matrix_rate_table",
                        "height": 300,
                        "page_break_before": false,
                        "config": {
                            "show_total": true,
                            "group_by": ["carrier", "transit_time", "frequency"]
                        },
                        "content": {
                            "text": "Freight Rates Breakdown"
                        }
                    },
                    { "type": "terms_block", "height": 150, "page_break_before": true, "content": { "text": "Terms and Conditions" } },
                    { "type": "footer", "height": 50, "page_break_before": false, "content": { "text": "Thank you for your business." } }
                ],
                "footer": { "text": "Generated by SOS Nexus" },
                "config": { "page_size": "A4", "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 }, "font_family": "Helvetica" }
          }'::jsonb,
          true,
          1
      ) RETURNING id INTO v_template_id;
  ELSE
      UPDATE quote_templates SET content = '{
            "layout": "mgl_matrix",
            "header": { "show_logo": true, "company_info": true, "title": "QUOTATION" },
            "sections": [
                { "type": "header", "height": 120, "content": { "text": "MGL Global Logistics" } },
                { "type": "key_value_grid", "height": 100, "config": { "columns": 2 }, "grid_fields": [
                    { "key": "customer.company_name", "label": "Customer" },
                    { "key": "quote.quote_number", "label": "Quote Ref" },
                    { "key": "quote.created_at", "label": "Date", "format": "date" },
                    { "key": "quote.expiration_date", "label": "Valid Until", "format": "date" },
                    { "key": "customer.contact_name", "label": "Attn" },
                    { "key": "customer.address", "label": "Address" },
                    { "key": "customer.phone", "label": "Phone" },
                    { "key": "customer.email", "label": "Email" },
                    { "key": "customer.code", "label": "Customer Code" },
                    { "key": "customer.inquiry_number", "label": "Inquiry No" },
                    { "key": "quote.origin.location_name", "label": "Origin" },
                    { "key": "quote.destination.location_name", "label": "Destination" },
                    { "key": "quote.service_level", "label": "Service Level" }
                ] },
                {
                    "type": "detailed_matrix_rate_table",
                    "height": 300,
                    "page_break_before": false,
                    "config": {
                        "show_total": true,
                        "group_by": ["carrier", "transit_time", "frequency"]
                    },
                    "content": {
                        "text": "Freight Rates Breakdown"
                    }
                },
                { "type": "terms_block", "height": 150, "page_break_before": true, "content": { "text": "Terms and Conditions" } },
                { "type": "footer", "height": 50, "page_break_before": false, "content": { "text": "Thank you for your business." } }
            ],
            "footer": { "text": "Generated by SOS Nexus" },
            "config": { "page_size": "A4", "margins": { "top": 40, "bottom": 40, "left": 40, "right": 40 }, "font_family": "Helvetica" }
      }'::jsonb
      WHERE id = v_template_id;
  END IF;

  -- 2. Get Currency
  SELECT id INTO v_curr_usd FROM public.currencies WHERE code = 'USD' LIMIT 1;
  
  -- 3. Get Charge Master Data
  SELECT id INTO v_side_sell FROM public.charge_sides WHERE code = 'sell' OR name ILIKE 'sell' LIMIT 1;
  IF v_side_sell IS NULL THEN
     INSERT INTO public.charge_sides (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Sell', 'sell', 'Sell side charge') 
     RETURNING id INTO v_side_sell;
  END IF;
  
  SELECT id INTO v_cat_freight FROM public.charge_categories WHERE code = 'freight' OR name ILIKE 'freight' LIMIT 1;
  IF v_cat_freight IS NULL THEN
     INSERT INTO public.charge_categories (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Freight', 'freight', 'Freight charges') 
     RETURNING id INTO v_cat_freight;
  END IF;

  SELECT id INTO v_cat_origin FROM public.charge_categories WHERE code = 'origin' OR name ILIKE 'origin' LIMIT 1;
  IF v_cat_origin IS NULL THEN
     INSERT INTO public.charge_categories (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Origin', 'origin', 'Origin charges') 
     RETURNING id INTO v_cat_origin;
  END IF;

  SELECT id INTO v_cat_dest FROM public.charge_categories WHERE code = 'destination' OR name ILIKE 'destination' LIMIT 1;
  IF v_cat_dest IS NULL THEN
     INSERT INTO public.charge_categories (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Destination', 'destination', 'Destination charges') 
     RETURNING id INTO v_cat_dest;
  END IF;

  SELECT id INTO v_cat_doc FROM public.charge_categories WHERE code = 'documentation' OR name ILIKE 'documentation' LIMIT 1;
  IF v_cat_doc IS NULL THEN
     INSERT INTO public.charge_categories (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Documentation', 'documentation', 'Documentation charges') 
     RETURNING id INTO v_cat_doc;
  END IF;
  
  SELECT id INTO v_basis_cont FROM public.charge_bases WHERE code = 'per_container' OR name ILIKE '%container%' LIMIT 1;
  IF v_basis_cont IS NULL THEN
     INSERT INTO public.charge_bases (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Per Container', 'per_container', 'Per container basis') 
     RETURNING id INTO v_basis_cont;
  END IF;

  SELECT id INTO v_basis_bl FROM public.charge_bases WHERE code = 'per_bl' OR name ILIKE '%bl%' LIMIT 1;
  IF v_basis_bl IS NULL THEN
     INSERT INTO public.charge_bases (tenant_id, name, code, description) 
     VALUES (v_tenant_id, 'Per B/L', 'per_bl', 'Per Bill of Lading basis') 
     RETURNING id INTO v_basis_bl;
  END IF;

  -- 4. Get/Update Containers
  
  -- 20SD
  SELECT cs.id INTO v_cont_20sd 
  FROM public.container_sizes cs
  JOIN public.container_types ct ON cs.container_type_id = ct.id
  WHERE ct.code = '20SD' OR ct.name ILIKE '%20%Standard%'
  LIMIT 1;

  IF v_cont_20sd IS NULL THEN
     DECLARE v_type_id uuid;
     BEGIN
         SELECT id INTO v_type_id FROM public.container_types WHERE code = '20SD';
         IF v_type_id IS NULL THEN
              INSERT INTO public.container_types (tenant_id, code, name, description, category)
              VALUES (v_tenant_id, '20SD', '20'' Standard Dry', 'Standard 20ft Container', 'Standard')
              RETURNING id INTO v_type_id;
          END IF;
         
         INSERT INTO public.container_sizes (
              container_type_id, length_ft, height_ft, width_ft, is_high_cube,
              internal_length_mm, internal_width_mm, internal_height_mm,
              door_width_mm, door_height_mm, capacity_cbm, max_payload_kg, tare_weight_kg, max_stack_weight_kg
          )
          VALUES (
              v_type_id, 20, 8.5, 8, false,
              5898, 2352, 2393,
              2340, 2280, 33.2, 25000, 2300, 192000
          )
          RETURNING id INTO v_cont_20sd;
     END;
  END IF;

  -- 40SD
  SELECT cs.id INTO v_cont_40sd 
  FROM public.container_sizes cs
  JOIN public.container_types ct ON cs.container_type_id = ct.id
  WHERE ct.code = '40SD' OR ct.name ILIKE '%40%Standard%'
  LIMIT 1;

  IF v_cont_40sd IS NULL THEN
     DECLARE v_type_id uuid;
     BEGIN
         SELECT id INTO v_type_id FROM public.container_types WHERE code = '40SD';
         IF v_type_id IS NULL THEN
              INSERT INTO public.container_types (tenant_id, code, name, description, category)
              VALUES (v_tenant_id, '40SD', '40'' Standard Dry', 'Standard 40ft Container', 'Standard')
              RETURNING id INTO v_type_id;
          END IF;
         
         INSERT INTO public.container_sizes (
              container_type_id, length_ft, height_ft, width_ft, is_high_cube,
              internal_length_mm, internal_width_mm, internal_height_mm,
              door_width_mm, door_height_mm, capacity_cbm, max_payload_kg, tare_weight_kg, max_stack_weight_kg
          )
          VALUES (
              v_type_id, 40, 8.5, 8, false,
              12032, 2352, 2393,
              2340, 2280, 67.7, 27600, 3750, 192000
          )
          RETURNING id INTO v_cont_40sd;
     END;
  END IF;

  -- 40HQ
  SELECT cs.id INTO v_cont_40hq 
  FROM public.container_sizes cs
  JOIN public.container_types ct ON cs.container_type_id = ct.id
  WHERE ct.code = '40HQ' OR ct.name ILIKE '%40%High%'
  LIMIT 1;

  IF v_cont_40hq IS NULL THEN
     DECLARE v_type_id uuid;
     BEGIN
         SELECT id INTO v_type_id FROM public.container_types WHERE code = '40HQ';
         IF v_type_id IS NULL THEN
              INSERT INTO public.container_types (tenant_id, code, name, description, category)
              VALUES (v_tenant_id, '40HQ', '40'' High Cube', 'High Cube 40ft Container', 'Standard')
              RETURNING id INTO v_type_id;
          END IF;
         
         INSERT INTO public.container_sizes (
              container_type_id, length_ft, height_ft, width_ft, is_high_cube,
              internal_length_mm, internal_width_mm, internal_height_mm,
              door_width_mm, door_height_mm, capacity_cbm, max_payload_kg, tare_weight_kg, max_stack_weight_kg
          )
          VALUES (
              v_type_id, 40, 9.5, 8, true,
              12032, 2352, 2698,
              2340, 2585, 76.4, 28600, 3900, 192000
          )
          RETURNING id INTO v_cont_40hq;
     END;
  END IF;

  -- 5. Get/Create Ports
  SELECT id INTO v_port_origin FROM public.ports_locations WHERE location_code = 'CNSHA' LIMIT 1;
  IF v_port_origin IS NULL THEN
    INSERT INTO public.ports_locations (location_name, location_code, location_type, country, city, is_active)
    VALUES ('Port of Shanghai', 'CNSHA', 'seaport', 'China', 'Shanghai', true)
    RETURNING id INTO v_port_origin;
  END IF;

  SELECT id INTO v_port_dest FROM public.ports_locations WHERE location_code = 'USMIA' LIMIT 1;
  IF v_port_dest IS NULL THEN
    INSERT INTO public.ports_locations (location_name, location_code, location_type, country, city, is_active)
    VALUES ('Port of Miami', 'USMIA', 'seaport', 'USA', 'Miami', true)
    RETURNING id INTO v_port_dest;
  END IF;

  -- 6. Get/Create Customer
  SELECT id INTO v_customer_id FROM public.accounts WHERE name = 'MGL Matrix Test Customer' LIMIT 1;
  IF v_customer_id IS NULL THEN
    INSERT INTO public.accounts (tenant_id, name, account_type, status)
    VALUES (v_tenant_id, 'MGL Matrix Test Customer', 'customer', 'active')
    RETURNING id INTO v_customer_id;
  END IF;

  -- 7. Get/Create Carriers
  -- MSC
  SELECT id INTO v_carr_msc FROM public.carriers WHERE name ILIKE 'MSC%' LIMIT 1;
  IF v_carr_msc IS NULL THEN
     INSERT INTO public.carriers (tenant_id, name, mode, scac) VALUES (v_tenant_id, 'MSC', 'ocean', 'MSCU') RETURNING id INTO v_carr_msc;
  END IF;
  
  -- Maersk
  SELECT id INTO v_carr_maersk FROM public.carriers WHERE name ILIKE 'Maersk%' LIMIT 1;
  IF v_carr_maersk IS NULL THEN
     INSERT INTO public.carriers (tenant_id, name, mode, scac) VALUES (v_tenant_id, 'Maersk', 'ocean', 'MAEU') RETURNING id INTO v_carr_maersk;
  END IF;

  -- CMA CGM
  SELECT id INTO v_carr_cma FROM public.carriers WHERE name ILIKE 'CMA%' LIMIT 1;
  IF v_carr_cma IS NULL THEN
     INSERT INTO public.carriers (tenant_id, name, mode, scac) VALUES (v_tenant_id, 'CMA CGM', 'ocean', 'CMDU') RETURNING id INTO v_carr_cma;
  END IF;
  
  -- Hapag-Lloyd
  SELECT id INTO v_carr_hl FROM public.carriers WHERE name ILIKE 'Hapag%' LIMIT 1;
  IF v_carr_hl IS NULL THEN
     INSERT INTO public.carriers (tenant_id, name, mode, scac) VALUES (v_tenant_id, 'Hapag-Lloyd', 'ocean', 'HLCU') RETURNING id INTO v_carr_hl;
  END IF;

  -- 8. Create Quote
  DELETE FROM public.quotes WHERE quote_number = 'QUO-MGL-MATRIX-TEST';
  
  INSERT INTO public.quotes (
    tenant_id, quote_number, title, account_id, status, total_amount, currency, created_by,
    origin_port_id, destination_port_id
  ) VALUES (
    v_tenant_id, 'QUO-MGL-MATRIX-TEST', 'MGL Matrix Test Quote', v_customer_id, 'draft', 0, 'USD', v_user_id,
    v_port_origin, v_port_dest
  ) RETURNING id INTO v_quote_id;

  -- Assign template to quote if column exists
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'quotes' AND column_name = 'template_id') THEN
      EXECUTE 'UPDATE public.quotes SET template_id = $1 WHERE id = $2' USING v_template_id, v_quote_id;
  END IF;

  -- 8.1 Create Quote Items (Legacy)
  INSERT INTO public.quote_items_legacy (
    quote_id, line_number, product_name, description, quantity, weight_kg, volume_cbm, package_category_id, hazmat_class
  ) VALUES 
  (v_quote_id, 1, 'Electronics', 'Computer Parts', 100, 500.00, 2.50, NULL, NULL),
  (v_quote_id, 2, 'Furniture', 'Wooden Chairs', 50, 1200.00, 15.00, NULL, NULL);

  -- 9. Create Version
  INSERT INTO public.quotation_versions (
    tenant_id, quote_id, version_number, is_current, status
  ) VALUES (
    v_tenant_id, v_quote_id, 1, true, 'draft'
  ) RETURNING id INTO v_version_id;

  -- Update quote with current version
  UPDATE public.quotes SET current_version_id = v_version_id WHERE id = v_quote_id;

  -- =================================================================
  -- CARRIER 1: MSC (20SD, 40SD, 40HQ)
  -- =================================================================
  
  -- 20SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_msc, v_cont_20sd, 25, v_curr_usd, 1650, 'MSC 20SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 1500, 1500, v_curr_usd, NULL),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 150, 150, v_curr_usd, 'THC/O');

  -- 40SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_msc, v_cont_40sd, 25, v_curr_usd, 2950, 'MSC 40SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 2800, 2800, v_curr_usd, NULL),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 150, 150, v_curr_usd, 'THC/O');

  -- 40HQ
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_msc, v_cont_40hq, 25, v_curr_usd, 3050, 'MSC 40HQ', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 2900, 2900, v_curr_usd, NULL),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 150, 150, v_curr_usd, 'THC/O');


  -- =================================================================
  -- CARRIER 2: Maersk (20SD, 40SD) - Remarks included
  -- =================================================================
  
  -- 20SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_maersk, v_cont_20sd, 22, v_curr_usd, 1700, 'Maersk 20SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 1550, 1550, v_curr_usd, 'Includes BAF'),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_doc, v_basis_bl, 1, 50, 50, v_curr_usd, 'Doc Fee'),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 100, 100, v_curr_usd, 'THC/O');

  -- 40SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_maersk, v_cont_40sd, 22, v_curr_usd, 3100, 'Maersk 40SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 2950, 2950, v_curr_usd, 'Includes BAF'),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_doc, v_basis_bl, 1, 50, 50, v_curr_usd, 'Doc Fee'),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 100, 100, v_curr_usd, 'THC/O');


  -- =================================================================
  -- CARRIER 3: CMA CGM (40HQ only)
  -- =================================================================
  
  -- 40HQ
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_cma, v_cont_40hq, 28, v_curr_usd, 3200, 'CMA CGM 40HQ', 'Bi-Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id, note)
  VALUES 
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 3000, 3000, v_curr_usd, 'Subject to GRI'),
  (v_tenant_id, v_opt_id, v_side_sell, v_cat_origin, v_basis_cont, 1, 200, 200, v_curr_usd, 'THC/O');


  -- =================================================================
  -- CARRIER 4: Hapag-Lloyd (20SD, 40SD, 40HQ)
  -- =================================================================
  
  -- 20SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_hl, v_cont_20sd, 24, v_curr_usd, 1600, 'HL 20SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id)
  VALUES (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 1600, 1600, v_curr_usd);

  -- 40SD
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_hl, v_cont_40sd, 24, v_curr_usd, 2900, 'HL 40SD', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id)
  VALUES (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 2900, 2900, v_curr_usd);

  -- 40HQ
  INSERT INTO public.quotation_version_options (
    tenant_id, quotation_version_id, carrier_id, container_size_id, total_transit_days, quote_currency_id, total_amount, option_name, frequency
  ) VALUES (
    v_tenant_id, v_version_id, v_carr_hl, v_cont_40hq, 24, v_curr_usd, 3000, 'HL 40HQ', 'Weekly'
  ) RETURNING id INTO v_opt_id;
  
  INSERT INTO public.quote_charges (tenant_id, quote_option_id, charge_side_id, category_id, basis_id, quantity, rate, amount, currency_id)
  VALUES (v_tenant_id, v_opt_id, v_side_sell, v_cat_freight, v_basis_cont, 1, 3000, 3000, v_curr_usd);

END $$;
