
-- Sync Domain: Real Estate
-- Generated by scripts/sync_domains.js

BEGIN;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.platform_domains WHERE name = 'Real Estate') THEN
    UPDATE public.platform_domains
      SET code = 'real_estate',
          description = 'Real Estate Management'
      WHERE name = 'Real Estate';
  ELSE
    INSERT INTO public.platform_domains (code, name, description)
    VALUES ('real_estate', 'Real Estate', 'Real Estate Management')
    ON CONFLICT (code) DO UPDATE SET
        name = EXCLUDED.name,
        description = EXCLUDED.description;
  END IF;
END $$;
COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'REAL_ESTATE';
COMMIT;
*/
