
-- Sync Domain: Customs & Compliance
-- Generated by scripts/sync_domains.js

BEGIN;

INSERT INTO public.platform_domains (code, name, description)
VALUES ('customs', 'Customs & Compliance', 'Regulatory compliance, HTS codes, and clearance.')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description;

COMMIT;

/*
-- ROLLBACK SECTION
-- Note: This rollback deletes the domain. If this was an update, you must manually restore the previous values.
BEGIN;
DELETE FROM platform_domains WHERE key = 'customs';
COMMIT;
*/
