// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gzhxgoigflftharcmdqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aHhnb2lnZmxmdGhhcmNtZHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1MTk2ODcsImV4cCI6MjA4NTA5NTY4N30.6xIZ3VYubUZ73pNPurzYuf-2RUpXj_9w-LpU-6d6kqU";

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Log configuration status for debugging
console.log('[Supabase] Initializing client with URL:', SUPABASE_URL);

const memoryStore = new Map<string, string>();

const safeStorage: Storage = {
  get length() {
    try {
      return localStorage.length;
    } catch {
      return memoryStore.size;
    }
  },
  clear() {
    try {
      localStorage.clear();
      return;
    } catch {
      memoryStore.clear();
    }
  },
  getItem(key: string) {
    try {
      return localStorage.getItem(key);
    } catch {
      return memoryStore.get(key) ?? null;
    }
  },
  key(index: number) {
    try {
      return localStorage.key(index);
    } catch {
      return Array.from(memoryStore.keys())[index] ?? null;
    }
  },
  removeItem(key: string) {
    try {
      localStorage.removeItem(key);
      return;
    } catch {
      memoryStore.delete(key);
    }
  },
  setItem(key: string, value: string) {
    try {
      localStorage.setItem(key, value);
      return;
    } catch {
      memoryStore.set(key, value);
    }
  },
};

const effectiveSupabaseUrl = SUPABASE_URL || 'http://localhost:54321';
const effectiveSupabaseKey = SUPABASE_PUBLISHABLE_KEY || 'missing-supabase-publishable-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(effectiveSupabaseUrl, effectiveSupabaseKey, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
